### ISSUE TITLE
[Bug] Cannot use vencord on latest Discord version

### ISSUE THREAD

**Issue by TonyGamer** [Vendicated/Vencord#1024]
### Discord Account

Tonì#7947

### What happens when the bug or crash occurs?

I was loading up my computer and discord was failing to update. After some basic troubleshooting, I uninstalled Vencord, and it worked just fine. After trying reinstall Vencord, however, the installation fails with the following text "rename C:\Users\User\AppData\Local\Discord\app-1.0.9012\resources\app.asar C:\Users\User\AppData\Local\Discord\app-1.0.9012\resources\_app.asar: The system cannot find the path specified"

It would seem that Discord has changed the file layout in their most recent update, which has broken Vencord.

### What is the expected behaviour?

Discord updates correctly. Vencord installation happens successfully without errors.

### How do you recreate this bug or crash?

1. Try and update Discord
2. Discord update fails
3. Uninstall Vencord and update
4. Try and reinstall Vencord
5. Installation fails

### Errors

`rename C:\Users\User\AppData\Local\Discord\app-1.0.9012\resources\app.asar C:\Users\User\AppData\Local\Discord\app-1.0.9012\resources\_app.asar: The system cannot find the path specified`

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Try reinstalling discord

**Comment by TonyGamer** [comment]
Thank you, that worked
