### ISSUE TITLE
[Bug] Silent Message Toggle button not consistent

### ISSUE THREAD

**Issue by cappscolton** [Vendicated/Vencord#1032]
### Discord Account

colton#8259

### What happens when the bug or crash occurs?

Silent Message Toggle button visual don't represent actual state of toggle.
2-parter:
In some cases I cannot disable the silent functionality via the button.
In some cases the button shows disabled when functionality is actually enabled.

### What is the expected behaviour?

Silent Message Toggle should begin with silent messages disabled (it does).
When you hit the button it should enable the functionality (it does).
When you send a message the button shouldn't change itself.
When you click "Disable Silent Message" the functionality should turn off.

### How do you recreate this bug or crash?

1. Enable Silent Message Toggle plugin
2. Go to a channel and type a message to verify that the functionality starts in Disabled.
3. Click "Enable Silent Message" button and send a message.
4. Verify that the button erroneously changed itself.
5. Verify that clicking the toggle button any number of times does not disable the functionality.
6. Verify that when the button represents a disabled state, the functionality is actually enabled.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by cappscolton** [comment]
Perhaps due to this line in combination with other problematic lines which I have yet to find:
https://github.com/Vendicated/Vencord/blob/bd95a25f4c111c3d0e2564fb1bfcf5b8e12e87de/src/plugins/silentMessageToggle.tsx#L54

**Comment by Nuckyz** [comment]
It is not really a bug because when I made it I intentionally made the button disable after you sent a message. I can make this a choosen behavior with a setting though

**Comment by cappscolton** [comment]
In the least rude way possible, I'm wondering if anyone at all would want that as default behavior. It seems unintuitive.

If the button is disabled at that point, why even have it visible, clickable, and changing visually on each click? Also, is it really a "toggle" if it can't be turned off?

The main reason I created this issue is because there is a secondary issue with the persistence setting functioning in an unintuitive way - which should be addressed after this is resolved.

**Comment by cappscolton** [comment]
Also, the fact that the button is intentionally disabled after sending a message doesn't really explain why it changes itself visually at that point.

**Comment by cappscolton** [comment]
Closing issue, discussed in discord. This is an issue arising from stable discord inconsistently grouping messages based on flags.
