### ISSUE TITLE
Stickers don't work

### ISSUE THREAD

**Issue by Henonicks** [Vendicated/Vencord#1043]
### Discord Account

Henonicks#7989

### What happens when the bug or crash occurs?

Every time I try to send a sticker from another server (with FakeNitro plugin enabled) there is an issue sending it

### What is the expected behaviour?

It has to send a link to the png of a sticker from another server I'm trying to send instead

### How do you recreate this bug or crash?

1. Go to a server that stickers
2. Go to DM's or another server
3. Try sending a sticker in DM's or another srvr

### Errors

```
Failed to load resource: the server responded with a status of 403 ()

Uncaught (in promise)

Uncaught (in promise)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by YellowBoiii** [comment]
same for me, maybe it's because of the new discord update

**Comment by Vendicated** [comment]
no it's because I messed it up lol

**Comment by ramhaidar** [comment]
![4363EBC679299937BFFB3FDC995A2834](https://user-images.githubusercontent.com/49301219/236061662-86e8d3a2-3bbe-4f99-a352-c89884683507.png)

**Comment by zcccccc1** [comment]
> ![4363EBC679299937BFFB3FDC995A2834](https://user-images.githubusercontent.com/49301219/236061662-86e8d3a2-3bbe-4f99-a352-c89884683507.png)

Getting the same error here!

**Comment by ramhaidar** [comment]
> > ![4363EBC679299937BFFB3FDC995A2834](https://user-images.githubusercontent.com/49301219/236061662-86e8d3a2-3bbe-4f99-a352-c89884683507.png)
> 
> Getting the same error here!

Thought it only happened to me :)

**Comment by InnitTho** [comment]
same issue on my end. Thought it was a linux thing
