### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by StormCrasher783** [Vendicated/Vencord#1055]
### Discord Account

StormCrasher783#9544

### What happens when the bug or crash occurs?

it just doesent work. when i download it, it never actually does anything. redownloaded 5 times.

### What is the expected behaviour?

im a noob at coding so idk

### How do you recreate this bug or crash?

click download vencord.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use our support channel
