### ISSUE TITLE
[Bug] VcNarrator 

### ISSUE THREAD

**Issue by Pfostierer** [Vendicated/Vencord#1058]
### Discord Account

Homeknopf#5982

### What happens when the bug or crash occurs?

VcNarrator does not find all windows Narrators. I am not sure if it is impossible use Natural Narrators/Voices. (((It also did not found the Desktop Voices)))

Plugin:
![image](https://user-images.githubusercontent.com/92048131/236414971-5f707d77-9826-4d58-b148-8479a49f9017.png)
Windows settings:
![image](https://user-images.githubusercontent.com/92048131/236415218-15081fa9-55c4-4263-9705-f007bcbfa754.png)

For the devs that are non US based: 

Currently Natural Voices/Narrators are only available in the US, to get them change the region to USA (restart PC or log out and log in) and try to download them under accessibility->voice output*. Install them and you can change back your region. 
Can't remember  the exact wording, also a VPN might be required.

### What is the expected behaviour?

Under the Narrator Voice in the plugin to find The natural voices

### How do you recreate this bug or crash?

1. Download more Narrator voices in Windows setting
2. Is not found the plugin menu

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
The plugin just uses the speechSynthesis Web api to retrieve voices, so it's out of our control
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices

**Comment by Vendicated** [comment]
Closing because this isn't something we can fix on our end. Hopefully a future Electron version will fix it
