### ISSUE TITLE
[Bug] MemberCount

### ISSUE THREAD

**Issue by something23-0001** [Vendicated/Vencord#1061]
### Discord Account

**ꜱᴏᴍᴇᴛʜɪɴɢ-0001**

### What happens when the bug or crash occurs?

![image](https://user-images.githubusercontent.com/14898342/236553805-387386f7-22c9-4487-8f8e-a72b2de1e2ab.png)

There is apparently 221 people online where there's not.

### What is the expected behaviour?

All the people that have their status not set to Offline be called "Online"

### How do you recreate this bug or crash?

1. Go to a channel.

### Errors

```
[Spellchecker] sh is not a valid locale.
Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 3ffb2a2fe2c3a8b21d01.js:7:123
    at async Promise.all (index 3)
```

No errors as far as Im aware that deal with this plugin, just a bug in the code.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/2834bed518a1fc1c384a93d599cc1b03555177c7
