### ISSUE TITLE
[Bug] Crashes and reloads randomly whilst in VC

### ISSUE THREAD

**Issue by Cammy16** [Vendicated/Vencord#1082]
### Discord Account

Citalopram 20mg#7329

### What happens when the bug or crash occurs?

after spending a random amount of time in a vc discord will just randomly reload with no input

### What is the expected behaviour?

that it doesnt reload discord randomly whilst in vc.

### How do you recreate this bug or crash?

1) join a vc
2) wait for a while, people stop talking
3) when you tab back into to discord it reloads the client and rejoins the vc

### Errors

api.spotify.com/v1/me/player:1          Failed to load resource: the server responded with a status of 401 ()
/api/v9/users/@me/survey:1          Failed to load resource: the server responded with a status of 429 ()
/api/v9/users/@me/notes/444881910490071050:1          Failed to load resource: the server responded with a status of 404 ()
/api/v9/streams/guild%3A756470589874765886%3A791709812630487060%3A444881910490071050/preview?version=1683554855717:1          Failed to load resource: the server responded with a status of 404 ()

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
This is related to Discord reaching 2gb memory usage (hard limit on 32bit electron) and running out of memory. Not a Vencord issue, just Discord having insane memory usage

Solutions:
- Leave some servers
- Use https://github.com/Vencord/Desktop, it has no memory limit
- Deal with it

**Comment by Cammy16** [comment]
Im only in like 5 servers and have 32GB of ram, i would like to screen share so until vendors desktop allows it I can't swap.
