### ISSUE TITLE
[Bug] Platform Indicators on Profile

### ISSUE THREAD

**Issue by ssylph** [Vendicated/Vencord#1083]
### Discord Account

sylph#0724

### What happens when the bug or crash occurs?

Spacing is weird between two different platform indicators
On client, spacing is closer
On web, spacing is farther
They seem to be the same element
![image](https://user-images.githubusercontent.com/103544605/236874797-e8b963d5-fb38-4b18-8e8c-f9f57b22efca.png)

### What is the expected behaviour?

Spacing should be normal as between default badges, and should not be the same class.

### How do you recreate this bug or crash?

Enable platform indicators plugin

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vendicated/Vencord/commit/7dcd32e838965c245f3984bef0c5ae4481672024

**Comment by ssylph** [comment]
![image](https://github.com/Vendicated/Vencord/assets/103544605/b578bc68-bd4a-4d3e-93cd-a6caf88938a9)

Now they're too far apart
