### ISSUE TITLE
[Feature Request] Install BetterDiscord's plugins or other plugins

### ISSUE THREAD

**Issue by Skorflex** [Vendicated/Vencord#1109]
### Discord Account

Iokza#9141

### What is it that you'd like to see?

English :

I think it would be cool to be able to apply our own plugins from an interface where we could add our own plugins or BetterDiscord plugins! Either through a kind of Repo plugin or like for the themes from the github links in RAW mode!

French : 

Je pense que ce serais cool de pouvoir appliquer nos propres plugins depuis une interface où on pourrait ajouter nos propres plugins ou des plugins de BetterDiscord ! Soit par un genre de pluginRepo ou comme pour les thèmes des liens github en mode RAW !

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
no
