### ISSUE TITLE
[Feature Request] Organize plugins list

### ISSUE THREAD

**Issue by ProffDea** [Vendicated/Vencord#1116]
### Discord Account

Dea#9535

### What is it that you'd like to see?

# Problem
Now with 122+ plugins, the 2x61 plugin list in Vencord is becoming difficult to parse through. The average consumer isn't going to read commit histories in the repo or updater to see if new plugins get added (actually just me / skill issue). This results in new plugins that get added to get buried and making the list more unbearable to read through.

# Solution 1
On the client, add a `Hide` button somewhere to each plugin in the list to send it to the shadow realm (a `Hidden` category to collapse/uncollapse maybe at the bottom of the list where you can unhide them). I don't wanna see and use the `Fart2` plugin every time I open the plugin page. This I can imagine being more easy than other potential solutions. The settings for hidden plugins can be in the local files that can get synced to the cloud.

# Solution 2
Add categories to put plugins under to be able to collapse/uncollapse groups of plugins. Much more difficult solution as it requires adding a new property to each individual plugin while coming up with an appropriate category to fit the specific plugin into which could cause a lot of discussion. It is also easy to make the situation worse with this solution if implemented improperly.

The categories would ideally be specific rather than vague like "`Spotify` > `Utilities`" otherwise the issue the category solution was suppose to solve will simply become the same issue with the majority of plugins falling under the utilities category. There should only be a few categories to prevent a long list of categories causing the same issue but this time with a list of categories instead.

Category name ideas can be `Meme`/`Fun`, `Developer`/`Dev`, `Voice Calls`, `Messages`, `3rd Party` (plugins that make use of 3rd party services, etc.

# Bonus
One special touch that would be great for new plugins would be a `New` category with **Solution 2** shown at the top that maybe shows 5-10 of the most recent plugins added. If not categories, then something or anything at all to show off new plugins.

If new plugins get shown off, it would be nice to be notified of them somehow. When the client gets updated that involves a new plugin, maybe add a toast when the client starts up notifying `X new plugin(s)!`

# Conclusion
I have a severe case of skill issue

### Request Agreement

- [X] This is not a plugin request

**Comment by Pierre2004** [comment]
Yes !
