### ISSUE TITLE
[Bug] MoreUserTags says everyone is a bot 

### ISSUE THREAD

**Issue by sprmcell** [Vendicated/Vencord#1122]
### Discord Account

sprmcell#2751

### What happens when the bug or crash occurs?

Says everyone (Admins/Owner/Mods) are bots, happens in multiple servers

![hi](https://cdn.discordapp.com/attachments/1053029549295812710/1107043151690092635/image.png)
![ily](https://cdn.discordapp.com/attachments/1053029549295812710/1107044925935210646/image.png)

### What is the expected behaviour?

The expected result is that it displays people correctly. 

### How do you recreate this bug or crash?

Open Vencord with listed plugin enabled and check member list

### Errors

```
no crash log
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Fixed
