### ISSUE TITLE
[Bug] Discord staff displayed as bots

### ISSUE THREAD

**Issue by RealZuko** [Vendicated/Vencord#1124]
### Discord Account

Mero#5496

### What happens when the bug or crash occurs?

It's a visual bug, displaying all/most discord employee's as bots, instead of users

### What is the expected behaviour?

I excepted to not see any badge next to account's nickname, but there is a bot bagde

### How do you recreate this bug or crash?

1. Join official discord server like DAC
2. Verify
3. Go to annoucnements
4. 
![image](https://github.com/Vendicated/Vencord/assets/128172119/28bed503-12d8-4335-886f-f2d34a4a539a)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by RealZuko** [comment]
fixed by restarting :|

**Comment by LeGeek01** [comment]
the issue come back with recent updates, but looks like pr #2146 fixed again the problem
