### ISSUE TITLE
[Feature Request] Lyrics as additional functionality to SpotifyControl

### ISSUE THREAD

**Issue by castdrian** [Vendicated/Vencord#1134]
### Discord Account

castdrian#0001

### What is it that you'd like to see?

It'd be nice to have the option to have lyrics if available above the controls as well

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
this is very out of scope for the plugin considering Spotify does not provide lyrics via their api. There also aren't any good free lyrics apis so you'd either have to pay for an api key or we'd have to scrape a site like genius which isn't possible without running into cors issues

Just google the lyrics
