### ISSUE TITLE
[Bug] PronounDB assigns pronouns to AutoMod

### ISSUE THREAD

**Issue by 0xallie** [Vendicated/Vencord#1136]
### Discord Account

alexia#0003

### What happens when the bug or crash occurs?

When someone with pronouns set gets filtered by AutoMod, the user's pronouns are assigned to AutoMod:

<img width="584" alt="Screenshot of the issue" src="https://github.com/Vendicated/Vencord/assets/482367/177b1cac-95a1-43c9-8c10-e0a09680da98">

### What is the expected behaviour?

The pronouns should either be inside the embed or just hidden entirely.

### How do you recreate this bug or crash?

1. Set your pronouns on PronounDB
2. Enable the PronounDB plugin
3. Trigger an AutoMod rule with report channel enabled
4. View AutoMod logs

### Errors

N/A

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by somerandomcloud** [comment]
bad issue, let AutoMod express their identity however they want.

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/bb83c0b672abc5cb812e23d704880e1750fa61e6
