### ISSUE TITLE
[Bug] Windows 10's Default Window Title Bar shows instead of Discord's Custom One

### ISSUE THREAD

**Issue by JaegerwaldDev** [Vendicated/Vencord#1144]
### Discord Account

Jaegerwald#4833

### What happens when the bug or crash occurs?

1. Obviously the custom Title Bar isn't working, and is basically exactly like on Vencord Desktop
##### Vencord
<img src="https://media.discordapp.net/attachments/1093265842755616809/1108023772566524006/image.png">

##### Discord/Discord Canary
<img src="https://cdn.discordapp.com/attachments/1093265842755616809/1108024070299193385/image.png">
3. Discord's CSS and Custom Theme CSS sort of breaks
<img src="https://cdn.discordapp.com/attachments/1093265842755616809/1108022864873017424/image.png"/>
<img src="https://cdn.discordapp.com/attachments/1093265842755616809/1108022933500203008/image.png"/>

### What is the expected behaviour?

It should have a custom title bar.

### How do you recreate this bug or crash?

I do not know, but it first ocurred when I updated to Discord's Birthday Update. It works as expected when you unpatch Discord/Discord Canary.

### Errors

```
None
```

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
does it happen on stable too

**Comment by solomoncyj** [comment]
check openasar settings

**Comment by Vendicated** [comment]
You probably enabled native titlebar in Vencord settings, disable it

**Comment by JaegerwaldDev** [comment]
> You probably enabled native titlebar in Vencord settings, disable it

Yup that was it, thanks.

**Comment by solomoncyj** [comment]
lol. fastest issue close i have ever seen
