### ISSUE TITLE
[Bug] Logged off from Discord account after trying to Inspect element

### ISSUE THREAD

**Issue by nasko222** [Vendicated/Vencord#1171]
### Discord Account

nasko222#1337

### What happens when the bug or crash occurs?

I tried to inspect element something and I got logged out of my account, and needed to log back in

### What is the expected behaviour?

I expected Inspect element to work fine, However it works fine after I logged back in, It also happened the first time to my friend who also used Vencord, but no longer happens now

### How do you recreate this bug or crash?

1. CTRL + SHIFT + I
2. Inspect element on something
3. Try to change some text and realize that discord will log you off your account (If this is the first time you do this)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Redundakitties** [comment]
This is not a bug. This happens b/c whenever dev tools is open, discord hides your token to prevent dumb users from being scammed.  if your discord reloads for any reason (such as running out of memory due to having the dev tools open), discord can't find your token and you are logged out. 

Fix: enable the NoDevtoolsWarning plugin

**Comment by D-Maxwell** [comment]
> This is not a bug. This happens b/c whenever dev tools is open, discord hides your token to prevent dumb users from being scammed. if your discord reloads for any reason (such as running out of memory due to having the dev tools open), discord can't find your token and you are logged out.
> 
> Fix: enable the NoDevtoolsWarning plugin

Enabling the plugin does in fact prevent forced log outs, however dev tools are still inaccessible given that Discord will reload a few seconds past releasing the inspector hotkey.
What am I doing wrong ?

**Comment by AutumnVN** [comment]
https://vencord.dev/faq/#Why-does-my-Discord-always-crash-when-opening-DevTools?

**Comment by Vendicated** [comment]
This issue was closed 5 months ago. Please do not necro old issues
