### ISSUE TITLE
[Bug] Vencord does not detect any activities

### ISSUE THREAD

**Issue by Ashureth-dev** [Vendicated/Vencord#1179]
### Discord Account

Ashureth#0125

### What happens when the bug or crash occurs?

The bug happens all the time, no matter if I restart it.  The activity toggle is on and thes settngs are like they should be.

### What is the expected behaviour?

I expect my profile to display my current activity.

### How do you recreate this bug or crash?

1. Just open Vencord

### Errors

```
There is no error in my console.
```

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Disable NoRPC / use normal patched Discord Desktop instead of Vencord Desktop
