### ISSUE TITLE
Mic Input Increase

### ISSUE THREAD

**Issue by Clqn** [Vendicated/Vencord#1180]
### Discord Account

Zeal#0255

### What is it that you'd like to see?

Private Client That has a feature to increase mic input through client ( similar to the ripcord feature) I will be paying

### Request Agreement

- [X] This is not a plugin request

**Comment by somerandomcloud** [comment]
Not even remotely the correct place to ask about this... What does this even mean :sob:

**Comment by ItzOnlyAnimal** [comment]
its called ripcord because you will be RIP after using it

**Comment by somerandomcloud** [comment]
i will rip you to shreds (I am ripped)
