### ISSUE TITLE
[Bug] UwUify also UwUs URLs

### ISSUE THREAD

**Issue by Vukkyy** [Vendicated/Vencord#1186]
### What happens when the bug or crash occurs?

When you post a message with a link in it, it will also attempt to UwUify the link, which will probably cause a broken link if it happens to have the letters "r" and "l" in it.

### What is the expected behaviour?

Not UwUifying the link

### How do you recreate this bug or crash?

1. Try to UwUify a message with a link in it.
2. It does letter substitution on your link.
3. The wink is bwoken nyow 3:

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by exhq** [comment]
dont try. vendy doesnt give a shit about uwuifier. as much as it hurts for me to see, it seems like they completely ignore me and uwuifier
