### ISSUE TITLE
[Bug] InvisibleChat plugin modal not working

### ISSUE THREAD

**Issue by Seb-135** [Vendicated/Vencord#1192]
### What happens when the bug or crash occurs?

I cannot send encrypted messages whatsoever. The button is added to the message box, clicking it opens the modal, and I can type in it, but pressing "Send" does nothing - it does not close the modal, and it does not send a message.
I am using the Vencord extension for Firefox from mozilla.org. Unsure if it happens with other platforms.

### What is the expected behaviour?

I expect the plugin to send a message.

### How do you recreate this bug or crash?

1. Install vencord on firefox
2. Enable InvisibleChat
3. Open "Encrypt Message" and fill out the popup
4. Press send

### Errors

```
Uncaught TypeError: bu is undefined
    ay VencordWeb:86
    onClick VencordWeb:86
    Me https://discord.com/assets/ad1fde4a477ddef962ae.js:1731
    je https://discord.com/assets/ad1fde4a477ddef962ae.js:1731
    Ur https://discord.com/assets/ad1fde4a477ddef962ae.js:1752
    Ur https://discord.com/assets/ad1fde4a477ddef962ae.js:1752
    Gr https://discord.com/assets/ad1fde4a477ddef962ae.js:1752
    Yr https://discord.com/assets/ad1fde4a477ddef962ae.js:1758
    cc https://discord.com/assets/ad1fde4a477ddef962ae.js:1823
    Le https://discord.com/assets/ad1fde4a477ddef962ae.js:1730
    Yr https://discord.com/assets/ad1fde4a477ddef962ae.js:1754
    Kt https://discord.com/assets/ad1fde4a477ddef962ae.js:1737
    Zt https://discord.com/assets/ad1fde4a477ddef962ae.js:1737
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
works for me, likely related to firefox failing to remove CSP
