### ISSUE TITLE
[Bug] Website fails to load

### ISSUE THREAD

**Issue by Seb-135** [Vendicated/Vencord#1194]
### What happens when the bug or crash occurs?

Sometimes when reloading the page with the Vencord Firefox extension enabled, seemingly randomly, the entire page simply fails to load. A shift+ctrl+R seems to fix it every time, but that's annoying.
![image](https://github.com/Vendicated/Vencord/assets/76539951/0454837f-1dbe-4023-adc8-f2fc45f39584)
This also happened immediately after installation, before enabling any plugins, adding any themes, or touching any settings in general. Here, the errors in console appear to just be due to the way I invalidate theme css links, as there's currently no way to disable them and keep them on hand (and I also get the same errors on a successful load)

In fact, comparing the output of a successful load, it seems that nothing that appears in the console on a failed load is out of the ordinary:
![image](https://github.com/Vendicated/Vencord/assets/76539951/e7fe7f70-8266-490a-a245-40f2c4d24a90)
Rather, the issue seems to be what's _not_ present in the console log.

One other thing to note, I've had this occur while in a DM or server, but never on the default Friends screen, `discord.com/channels/@me`

### What is the expected behaviour?

I expect the website to load.

### How do you recreate this bug or crash?

1. Add the FF Vencord extension
2. Navigate around Discord and press ctrl+r several times in different places
3. Get randomly flashbanged with a white screen

### Errors

Seems that there isn't an actual error, but `Vencord   WebpackInterceptor  Patching webpackChunkdiscord_app.push` is missing entirely from the console on a failed load.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
hi! this should be fixed via https://github.com/Vendicated/Vencord/commit/a2a33ca62d4651c11829e8d7d0504bbda57fa0f4 now

Please verify whenever you get the update (should be available in ~10 minutes)

**Comment by Seb-135** [comment]
I've been reloading for several minutes now and it appears fixed - not a single white screen, and I've managed to get both new messages in console, so it seems the fallback works just fine.
Thanks!

**Comment by Vendicated** [comment]
neat, thanks for verifying!
