### ISSUE TITLE
[Feature Request] Install BetterDiscord Plugins

### ISSUE THREAD

**Issue by Tasye24** [Vendicated/Vencord#1221]
### Discord Account

Tasye#0239

### What is it that you'd like to see?

Is it possible in Vencord or will be possible to make [BetterDiscord](https://betterdiscord.app/plugins) Plugins available on Vencord ?
Like a new tab in settings called "Plugins Repo" (like what purpose [this plugin](https://betterdiscord.app/plugin/PluginRepo) [(alternative link)](https://betterdiscord.app/plugin/PluginRepo) but by default in Vencord)

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
no

**Comment by ImAFrogOwO** [comment]
hahah funny vee say bd is made of low quality plugins. this is possible but not in this repo
