### ISSUE TITLE
[Bug] anonymiseFileNames plugin wrongly scrambles .tar.[gx]z extension

### ISSUE THREAD

**Issue by 0x3C50** [Vendicated/Vencord#1230]
### Discord Account

0x150#9699

### What happens when the bug or crash occurs?

Uploading a file ending in ".tar.[gx]z" results in the filename being scrambled to "(random file name).[gx]z", nuking the `.tar` extension part.

### What is the expected behaviour?

The plugin should recognize the ".tar.[gx]z" suffix, and include it as one extension

### How do you recreate this bug or crash?

1. Upload a file called "test.tar.gz"
2. Observe, the file name is changed to "(randomized).gz"

### Errors

\-

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vendicated/Vencord/commit/fe80b8cc8586f3119076a99c610f36d7824985a9
