### ISSUE TITLE
[Feature Request] Button "Copy Full Emoji ID" in emoji panel 

### ISSUE THREAD

**Issue by D3anDark** [Vendicated/Vencord#1234]
### Discord Account

DeanDark#8006

### What is it that you'd like to see?

I would like that when I press the right mouse button. There would be a button that would give the whole ID of the emoticon ( <:emoji:1234567890> ). 

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
?
![image](https://github.com/Vendicated/Vencord/assets/45497981/f5da50be-aff6-421d-a80b-d4cdbdbb6028)

**Comment by IThundxr** [comment]
my man just add \ before the emoji and get the id its not rocket science

**Comment by D3anDark** [comment]
> ? ![image](https://user-images.githubusercontent.com/45497981/245328422-f5da50be-aff6-421d-a80b-d4cdbdbb6028.png)

Because it's a option, but okay. I un check
