### ISSUE TITLE
[Bug] viewIcons plugin: the "View Server Avatar" button never returns GIFs

### ISSUE THREAD

**Issue by lumap** [Vendicated/Vencord#1236]
### Discord Account

Lumap#0001

### What happens when the bug or crash occurs?

When a member has an animated server avatar, right-clicking on their profile and clicking server avatar only shows the webp version of their avatar instead of the GIF one

### What is the expected behaviour?

a GIF avatar is shown instead

### How do you recreate this bug or crash?

1. Have a member with an animated server avatar
2. Right click -> View server avatar

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by KannaDev** [comment]
I have tested this, and it seems to work perfectly fine with animated server avatars. It loads the .gif, instead of .webp.

**Comment by lumap** [comment]
dunno what's up with mine then, [video](https://cdn.discordapp.com/attachments/1020339327831658629/1121220708102590594/Enregistrement_de_lecran_2023-06-22_a_01.30.11.mov)

**Comment by KannaDev** [comment]
The only thing I can really think of is that the avatar you're using is a .webp 😕 
Have you tried checking other users?

**Comment by lumap** [comment]
yeah tried other users and everything from gifs to webp, they all show as webp with that button

**Comment by KannaDev** [comment]
Quite unusual, mind sending me an invite to somewhere which has the issue so I can test it myself? @friendships

**Comment by lumap** [comment]
made a lil [server](https://discord.gg/qz4ygk6A)
