### ISSUE TITLE
[Feature Request] [Translate] setting request

### ISSUE THREAD

**Issue by jqms** [Vendicated/Vencord#1237]
### Discord Account

jqms#6969

### What is it that you'd like to see?

add a setting to make the translate button show in context menu instead of the weird menu when you hover messages 
![image](https://github.com/Vendicated/Vencord/assets/65556454/0e96984a-44de-46f7-9de6-bd313d14345a)

### Request Agreement

- [X] This is not a plugin request

**Comment by ArjixWasTaken** [comment]
Why not both?

Could instead make it so that there are two settings, for the two buttons

**Comment by Vendicated** [comment]
Added (without settings)
