### ISSUE TITLE
[Feature Request] Remove annoying discord menu at the top

### ISSUE THREAD

**Issue by Fenish** [Vendicated/Vencord#1240]
### Discord Account

fenish#0001

### What is it that you'd like to see?

If you open youtube video that sent to a channel full screen everything is okay.
But if you leave fullscreen via pressing button at the bottom right, there is annoying menu pops up at the top

# Before

![image](https://github.com/Vendicated/Vencord/assets/46840264/1450827e-68b0-4572-b2bb-1f0d47153679)

# After

![image](https://github.com/Vendicated/Vencord/assets/46840264/768d6829-19f6-430d-8c96-ae02a4fb16cc)

### Request Agreement

- [X] This is not a plugin request

**Comment by ItzOnlyAnimal** [comment]
this is plugin request

**Comment by Fenish** [comment]
> this is plugin request

But this is not about plugins this is discord's vanilla shitness. It is kinda bug. If you exit via pressing esc, everything is fine.
If you click exit full screen button, this menu appears

**Comment by ImLvna** [comment]
That is still a plugin request. You are requesting we make a plugin to fix vanilla discord’s issues

**Comment by Fenish** [comment]
> That is still a plugin request. You are requesting we make a plugin to fix vanilla discord’s issues

basically every feature request is plugin request isn't it?

**Comment by ItzOnlyAnimal** [comment]
A feature request is changing/adding something related to vencord itself, a plugin request is roughly anything that modifies discord's code including fixing bugs (FixInbox for example)

**Comment by ImLvna** [comment]
[:3](https://github.com/Vendicated/Vencord/discussions/new?category=ideas)

**Comment by Vendicated** [comment]
pressing alt should hide it

**Comment by Fenish** [comment]
> pressing alt should hide it

nope we already tried lots of things. thats why i opened request

**Comment by Fenish** [comment]
> pressing alt should hide it

i use arch btw
