### ISSUE TITLE
[Feature Request] VcNarrator - ignore stage channels 

### ISSUE THREAD

**Issue by Avenred** [Vendicated/Vencord#1247]
### What is it that you'd like to see?

It would be nice if VcNarrator had a setting to ignore stage channels. Since these channels have a lot of people leaving/join very quickly, it leads to the narrator constantly talking.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/f09b44b0d5acbcb67570727ebdd10102a2c707f8
