### ISSUE TITLE
[Bug] Message Logger not ignoring bot edited image posts, not letting you discard history from edited image only posts

### ISSUE THREAD

**Issue by shinji257** [Vendicated/Vencord#1269]
### Discord Account

Shinji#6227

### What happens when the bug or crash occurs?

Two bugs here.  If you want me to split them then let me know.

Bug 1) When you have it ignore bot messages it still tracks changes from image only posts that are generated by bots.
Bug 2) It fails to give the option to remove history for bot generated image posts.
![image](https://github.com/Vendicated/Vencord/assets/261005/f4a92bd3-afba-4de2-9b95-b3c6f91e198d)

Settings: 
![image](https://github.com/Vendicated/Vencord/assets/261005/44ba84ba-af6f-44ce-8f95-0126b6df9ea4)

### What is the expected behaviour?

Image posts should update normally as if the plugin wasn't even enabled when ignoring bots is enabled.  If the option is disabled the ability to remove message history for the post should be present.

### How do you recreate this bug or crash?

1. Enable Message History.  Set as settings show above.
2. Go on a discord with a bot that is capable of editing its own image only post (no text).  

I'm not sure how many bots there are like that.  The bot we use on my discord can do this but it is written by someone we know and is part of the AMP (Game Servers...) package.

### Errors

This is the only error I get but I don't believe it is related to the above.  It doesn't show when the messages are updated.
```
331bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by shinji257** [comment]
Just alerting that this is still happening with the latest commits to the plugin and I tried to both ignore the bot via user id as well as ignore the channel that this is happening (new feature) with no success.

**Comment by Vendicated** [comment]
is this still happening now?

**Comment by shinji257** [comment]
Unknown as I'll be unable to reproduce it.  We no longer use the bot for unrelated reasons.

**Comment by MemeHovy** [comment]
> is this still happening now?

idk if this comment will get removed but I can confirm the 2nd one doesn't happen anymore

**Comment by Vendicated** [comment]
thank you

**Comment by MemeHovy** [comment]
> thank you

np
