### ISSUE TITLE
[Feature Request] Middle mouse button scrolling

### ISSUE THREAD

**Issue by KronsyC** [Vendicated/Vencord#1271]
### Discord Account

Kronsy#0556

### What is it that you'd like to see?

I think that discord used to have middle mouse button scrolling, by middle clicking then physically moving the mouse up or down, it made browsing channel histories much faster IMO and would be cool if it was brought back 

### Request Agreement

- [X] This is not a plugin request

**Comment by IThundxr** [comment]
This already exists?

**Comment by KronsyC** [comment]
Does it? alrighty sorry about that

**Comment by IThundxr** [comment]
yea it does i think it doesnt on linux but theres ways to get it on linux

**Comment by KronsyC** [comment]
Oh that makes sense, middle mouse is paste on linux, so thats why its not being captured

**Comment by Charlignon** [comment]
Hello ! TL;DR the need for such a plugin exist and is not negligible, so I would suggest to reopen the issue :)

Middle click auto-scroll does exist on Chromium/Electron, but it is enabled [only on Windows](https://niek.github.io/chrome-features/#:~:text=MiddleClickAutoscroll). Mac and Linux user can use the `--enable-blink-features=MiddleClickAutoscroll` flag when start their browser/app, but it is considered [a bad practice](https://issues.chromium.org/issues/40811836) to use these flags. Additionally, it does not prevent Middle Click Paste (selection buffer) on Linux-based systems (X11 and Wayland), and there's no workaround for that. Further support from Chromium does not seem to be planned.

So to sum up a bit:
- Gecko browsers (Firefox) : ✅ Supports autoscroll on all platforms
- Chromium browsers (Chrome, Opera, Brave, etc) : 
  - Windows ✅
  - Mac :warning: can use the flag OR use an addon such as [this one](https://github.com/Pauan/AutoScroll)
  - Linux :warning::warning: can use the flag (BUT no middle click paste support) OR use an addon
- Chromium/Electron apps (Discord, Vesktop) : 
   - Windows ✅ (? not sure, can't test it)
   - Mac :warning: can use the flag
   - Linux ❌ can use flag, but every click will paste content in the app

So there's a real need for such plugin on Vencord. You can read more on [this Vesktop issue](https://github.com/Vencord/Vesktop/issues/171). Additionally, a [similar plugin](https://github.com/hackermare/BD-AutoScroll) exists for BetterDiscord. While I acknowledge the differences between both systems, this mean that development effort should be minimal.

Thank you for your consideration !
