### ISSUE TITLE
[Feature Request] Remove Put Notification for Cloud Settings

### ISSUE THREAD

**Issue by JustArion** [Vendicated/Vencord#1274]
### Discord Account

`_arion`

### What is it that you'd like to see?

Hi, currently [settingsSync.ts#L152](
https://github.com/Vendicated/Vencord/blob/3680c26f724a77fcb3b66f24264bcd4556d15bbf/src/utils/settingsSync.ts#L152), from the method [putCloudSettings](https://github.com/Vendicated/Vencord/blob/3680c26f724a77fcb3b66f24264bcd4556d15bbf/src/utils/settingsSync.ts#L124) shows a notification to the user whenever they start the client (and upon explicitly clicking "Sync to Cloud").

My suggestion is, remove the notification that occurs on client startup but keep the one that the user explicitly clicks.
No one likes overly informative things unless there's an error (or they're a developer working on the program)

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
already done yesterday, will ariive in stable soon https://github.com/Vendicated/Vencord/commit/f1349a27874cb7576455af38165abfea91a565a7
