### ISSUE TITLE
[Feature Request] [ImageZoom] More settings

### ISSUE THREAD

**Issue by Seb-135** [Vendicated/Vencord#1288]
### What is it that you'd like to see?

More customisation for the ImageZoom plugin would be great - I had 2 extra settings in mind.
1. Option to be able to use a square lens.
A square lens makes it significantly easier to read text. Similar to Lighty's plugin for BD, [BetterImageViewer](https://1lighty.github.io/BetterDiscordStuff/?plugin=BetterImageViewer).
2. Ability to change scaling algorithm.
I would like to be able to choose nearest neighbour for the scaling method as I look at a lot of 1:1 pixel art on discord, and ImageZoom isn't great for zooming in on it, as its scaling blurs the image. 
I'm not sure if scaling methods other than NN and the current one should be implemented, as they may be too niche. Maybe if someone's bored enough :)

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
2 was added a while ago. I just added 1 in https://github.com/Vendicated/Vencord/commit/b607eebcb709daee421aba4e19d7729e4766b974
