### ISSUE TITLE
[Feature Request] ClearURLs (Add function for fx and vx)

### ISSUE THREAD

**Issue by SkyRider13** [Vendicated/Vencord#1299]
### Discord Account

skyrider1570

### What is it that you'd like to see?

The plugin is great but at the moment it seems to be unable to remove thesame tracking stuff from any twitter URL I post that uses "vx" and "fx" for example 
https://twittervx.com/Dexerto/status/1669345035639492609?t=2c86_jcBxl9gK7EhefNT6Q&s=33, 
https://fxtwitter.com/NoContextHumans/status/1669279210609729536?t=PDA9-QyuwOY03_IfwPy9pA&s=19 and
https://vxtwitter.com/NoContextHumans/status/1669279210609729536?t=PDA9-QyuwOY03_IfwPy9pA&s=19 
don't get cleared but a normal twitter link of each of these still does.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
This feature request doesn't make a lot of sense. These tracking params do nothing on twitter alternatives, so stripping them is kinda senseless. Plus if you use the Vencord TextReplace plugin to convert twitter -> fxtwitter automagically, the stripping works correctly
