### ISSUE TITLE
the powershell installer trolls

### ISSUE THREAD

**Issue by poob1** [Vendicated/Vencord#13]
Method invocation failed because [Microsoft.PowerShell.Commands.MatchInfo] does not contain a method named 'Get'.

^ that is what it says

**Comment by MeguminSama** [comment]
Can you give me your windows version (run `winver` and show output) and also in powershell run `$PSVersionTable. PSVersion` and show the output of that?

**Comment by poob1** [comment]
![image](https://user-images.githubusercontent.com/78015856/191739961-64638691-c6af-4c7d-a3bf-38dfe349927f.png)
![image](https://user-images.githubusercontent.com/78015856/191740169-fff52e63-27c4-4612-992a-af58012fad43.png)
@MeguminSama

**Comment by MeguminSama** [comment]
I'll look into it in a bit

**Comment by x6r** [comment]
the powershell script only works with [Powershell Core](https://github.com/powershell/powershell) (v7.x) with the execution policy set to `RemoteSigned`:
```pwsh
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
```

**Comment by FayneAldan** [comment]
Might be a good idea to add a `#Requires` statement:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7.2#-version-nn

**Comment by Vendicated** [comment]
🦀  🦀 powershell installer is gon!! 🦀 🦀
