### ISSUE TITLE
[Bug] nitro themes are persisting in fakenitro

### ISSUE THREAD

**Issue by localwhale20** [Vendicated/Vencord#1304]
### Discord Account

@danilwhale

### What happens when the bug or crash occurs?

nitro themes again don't work with fakenitro

### What is the expected behaviour?

select nitro theme and it would enable forever, not for 10 nanoseconds

### How do you recreate this bug or crash?

(assumes that you already enabled fakenitro)
1. open user settings
2. open appearance
3. select theme you want
4. look how your theme disappears

### Errors

[discord_protos.discord_users.v1.PreloadedUserSettings] Updating appearance with delay 0
0034ebd72a91573d17ea.js:9961 [discord_protos.discord_users.v1.PreloadedUserSettings] Scheduling save from markDirty
0034ebd72a91573d17ea.js:9961 [discord_protos.discord_users.v1.PreloadedUserSettings] Persisting proto

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by KannaDev** [comment]
Unsure as to what you are referring to. As setting themes on a Non Nitro Account with Fake Nitro works fine, just doesn't appear correctly in settings.
![DiscordCanary_XyMeHvI3QK](https://github.com/Vendicated/Vencord/assets/65371696/3e566257-2a98-42d7-bb19-b1a5f2da5c78)

**Comment by Nuckyz** [comment]
> Unsure as to what you are referring to. As setting themes on a Non Nitro Account with Fake Nitro works fine, just doesn't appear correctly in settings. ![DiscordCanary_XyMeHvI3QK](https://user-images.githubusercontent.com/65371696/247783915-3e566257-2a98-42d7-bb19-b1a5f2da5c78.png)

how does it not appear correctly in settings?

**Comment by gk98s** [comment]
I have a similar issue. Setting it works fine, until i restart discord. It reverts back to the normal dark theme.
