### ISSUE TITLE
[Feature Request] A button to change Discord sounds

### ISSUE THREAD

**Issue by Venus5687** [Vendicated/Vencord#1311]
### Discord Account

LeoTheSmart#7576

### What is it that you'd like to see?

I would like to see a feature to edit the Discord sounds for example the ping sound etc. I would love to see that!

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
![Screenshot_20230619-135826_Bromite__01](https://github.com/Vendicated/Vencord/assets/45497981/85e440a9-9950-4103-9b30-746111249e13)
