### ISSUE TITLE
[Bug] Fake Nitro Streaming crash

### ISSUE THREAD

**Issue by BudImCanadian** [Vendicated/Vencord#1318]
### Discord Account

deepinyahmum

### What happens when the bug or crash occurs?

While streaming with fakenitro plugin discord will crash while scrolling through chats or randomly. May be due to Diablo IV

### What is the expected behaviour?

To be able to stream in higher quality than standard

### How do you recreate this bug or crash?

Begin streaming with fakenitro at 1080p+ scroll through chats. tab in and out if you have to and it will eventually crash you out. "states plugin may of failed try again error" not quoted exactly but you know what error im referring to. 

### Errors

```
![image](https://github.com/Vendicated/Vencord/assets/133236920/45852083-7eda-4ce2-b5ab-d2a80697987e)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by BudImCanadian** [comment]
Idk how to find the crash report

**Comment by aamiaa** [comment]
Your screenshot shows that you're using BetterDiscord, not Vencord.

**Comment by somerandomcloud** [comment]
BRUH, that is literally BetterDiscord, not vencord.

**Comment by BudImCanadian** [comment]
Nope, its vencord installed on top of better discord.

**Comment by somerandomcloud** [comment]
Well then you shouldn't ask for support here, as we do not support BetterDiscord... Not even sure how you installed BD on top of VC....

**Comment by Vendicated** [comment]
Using multiple mods at once is not supported.

In any case, you're likely just running out of memory (Discord is capped to 2gb) so nothing that can be done
