### ISSUE TITLE
[Feature/Question] Is it possible/how to load QuickCss.css in using the Browser extension?

### ISSUE THREAD

**Issue by Spacellary** [Vendicated/Vencord#134]
### Question/Issue
Is it possible/how to load QuickCss.css using the Browser extension?
When I open Vencord settings in the browser this is all I see, where is the QuickCss.css file supposed to be placed/located for the web version? The screenshot attached is all I see as options.

### Motivation
A pretty Discord.
_Vencord is love, Vencord is life._
<br>
#### Vencord web settings page:
![msedge_1Yj0E9jZTR](https://user-images.githubusercontent.com/39604793/197218761-f55bc268-b099-4c64-a361-80c659781931.png)

**Comment by somerandomcloud** [comment]
Hey! QuickCSS doesn't work on browser right now. There are some other CSS editors that you could use like:

- Stylus || [Chrome/Chromium](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) || [Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)
- Stylish || [Chrome/Chromium](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) || [Firefox](https://addons.mozilla.org/en-US/firefox/addon/stylish/)
- Live CSS Editor || [Chrome/Chromium](https://chrome.google.com/webstore/detail/live-editor-for-css-less/ifhikkcafabcgolfjegfcgloomalapol) || [Firefox](https://addons.mozilla.org/en-US/firefox/addon/live-editor-for-css-less-sass/) || [Github](https://github.com/webextensions/live-css-editor)

**Comment by Vendicated** [comment]
I will implement it either today or tomorrow

**Comment by Spacellary** [comment]
Amazing news, good stuff.
Thanks all contributors for the continuous improvements in Vencord!
This can be closed as #Completed when that's done by then.

**Comment by Vendicated** [comment]
basically done 

https://user-images.githubusercontent.com/45497981/197290655-51003cc5-76ff-47c6-a7bf-3a455230f5b3.mp4

I still need to fine tune it and it only works on web for now. Gonna push to monaco branch so if u wanna use it already you can check out that branch (`git fetch && git checkout monaco`) then build

**Comment by Spacellary** [comment]
Nice! 👏

**Comment by Vendicated** [comment]
Scratch that, I pushed to main. Implemented in https://github.com/Vendicated/Vencord/commit/4b1e96b76ee4eea16fcb3b5cae74e173541b3c74

**Comment by Vendicated** [comment]
Please let me know if teverything works fine

**Comment by Spacellary** [comment]
> Please let me know if teverything works fine

Thanks Ven-oniichan-kun-senpai, **with `Dev Build 4b1e96b` everything works fine and looks beautiful.**

It doesn't work in inPrivate (incognito) mode in MS Edge, but that's not a frequent enough use case for me to matter, just something I noticed, even after allowing the extension in private windows, could be related to rant bellow.

_Chromium is so annoying with unpacked extensions, that warning triggers me massively, I ended up having to pack the extension and using the Group Policy editor, after downloading their administrative model, something that's meant for enterprise deployment just be able to manually whitelist my own .crs so it would just behave like a regular extension...

I could have used the Dev or Canary channel but these currently have issues for me and actually even miss a feature I became used to (surprisingly, I know) in the Main channel._

Again, ranting about Chromium aside, **it works great!**

**Comment by somerandomcloud** [comment]
> It doesn't work in inPrivate (incognito) mode in MS Edge

This happens because if I remember correctly storage between addons arent shared from incognito and... not incognito

**Comment by Vendicated** [comment]
If you mean that your css from normal doesn't transfer over to incognito, that's likely to be expected as I don't use extension storage but instead IndexedDB

**Comment by Spacellary** [comment]
Alright I think I understand now, it makes sense. Thanks for clarifying.

**Comment by Spacellary** [comment]
Ah yes, another thing, when I click the Open QuickCSS FIle button in the inPrivate tab, the window that pops up is blank, not because the adress is about:blank as that also happens outside inPrivate windows, but it has no contents or text fields, it's just empty.
#### Like this:
![msedge_AKCRUjOs96](https://user-images.githubusercontent.com/39604793/197298946-996c243d-8c4d-48cd-a9b8-32297b58b2b4.png)

**Comment by kiriya-aoi** [comment]
> Please let me know if teverything works fine

Seems like it doesn't work with the userscript, just the extension.

**Comment by Vendicated** [comment]
because the userscript doesn't have cps bypass. This is a known limitation for now. 

Use the extension or install a cps disabler and enable it for discord (https://github.com/PhilGrayson/chrome-csp-disable)
