### ISSUE TITLE
[Bug] Both native Windows and Discord title bars at the same time

### ISSUE THREAD

**Issue by ghost** [Vendicated/Vencord#1346]
### Discord Account

Valdemar_check

### What happens when the bug or crash occurs?

The only thing that happens is that both windows and discord tray are showed at the same time. Nothing harmful but weird
![image](https://github.com/Vendicated/Vencord/assets/85429908/d982a5a4-077f-453c-88a3-d15608a33d37)

### What is the expected behaviour?

Only either windows or discord title bar is seen

### How do you recreate this bug or crash?

1. Turn on "native windows title bar" feature and restart the app _using windows app tray_
2. Go to plugins tab, turn on or off any plugin and restart the app using _built in restart button on the plugins tab_

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use our support channel instead of necroing old issues.
