### ISSUE TITLE
[Feature Request] in app changelog

### ISSUE THREAD

**Issue by jarvis09-yann** [Vendicated/Vencord#1364]
### Discord Account

jarvis09

### What is it that you'd like to see?

Hello, I request adding a box in the vencord tab in the settings which would show the latest changes or something like the latest commit name.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
updater tab already exists?

**Comment by jarvis09-yann** [comment]
Yes, but it doesn't show what the update added/changed and that's the feature I'm requesting sorry if i wasn't clear

**Comment by Vendicated** [comment]
it does though

**Comment by jarvis09-yann** [comment]
![Capture d'écran 2023-05-15 192604](https://github.com/Vendicated/Vencord/assets/72513680/73986555-8c2b-40e9-9290-616524218a20)
i dont see it on my client

**Comment by jarvis09-yann** [comment]
![Capture d'écran 2023-06-30 131102](https://github.com/Vendicated/Vencord/assets/72513680/bfa92041-bf49-4d9c-a453-e3f519577459)
i dont see it on my client

**Comment by Vendicated** [comment]
whenever there's an update it shows you the changes for that update. if you use auto update you just don't get a chance to see it. Too see it at any time, go here https://github.com/Vendicated/Vencord/commits/main

**Comment by jarvis09-yann** [comment]
my request was to display in the app the name of the commit or a quick explanation of what the update added/changed

**Comment by jarvis09-yann** [comment]
nvm I finally understand what you meant, the changelog shows before you update the app, sorry for the inconvenience, can I close the issue ?
