### ISSUE TITLE
[Bug] OpenInApp prevents message buttons with links from working

### ISSUE THREAD

**Issue by infini0083** [Vendicated/Vencord#1375]
### What happens when the bug or crash occurs?

Clicking on a message button that's supposed to redirect you to a link will not work, giving the impression that the button has no function.

https://github.com/Vendicated/Vencord/assets/113451171/162e570d-ac96-40b9-bfc4-fe8b3b0ef6c3

### What is the expected behaviour?

Button should bring up the "proceed to website" confirmation pop-up after clicked.

https://github.com/Vendicated/Vencord/assets/113451171/c937b607-e486-49c2-8f26-d9f3a93de829

### How do you recreate this bug or crash?

1. Turn on the OpenInApp plugin
2. Click a message button that contains a link

### Errors

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'defaultPrevented')
    at Object.handleLink (openInApp.ts:129:19)
    at ae (WebpackModule757817:2:10009)
    at T.t (WebpackModule704229:2:1747)
    at Object.Me (7c515e89902f642bbb85.js:1736:509)
    at je (7c515e89902f642bbb85.js:1736:663)
    at 7c515e89902f642bbb85.js:1757:416
    at Ur (7c515e89902f642bbb85.js:1757:513)
    at Gr (7c515e89902f642bbb85.js:1757:927)
    at 7c515e89902f642bbb85.js:1763:415
    at cc (7c515e89902f642bbb85.js:1828:267)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by ryanccn** [comment]
Can reproduce

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/994c3b3c92ccb510facd726a3ceecdb987263f79
