### ISSUE TITLE
[Bug] ShowMeYourName displays Discord Username instead of Display Name

### ISSUE THREAD

**Issue by Xaver106** [Vendicated/Vencord#1381]
### Discord Account

xaver106

### What happens when the bug or crash occurs?

![20230705_161439](https://github.com/Vendicated/Vencord/assets/46501008/47c26f8c-d5f6-4f20-baa5-b0be4ec7ca32)
Instead of displaying only my Discords Display Name, the Plugin shows my Username/Discriminator.
It still grabs my Server Nickname, if I have one, but right now it seems, that basivcally everyone has a Nickname

### What is the expected behaviour?

If a user doesn't have a Server Nickname, don't show me his Username/Discriminator. It only adds confusion

### How do you recreate this bug or crash?

1. Open Discord
2. Open Settings
3. Navigate to Vencord/Plugins
4. Search for ShowMeYourName
5. Enable The Plugin ShowMeYourName
6. Exit Settings
7. Go on any Server and check the username of a user with a new Username

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by 0xallie** [comment]
I don't consider this a bug, it should be configurable though.

**Comment by Xaver106** [comment]
Yes, but now there are two different usernames to choose from. I don't care what someone's username is, I only want to see the difference between the server name and display name. Consider this a feature request if necessary.

**Comment by RobertsSpaceIndustries** [comment]
You can modify that

**Comment by TheKodeToad** [comment]
![image](https://github.com/Vendicated/Vencord/assets/57493648/1467e393-3c5f-43f4-8e95-d0a80ed4e5ce)
You can't

**Comment by RobertsSpaceIndustries** [comment]
> ![image](https://user-images.githubusercontent.com/57493648/260023101-1467e393-3c5f-43f4-8e95-d0a80ed4e5ce.png) You can't

Yeah that's what I meant.

**Comment by Xaver106** [comment]
> > ![image](https://user-images.githubusercontent.com/57493648/260023101-1467e393-3c5f-43f4-8e95-d0a80ed4e5ce.png) You can't
> 
> Yeah that's what I meant.

But that's not what I meant. You can't choose Display name instead of username

**Comment by TheKodeToad** [comment]
yeah i've made a thing which should work

**Comment by Vendicated** [comment]
Now an option via https://github.com/Vendicated/Vencord/commit/c79e065d09b9a1c6c0d0db94fe60204fefc0e138

**Comment by 103sbavert** [comment]
For some reason the new toggle doesn't work.

**Comment by 103sbavert** [comment]
I just tested it again and it turns out that it's the mentions that don't change, but the display name appears correctly.
