### ISSUE TITLE
RelationshipNotifier says friend request revoked if I accept it from another client

### ISSUE THREAD

**Issue by 0xallie** [Vendicated/Vencord#1388]
### Discord Account

alexiaya

### What happens when the bug or crash occurs?

"Friend request from [username] has been revoked"

### What is the expected behaviour?

It should not show anything, since it was accepted.

### How do you recreate this bug or crash?

1. Get a friend request from someone
2. Accept it on some client without the plugin (e.g. mobile)

### Errors

N/A

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
hmm, we can probably use the Relationship store to see if this user is now a friend/blocked and skip notifying if so. Perhaps you could pr this?

**Comment by Vendicated** [comment]
Fixed
