### ISSUE TITLE
[Linux] add an option to use Wayland support with Chromium WebRTC PipeWire support and Preferred Ozone platform

### ISSUE THREAD

**Issue by Enderteck** [Vendicated/Vencord#1393]
### Discord Account

Enderteck#0172

### What is it that you'd like to see?

You can use Chomium flags to make it work on wayland ! I tried enabling those two flags in chrome then using discord and it works great, I could screenshare and everithing ! Could there be an option in Vencord settings or under the Linux settings tab to enable those chromium flags to be able to screenshare wayland ? (apps and entire desktop).

I don't know if that's possible but I'm still asking. Thanks in advance ♥️

Description of the flags:

WebRTC PipeWire support: Enabled
When enabled the WebRTC will use the PipeWire multimedia server for capturing the desktop content on the Wayland display server. – Linux

Preferred Ozone platform : Auto
Selects the preferred platform backend used on Linux. The default one is "X11". "Auto" selects Wayland if possible, X11 otherwise. – Linux

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
you can achieve this by passing them as command line flags to discord, see https://wiki.archlinux.org/title/Discord#Screen_sharing_on_Wayland
