### ISSUE TITLE
[Bug] ShowAllMessageButtons not working

### ISSUE THREAD

**Issue by sodie420** [Vendicated/Vencord#1397]
### Discord Account

sodie.

### What happens when the bug or crash occurs?

the plugin doesnt work. i still have to press shift to show all the message buttons. normally it works, but suddenly it doesnt.

### What is the expected behaviour?

all the message buttons are supposed to show up, without having to press shift.

### How do you recreate this bug or crash?

it doesnt work. i've tried restarting, checking for updates, disabling and re-enabling it. nothing fixes it.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Nuckyz** [comment]
https://github.com/Vendicated/Vencord/pull/1392
