### ISSUE TITLE
[Bug] PronounDB only displays Discord pronouns in chat messages once user with said pronouns is clicked on

### ISSUE THREAD

**Issue by Jurtaa** [Vendicated/Vencord#1399]
### Discord Account

f.catus

### What happens when the bug or crash occurs?

The bug involves no pronouns displaying next to the timestamps in messages upon opening up Discord. However, when you click on a user's name, their pronouns are suddenly displaying in their messages as intended.

### What is the expected behaviour?

I expect all pronouns to already be displayed in each users' messages.

### How do you recreate this bug or crash?

1. Boot up/restart Discord.
2. Note if any pronouns are being displayed.
3. Click on and off a user's name.
4. Repeat step 2.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
not possible. Discord pronouns are only available in the profile data, and fetching profile of everyone in chat is not viable
