### ISSUE TITLE
[Bug] Theme refusing to load up after a browser restart

### ISSUE THREAD

**Issue by Mineplayerminer** [Vendicated/Vencord#1403]
### What happens when the bug or crash occurs?

I installed Vencord yesterday into my browser (Official Brave) as I wanted to have some nice themes. However, this morning, I'm getting an error "Failed to fetch," like it couldn't access the CSS file anymore. I even tried clearing my browser's cache and cookies. Sadly, it didn't work. I tried removing the extension and installing it back. This time, the themes were back, until I've restarted everything. The same issue occurred.
Could it be, as it's trying to load the stylesheet from an external link outside Discord? I'm not that deep into HTML and CSS, so I don't know the expected behavior of the Content Security Policy. I'm not using the Discord client because Discord did a very nice job of eating 1 GB of RAM when idling. I blame them for using full Chromium. The web version is much lighter and it doesn't require any HW acceleration crap. I'm not using any kinds of Betas or Canaries since they eat twice of the resources and they're not worth using them if you're not a hardcore programmer.

### What is the expected behaviour?

Normally, the theme should be cached or loaded once again with no errors, unless the file location had been changed.

### How do you recreate this bug or crash?

1. Add Vencord to your browser.
2. Open up discord.com.
3. Paste the raw CSS link to your theme in the Themes tab.
4. The theme is now loaded. restart your browser completely. (Not just closing it)
5. None of the themes will work now.

### Errors

```
VencordWeb:196 Refused to load the stylesheet 'https://raw.githubusercontent.com/ClearVision/ClearVision-v6/master/ClearVision_v6.theme.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' https://cdn.discordapp.com https://*.hcaptcha.com https://hcaptcha.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

FT @ VencordWeb:196
VencordWeb:26 Refused to connect to 'https://raw.githubusercontent.com/ClearVision/ClearVision-v6/master/ClearVision_v6.theme.css' because it violates the following Content Security Policy directive: "connect-src 'self' https://status.discordapp.com https://status.discord.com https://support.discordapp.com https://support.discord.com https://discordapp.com https://discord.com https://discord-attachments-uploads-prd.storage.googleapis.com https://cdn.discordapp.com https://media.discordapp.net https://router.discordapp.net wss://*.discord.gg https://best.discord.media https://latency.discord.media wss://*.discord.media wss://dealer.spotify.com https://api.spotify.com https://sentry.io https://api.twitch.tv https://api.stripe.com https://api.braintreegateway.com https://client-analytics.braintreegateway.com https://*.braintree-api.com https://www.googleapis.com https://*.algolianet.com https://*.hcaptcha.com https://hcaptcha.com https://*.algolia.net ws://127.0.0.1:* http://127.0.0.1:*".

(anonymous) @ VencordWeb:26
VencordWeb:26 Refused to connect to 'https://raw.githubusercontent.com/ClearVision/ClearVision-v6/master/ClearVision_v6.theme.css' because it violates the document's Content Security Policy.
(anonymous) @ VencordWeb:26
1db98f8adca037ec606b.js:5598 [FetchBlockedDomain] Fetching blocked domain list
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Brave bug. https://github.com/brave/brave-browser/issues/30854
