### ISSUE TITLE
[Bug] Userscript not working on Safari

### ISSUE THREAD

**Issue by itz-coffee** [Vendicated/Vencord#1417]
### Discord Account

itz_coffee

### What happens when the bug or crash occurs?

The userscript isn't working with either Tampermonkey or Userscripts on safari

### What is the expected behaviour?

Vencord should load on the web page

Safari: Version 17.0 (19616.1.20.11.3)
Discord: Stable 212637 (6da172b)
Mac: Sonoma 14.0

### How do you recreate this bug or crash?

1. Download Tampermonkey or Userscripts from the app store
2. Add vencord userscript
3. Open the discord web app

### Errors

Tampermonkey
```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
```
Userscripts
```
[Warning] Vencord.user.js @inject-into value set to 'content' due to @grant values: GM_xmlhttpRequest - https://github.com/quoid/userscripts/issues/265#issuecomment-1213462394 (content.js, line 384)
[Info] Injecting Vencord (js) (content.js, line 278)
[Error] Vencord.user.js error
ReferenceError: Can't find variable: unsafeWindow
(anonymous function)
(anonymous function)
(anonymous function)
(anonymous function)
(anonymous function)
(anonymous function)
(anonymous function)
anonymous
injectJS
processJS
(anonymous function)
	injectJS (content.js:291)
	processJS (content.js:229)
	(anonymous function) (content.js:419)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by ilikecereal1** [comment]
I tried it on my iPad and it doesn’t work.

**Comment by Vendicated** [comment]
safari is not supported, use chromium/firefox

**Comment by itz-coffee** [comment]
You should update the script then as it currently says its compatible 
https://github.com/Vencord/builds/tree/main/Vencord.user.js#L16

**Comment by joulev** [comment]
Bumping this, it doesn't work on Safari 17.3.1 and Tampermonkey v4.20.6188. The error is the same as above.

> [Error] Refused to execute a script because its hash or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (about:blank, line 1)
> [Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (about:blank, line 0)
> [Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (1086674479519907943, line 0)

After that there are a few logs and some are marked as from Vencord

![](https://cdn.discordapp.com/attachments/1069885585357033483/1206475914607591434/image.png?ex=65dc2541&is=65c9b041&hm=a1fd54c99bb25e64936f8be5bc96b7d2977a9e6176beea697f79691fd04e6924&)

but Vencord itself is not loaded successfully (in the settings it doesn't show up).

**Comment by Vendicated** [comment]
![screenshot of my previous response](https://github.com/Vendicated/Vencord/assets/45497981/ec436c9c-34b4-4f15-91e3-ff03b7644836)
