### ISSUE TITLE
[Bug] fakenitro does not work with emoji server premium

### ISSUE THREAD

**Issue by pro11x11** [Vendicated/Vencord#1424]
### What happens when the bug or crash occurs?

fakenitro does not work with emoji
server premium
![image](https://github.com/Vendicated/Vencord/assets/110092289/8f6ab0b5-de7f-49f4-a7df-522485965535)

### What is the expected behaviour?

i expect fakenitro  work with emoji
server premium

### How do you recreate this bug or crash?

join a server with premium emoji
go to emoji 
![image](https://github.com/Vendicated/Vencord/assets/110092289/b02a3233-9230-45ea-bd0c-e90d8f4a1bb4)
go where the premium emoji is
click on it
see this :
![image](https://github.com/Vendicated/Vencord/assets/110092289/5a4d43f5-bc61-4778-a32c-7465d96aa280)

### Errors

Nothing

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
added!
