### ISSUE TITLE
Render error in plugins 

### ISSUE THREAD

**Issue by alije123** [Vendicated/Vencord#143]
![image](https://user-images.githubusercontent.com/33022255/197365849-1ca04066-06b0-4705-b454-1be5fb934682.png)

> TypeError: Cannot read property 'localeCompare' of undefined
>     at VencordRenderer:31
>     at Array.sort (<anonymous>)
>     at VencordRenderer:31
>     at Object.useMemo (WebpackModule364448:2)
>     at Object.t.useMemo (62be08f0b264e26179c8.js:1642)
>     at VencordRenderer:31
>     at ua (WebpackModule364448:2)
>     at $s (WebpackModule364448:2)
>     at ku (WebpackModule364448:2)
>     at Uu (WebpackModule364448:2)
> r.<computed> @ 62be08f0b264e26179c8.js:6061
> overrideMethod @ react_devtools_backend.js:4026
> ps @ WebpackModule364448:2
> Is.n.payload @ WebpackModule364448:2
> Ei @ WebpackModule364448:2
> za @ WebpackModule364448:2
> $s @ WebpackModule364448:2
> ku @ WebpackModule364448:2
> Uu @ WebpackModule364448:2
> wu @ WebpackModule364448:2
> yu @ WebpackModule364448:2
> eval @ WebpackModule364448:2
> t.unstable_runWithPriority @ 62be08f0b264e26179c8.js:1663
> Ko @ WebpackModule364448:2
> Xo @ WebpackModule364448:2
> qo @ WebpackModule364448:2
> we @ WebpackModule364448:2
> en @ WebpackModule364448:2
> 62be08f0b264e26179c8.js:6061  
> 
> (Vencord)   (React ErrorBoundary)  A component threw an Error
>  TypeError: Cannot read property 'localeCompare' of undefined
>     at VencordRenderer:31
>     at Array.sort (<anonymous>)
>     at VencordRenderer:31
>     at Object.useMemo (WebpackModule364448:2)
>     at Object.t.useMemo (62be08f0b264e26179c8.js:1642)
>     at VencordRenderer:31
>     at ua (WebpackModule364448:2)
>     at $s (WebpackModule364448:2)
>     at ku (WebpackModule364448:2)
>     at Uu (WebpackModule364448:2)
> r.<computed> @ 62be08f0b264e26179c8.js:6061
> overrideMethod @ react_devtools_backend.js:4026
> _log @ VencordRenderer:13
> error @ VencordRenderer:13
> componentDidCatch @ VencordRenderer:30
> Is.i.componentDidCatch.n.callback @ WebpackModule364448:2
> pi @ WebpackModule364448:2
> Ss @ WebpackModule364448:2
> Vu @ WebpackModule364448:2
> t.unstable_runWithPriority @ 62be08f0b264e26179c8.js:1663
> Ko @ WebpackModule364448:2
> Bu @ WebpackModule364448:2
> yu @ WebpackModule364448:2
> eval @ WebpackModule364448:2
> t.unstable_runWithPriority @ 62be08f0b264e26179c8.js:1663
> Ko @ WebpackModule364448:2
> Xo @ WebpackModule364448:2
> qo @ WebpackModule364448:2
> we @ WebpackModule364448:2
> en @ WebpackModule364448:2
> 62be08f0b264e26179c8.js:6061  
> 
> (Vencord)  (React ErrorBoundary)  Component Stack 
>     at VencordRenderer:31:7577
>     at G (VencordRenderer:29:870)
>     at n (https://canary.discord.com/assets/a7e2408b9a621e2a5b81.js:44:352)
>     at se (https://canary.discord.com/assets/1d1bd9d3409747b6697d.js:34:142)
>     at D (https://canary.discord.com/assets/62be08f0b264e26179c8.js:6514:257)
>     at div
>     at https://canary.discord.com/assets/630a85435a376190ea33.js:42:365
>     at D (https://canary.discord.com/assets/62be08f0b264e26179c8.js:6514:257)
>     at div
>     at https://canary.discord.com/assets/62be08f0b264e26179c8.js:5457:565
>     at div
>     at div
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:6317:761)
>     at div
>     at https://canary.discord.com/assets/62be08f0b264e26179c8.js:251:313
>     at k (https://canary.discord.com/assets/1d1bd9d3409747b6697d.js:44:9)
>     at n (https://canary.discord.com/assets/1d1bd9d3409747b6697d.js:34:823)
>     at n (https://canary.discord.com/assets/a7e2408b9a621e2a5b81.js:44:352)
>     at d (https://canary.discord.com/assets/f5718af71592f5d3ea12.js:12:335)
>     at https://canary.discord.com/assets/f5718af71592f5d3ea12.js:12:840
>     at https://canary.discord.com/assets/1a09b916fdc87bde55b3.js:1:378
>     at d (https://canary.discord.com/assets/f5718af71592f5d3ea12.js:12:335)
>     at https://canary.discord.com/assets/f5718af71592f5d3ea12.js:12:840
>     at https://canary.discord.com/assets/1a09b916fdc87bde55b3.js:2:748
>     at Suspense
>     at Suspense(UserSettings)
>     at div
>     at l (https://canary.discord.com/assets/62be08f0b264e26179c8.js:353:15)
>     at _ (https://canary.discord.com/assets/62be08f0b264e26179c8.js:5239:107)
>     at n (https://canary.discord.com/assets/cd2fe2c73871e7172987.js:1277:755)
>     at div
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:6317:761)
>     at n (https://canary.discord.com/assets/cd2fe2c73871e7172987.js:1280:235)
>     at iie (https://canary.discord.com/assets/cd2fe2c73871e7172987.js:1281:640)
>     at div
>     at n (https://canary.discord.com/assets/cd2fe2c73871e7172987.js:1283:923)
>     at gie (https://canary.discord.com/assets/cd2fe2c73871e7172987.js:1285:481)
>     at t (https://canary.discord.com/assets/62be08f0b264e26179c8.js:1617:221)
>     at t (https://canary.discord.com/assets/62be08f0b264e26179c8.js:1618:172)
>     at o (https://canary.discord.com/assets/cd2fe2c73871e7172987.js:1327:905)
>     at Suspense
>     at f
>     at t (https://canary.discord.com/assets/62be08f0b264e26179c8.js:1617:221)
>     at t (https://canary.discord.com/assets/62be08f0b264e26179c8.js:1618:172)
>     at div
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:5348:243)
>     at VerificationLayerProvider
>     at re (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2082:339)
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:5348:243)
>     at AppLayerProvider
>     at div
>     at div
>     at _ (https://canary.discord.com/assets/62be08f0b264e26179c8.js:3508:472)
>     at D (https://canary.discord.com/assets/62be08f0b264e26179c8.js:6514:257)
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2111:243)
>     at T (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2114:355)
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2115:79)
>     at a (https://canary.discord.com/assets/62be08f0b264e26179c8.js:5940:967)
>     at _ (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2074:559)
>     at Ct (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2097:268)
>     at n (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2241:245)
>     at a (https://canary.discord.com/assets/62be08f0b264e26179c8.js:5939:960)
>     at https://canary.discord.com/assets/62be08f0b264e26179c8.js:2182:524
>     at mn (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2184:809)
>     at t (https://canary.discord.com/assets/62be08f0b264e26179c8.js:1614:520)
>     at t (https://canary.discord.com/assets/62be08f0b264e26179c8.js:1571:817)
>     at mi (https://canary.discord.com/assets/62be08f0b264e26179c8.js:2291:109)

**Comment by Vendicated** [comment]
This means you have a plugin with no name property. Make sure you don't have any files in your Vencord folder that shouldn't be there or do a fresh install

**Comment by Vendicated** [comment]
all good don't worry! and if you want any help with making your plugin work just ask on the server
