### ISSUE TITLE
[Feature Request] exclude servers from message log

### ISSUE THREAD

**Issue by sssnipercat1** [Vendicated/Vencord#1433]
### Discord Account

Sssnipercat1

### What is it that you'd like to see?

It has come up in one of the servers I am in that they strictly prohibit message logging using modded clients, and so it would be really nice to be able to exclude certain servers from the logger.

### Request Agreement

- [X] This is not a plugin request

**Comment by l-zeuch** [comment]
This was already done in #1420 and will likely come with the next release.
