### ISSUE TITLE
[Bug] <title>Custom RPC using the Custom RPC plugin not showing up for others

### ISSUE THREAD

**Issue by TinySlugcat** [Vendicated/Vencord#1444]
### Discord Account

scuglat

### What happens when the bug or crash occurs?

On my Windows 10 PC, whenever I use the Custom RPC plugin in Vencord, it will show up just fine on my end but no one else is able to see it, even if they themselves have Vencord installed. It works just fine on my other devices, and I do not have any idea why it is occurring. I've tried to reinstall Vencord and disable all my other plugins, but to no avail.

### What is the expected behaviour?

I expect the a Custom RPC using the Custom RPC plugin to show up for everyone.

### How do you recreate this bug or crash?

1. Enable the Custom RPC Vencord plugin
2. Make an application in the Discord Developer Portal
3. Use the application ID in the menu of the plugin
4. Set the buttons to the desired link and title
5. Set the images to the ones uploaded in the Discord Developer Portal
6. Exit the plugin menu
7. Get a friend or a different device to check your profile

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
that means you have an invalid configuration. Make sure all your images have tooltips and your timestamps are valid and in the proper order. If you need further help, use our support channel
