### ISSUE TITLE
Desktop mode for Vencord Android 

### ISSUE THREAD

**Issue by dumcatt** [Vendicated/Vencord#1456]
### Discord Account

stpdg

### What is it that you'd like to see?

Being able to use the desktop version of Discord in the Vencord application. A slider for the zoom level would be awesome too (ctrl + , -)

Requesting this because both discord mobile sucks and the web mobile version also sucks on an android tablet.

Something like this:
![Screenshot_20230719_174243_Samsung Internet](https://github.com/Vendicated/Vencord/assets/93240060/a65029d1-26f4-42be-a0d9-be3387c373a8)

![Screenshot_20230719_174249_Samsung Internet](https://github.com/Vendicated/Vencord/assets/93240060/27503eb5-fd71-4964-b4f9-bc81da1d2f90)

### Request Agreement

- [x] This is not a plugin request

**Comment by ActuallyTheSun** [comment]
wrong repo, https://github.com/Vencord/Android

**Comment by dumcatt** [comment]
oops sorry

**Comment by dumcatt** [comment]
I can't figure out how to submit a request in the Vencord Android repo so I'm going to reopen this thread.

**Comment by luximus-hunter** [comment]
> I can't figure out how to submit a request in the Vencord Android repo

You can't
