### ISSUE TITLE
[Issue] Spotify embed's are gone.

### ISSUE THREAD

**Issue by DarkArtz0** [Vendicated/Vencord#1457]
### Discord Account

floppaonsnow

### What happens when the bug or crash occurs?

The Spotify embed's seem to disappear as soon as you install vencord, dont know if this is on my side or vencord's.

### What is the expected behaviour?

Spotify embeds appear like normal.

### How do you recreate this bug or crash?

Install vencord.

### Errors

```
Content Security Policy of your site blocks some resources.

```
This was the only one I could find.
![image](https://github.com/Vendicated/Vencord/assets/95894740/6f923661-be00-418f-bcd9-a625ccafd92e)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Not related to Vencord. Try reinstalling Discord

**Comment by enygmate** [comment]
I also get the error only when Vencord is installed, works well until I install it.
![image](https://github.com/Vendicated/Vencord/assets/65200640/9dd164fc-ec85-47ae-8312-c8ed9a1821f0)
