### ISSUE TITLE
[Feature Request] <Load Themes Natively>

### ISSUE THREAD

**Issue by GlitchyDoodles** [Vendicated/Vencord#1464]
### Discord Account

glitchydoodles

### What is it that you'd like to see?

I think it would be cool if we could load themes from both Github and from our PCs. That would be a nice feature.

### Request Agreement

- [X] This is not a plugin request

**Comment by xdCoolesding** [comment]
so you mean "load themes locally"

**Comment by GlitchyDoodles** [comment]
> so you mean "load themes locally"

Yeah, Whenever I install new themes and restart vencord. The github link for my theme stops working.
