### ISSUE TITLE
[Bug] MessageLinkEmbeds issues

### ISSUE THREAD

**Issue by VillainsRule** [Vendicated/Vencord#1467]
### Discord Account

@villainsrule_

### What happens when the bug or crash occurs?

This is a two part bug.
### Part I:
<img width="299" alt="Screen Shot 2023-07-22 at 10 20 35 PM" src="https://github.com/Vendicated/Vencord/assets/101288516/5b462d8a-7eca-4ea2-9e31-fbd7565d2def"><br>
<img width="399" alt="Screen Shot 2023-07-22 at 10 21 23 PM" src="https://github.com/Vendicated/Vencord/assets/101288516/7a439796-8ff8-4de0-b19b-ed3ff997727d">
Mentions, when embedded, always show @deleted-role.
### Part II:
<img width="313" alt="Screen Shot 2023-07-22 at 10 22 44 PM" src="https://github.com/Vendicated/Vencord/assets/101288516/287ae038-ec07-446b-a21f-b82b46ac4210">
<br>
<img width="394" alt="Screen Shot 2023-07-22 at 10 22 37 PM" src="https://github.com/Vendicated/Vencord/assets/101288516/fa01b259-f27a-420e-8699-5bf31c436565">
Headers (using newer markdown changes), don't show up.

### What is the expected behaviour?

I "expect" Vencord to show the proper role mention. I understand not having the big text for sizing issues, but it'd be a good setting for the plugin.

### How do you recreate this bug or crash?

1. Put a message with a role mention or large text
2. Enable MessageLinkEmbeds
3. Link the message in another channel

### Errors

none

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by AutumnVN** [comment]
it only happens with automod embed, the normal embed works fine

**Comment by Vendicated** [comment]
automod embed limitation like autumn said
