### ISSUE TITLE
[Bug] Won't install

### ISSUE THREAD

**Issue by AzvidPlayz** [Vendicated/Vencord#1506]
### Discord Account

Azvidplayz

### What happens when the bug or crash occurs?

I click the install button on the installer and it says I have a broken install, and I tried uninstalling and reinstalling Discord, but the same thing happened

### What is the expected behaviour?

I expected Vencord to install but instead, it showed an error (see image)
<img width="437" alt="image" src="https://github.com/Vendicated/Vencord/assets/82178480/193d7abf-e820-4173-98f7-98cee268d71c">

### How do you recreate this bug or crash?

I'm not sure how to recreate it, it just happened after I opened the installer

### Errors

```
Replace this text with your crash-log.
```
I can't open the dev console on the Installer

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
read the prompt and do what it says.
