### ISSUE TITLE
[Feature Request] Separate Date and Time Formats from Language

### ISSUE THREAD

**Issue by Rainydaysout** [Vendicated/Vencord#1509]
### Discord Account

rainydaysout

### What is it that you'd like to see?

The feature itself would allow you to change the clock without changing your Language Settings simply allowing you to enjoy your preferred clock format without having to change the language.
This feature would also allow you to change the Date format as well.
So you could have you your own format that's easiest for you to read without having to find the right language.

The settings would pretty much be like this.

**Date & Time**

**Date Format** (Dropbox for selecting)
DD/MM/YY
DD/YY/MM
MM/DD/YY
MM/YY/DD
YY/MM/DD
YY/DD/MM

**Additional Date Settings**
~**Month** (Dropbox for selecting)
 Show as numbers [01]
 Show as words (Short) [Jan]
 Show as words (Long) [January]
 
~**Year** (Dropbox for selecting)
Show as YY [23]
Show as YYYY [2023]

**Time Settings**
~**Time Formats** (Dropbox for selecting)
Use 12 hour format [1200AM 12:00PM]
Use 24 hour format [00:00 23:00]

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
is this just about having 24h time and english? if so, Discord Settings > Language > English, UK

in any case, this isn't the right place to put plugin requests, use discussions

**Comment by Rainydaysout** [comment]
> is this just about having 24h time and english? if so, Discord Settings > Language > English, UK
> 
> in any case, this isn't the right place to put plugin requests, please use discussions

Ah okie, thanks I'll go to discussions then.
It's not just about the English with that, it's also so you can have any date & time formats without having to find the region that has your preferred format.
The idea was to just make those separate to where anybody from any region could have whatever format they wanted.
