### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by acheddadi** [Vendicated/Vencord#1510]
### What happens when the bug or crash occurs?

The bug always happens when I try to record myself speaking while using the new voice message feature. The error message "Failed to finish recording" appears.

### What is the expected behaviour?

I expect the recording to feature to work.

### How do you recreate this bug or crash?

1. Click the + sign near the chat prompt
2. Click send voice message
3. A voice recording prompt appears
4. Click start recording and begin speaking
5. Click stop recording
6. Observe that the message "Failed to finish recording appears

### Errors

"Failed to finish recording"

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
please use our support channel
