### ISSUE TITLE
[Bug] MuteNewGuild doesn't work for some servers.

### ISSUE THREAD

**Issue by fr-gg** [Vendicated/Vencord#1537]
### Discord Account

Fr_g

### What happens when the bug or crash occurs?

Server that have previewmode, don't get muted once you actually join the server.

### What is the expected behaviour?

Those servers should also be muted.

### How do you recreate this bug or crash?

1. Join a server with previewmode enabled.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
should be fiuxed
