### ISSUE TITLE
I get this after injecting and restarting, I tried both on canary discord and just normal updated discord

### ISSUE THREAD

**Issue by dw13gamung** [Vendicated/Vencord#154]
[](
![DiscordCanary_BiWRBP1d02](https://user-images.githubusercontent.com/55485635/197558658-1fab7fc3-0e85-4273-bd3b-641d26f49944.png)

**Comment by Vendicated** [comment]
Use the support channel

**Comment by exhq** [comment]
you should try injecting inside of me ;)

**Comment by dw13gamung** [comment]
@Vendicated where is that channel located, I don't see it?
