### ISSUE TITLE
Crash on Wayland

### ISSUE THREAD

**Issue by xtrm-en** [Vendicated/Vencord#163]
Hey, got a crash after injecting the latest version, which didn't happen around a week ago:

```bash
xtrm:~/ $ discord-canary
[Vencord] Starting up...
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

# just hangs here
```

This doesn't happen without Vencord but I can't figure out what uses `libva` in the project.

## System Information
![image](https://user-images.githubusercontent.com/26600206/198056889-b0e781e9-47f3-477e-a0af-c8b68a2a6245.png)

**Comment by somerandomcloud** [comment]
Did you try uninstalling and reinstalling? What were the steps you took to update?

**Comment by xtrm-en** [comment]
Tried `git pull`, removing and re-cloning the repo, removing `discord-canary` and all configuration files, and tried using stable instead of canary.

**Comment by Vendicated** [comment]
Not caused by Vencord.

Try running Discord with
```sh
discord --enable-features=UseOzonePlatform --ozone-platform=wayland
```
(from https://bugs.gentoo.org/819045)

**Comment by somerandomcloud** [comment]
So both stable and canary dont work with vencord injected, but work without vencord injected?

**Comment by xtrm-en** [comment]
They do work without Vencord, but the fix Ven sent worked, thanks!

**Comment by faejr** [comment]
I still experience this issue on the latest version of Vencord, it just happened out of nowhere. The fix that Ven suggested also doesn't work for me 
```
❯ discord --enable-features=UseOzonePlatform --ozone-platform=wayland
[Vencord] Starting up...
interface 'wl_output' has no event 4
tcmalloc: large alloc 1073741824 bytes == 0x26d7569df000 @  0x5617a8679ff5 0x7f96382a92aa
[1]    25944 trace trap (core dumped)  discord --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by faejr** [comment]
I decided to come back to this, somehow I managed to fix it by simply running `pnpm build` prior to launching discord

**Comment by ArjixWasTaken** [comment]
So your issue was simply unrelated.
