### ISSUE TITLE
[Feature Request] Add a way to block/hide emoji?

### ISSUE THREAD

**Issue by zapxcero** [Vendicated/Vencord#1631]
### What is it that you'd like to see?

I don't know if this counts as plugin request or not. I can't find the discussions tab (my bad).

I think a way to block/hide emoji is a great feature. Some emoji are downright vulgar, ugly, and ruins the chat. I don't want to block the users who use them. I'd rather see the text :emoji_name: than the emoji itself.  
  
Thanks!

  

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
can be done with css
