### ISSUE TITLE
[Feature Request] <title>

### ISSUE THREAD

**Issue by THEwabbit212** [Vendicated/Vencord#1635]
### Discord Account

gamerwabbit212

### What is it that you'd like to see?

A wallpaper changer.
You see how popular wallpaper engine is?
Imagine the dopeness, sry, **cuteness**,  it would add to Vencord
I found this one for powercord: https://github.com/powercord-community/wallpaper-changer
It uses sources like wallhaven...

Is very nice

This is most likely totally a plugin request

_Thank you, yours truly_

_-THEwabbit_

### Request Agreement

- [X] This is not a plugin request

**Comment by ActuallyTheSun** [comment]
![Screenshot_20230811-210408_GitHub.png](https://github.com/Vendicated/Vencord/assets/78964224/1d655b59-5129-4d4c-957e-8690c8be9757)

**Comment by TheKodeToad** [comment]
Looks like they didn't realise
