### ISSUE TITLE
[Bug] Unable to update

### ISSUE THREAD

**Issue by Polat17563** [Vendicated/Vencord#1645]
### Discord Account

gumballsupporter

### What happens when the bug or crash occurs?

It happens when i start discord and go to settings --> vencord --> updater. it says unable to update and when clicking on check for updates, it does not wok and prints out an console log, which i dont understand.

### What is the expected behaviour?

I expect vencord to check for updates and show available updates.

### How do you recreate this bug or crash?

1. open user settings
2. click updater in the vencord section

### Errors

df22f2b7f3ea2bf6acf1.js:10230  Vencord   Updater  Failed to update Object[[Prototype]]: Object

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by whqwert** [comment]
Repair using the installer
