### ISSUE TITLE
[Bug] local settings persist across account changes

### ISSUE THREAD

**Issue by SomeAspy** [Vendicated/Vencord#1647]
### Discord Account

SomeAspy

### What happens when the bug or crash occurs?

[small discussion about it in the #support channel](https://discord.com/channels/1015060230222131221/1026515880080842772/1140044239053533236)

Settings will be persisted across account changes, which has the possibility to cause issues on plugins that might rely on account specific data (such as pinDms pinning specific DMs)

### What is the expected behaviour?

Settings should be unique to each account

### How do you recreate this bug or crash?

Use the account switcher and settings should persist

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by EntityReborn** [comment]
Additional information to avoid a click:
I use both Discord release and Discord canary concurrently on the same computer, using different accounts. Some plugins, such as the above mentioned PinnedDms, are much more account specific than install specific, especially in this use case.

**Comment by EntityReborn** [comment]
Potential suggestions:
- expand plugins to decide if they want machine-based vs account-based settings. (more flexible for plugins, but likely plugins would have to update their methodology)
- expect all plugins to have account-based settings (less flexibility, but less complexity, and not an issue plugins concern themselves with)

**Comment by lewisakura** [comment]
alternative: every account gets its own settings file based on user ID, which provides full separation as part of the mod itself. but this requires the user to be logged in, and if they aren't settings can't be loaded. for example, see this from the cloud settings:
https://github.com/Vendicated/Vencord/blob/3e732646e5ab83f76b34ec7fdb3d9d8c68faca8d/src/utils/cloud.tsx#L32-L36
we have to throw here if the user id isnt available otherwise... we don't know who's logged in and what to sync.

**Comment by Vendicated** [comment]
having entirely separate settings per account would be an anti feature imo, and also not really work well with the way vencord works. the most sensible solution would be to have plugins that do have account specific settings handle it correctly. relationship notifier for example correctly stores settings by User id

**Comment by Vendicated** [comment]
i think this should be fixed now? if there are still any plugins with this issue, please let usknow
