### ISSUE TITLE
[Feature Request] A button to quickly disable Vencord

### ISSUE THREAD

**Issue by RyveEthan** [Vendicated/Vencord#1650]
### Discord Account

**-**

### What is it that you'd like to see?

In the settings there would be a button to quickly disable or enable Vencord (**plugins + theme**), for example if we want to take a screenshot without showing that we use Vencord. If we can configure a **shortcut** to disable or enable Vencord it would be even better !

Thanks

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
not possible
