### ISSUE TITLE
[Bug] <I can't turn off the DTM-16 Plugin because I think I might've also equipped the DTM-18 Plugin>

### ISSUE THREAD

**Issue by Angiebro11** [Vendicated/Vencord#1651]
### Discord Account

dumb#0712

### What happens when the bug or crash occurs?

When I try and go to my settings to go turn off the Plugin in the vencord section, it wont let me choose any settings to go to and it keeps me stuck on the main screen of the settings 
[Screen recording 2023-08-14 1.25.58 AM.webm](https://github.com/Vendicated/Vencord/assets/142203187/f9e79108-d40b-45e7-b523-840da8084ee7)

### What is the expected behaviour?

It's supposed to let me go into my settings and scroll down and change my settings but it just makes it so I can't do anything therefore not being able to take it off

### How do you recreate this bug or crash?

1. Have both plugins enabled and click on the settings tab
2. Try and Click on any of the settings options and it should not let you switch

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [ ] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use our support channel
