### ISSUE TITLE
[Plugin Request] ChannelTabs plugin 

### ISSUE THREAD

**Issue by Methosss** [Vendicated/Vencord#1652]
### What is it that you'd like to see?

I couldn't find discussion tab on github
There is: Code, Issues, Pull requests, Actions, Projects, Security, Insights.

The plugin:
I would like to see plugin ChannelTabs On The top of app where i can Quick navigate to certain Channel on any server i'm in and if this Channel is a user dm i would See his avatar and status and if this Channel is a chat from one of servers i would like to See server logo and number of unread messages or notification if i was mentioned

### Request Agreement

- [X] This is not a plugin request

**Comment by Vap0r1ze** [comment]
1. A pull request for this exists already #499
2. did you not read the text in the checkbox you clicked before submitting??
