### ISSUE TITLE
[Feature Request] Delete a review off of your profile from ReviewDB

### ISSUE THREAD

**Issue by Zmonify** [Vendicated/Vencord#1653]
### Discord Account

firedevilx

### What is it that you'd like to see?

It would be nice if we could delete ReviewDB reviews that we don't want on our profiles

### Request Agreement

- [X] This is not a plugin request

**Comment by Vap0r1ze** [comment]
You can report reviews that are malicious / abusive / have slurs or something. If you mean being able to delete any review you don't, that kinda goes against what "reviews" are for

**Comment by Zmonify** [comment]
> You can report reviews that are malicious / abusive / have slurs or something. If you mean being able to delete any review you don't, that kinda goes against what "reviews" are for

There's a person pretending to be a YouTuber asking for nitro

**Comment by Zmonify** [comment]
> You can report reviews that are malicious / abusive / have slurs or something. If you mean being able to delete any review you don't, that kinda goes against what "reviews" are for

How do I opt-out then

**Comment by Zmonify** [comment]
Nevermind I figured it out

**Comment by Vap0r1ze** [comment]
> There's a person pretending to be a YouTuber asking for nitro
![image](https://github.com/Vendicated/Vencord/assets/20448879/3a728725-9333-4021-90dc-4ad86d016e63)
