### ISSUE TITLE
Image Utilities

### ISSUE THREAD

**Issue by Fox-CZSK** [Vendicated/Vencord#1655]
### Discord Account

fox_cz01

### What is it that you'd like to see?

can you please add this https://betterdiscord.app/plugin/ImageUtilities
![image](https://github.com/Vendicated/Vencord/assets/116446597/9f6b6770-e63b-47c8-baa2-4e5a324eb04f)
![image](https://github.com/Vendicated/Vencord/assets/116446597/0e2cfecf-7bcd-48f0-88bc-3906e15db344)
![image](https://github.com/Vendicated/Vencord/assets/116446597/7773e2dc-9e27-4933-b0d1-7c004ae5ece8)

**Comment by DaBluLite** [comment]
Pretty sure this is a plugin request

**Comment by Fox-CZSK** [comment]
> Pretty sure this is a plugin request

ye

**Comment by DaBluLite** [comment]
![image](https://github.com/Vendicated/Vencord/assets/73998678/468b6b77-832c-45f8-916f-a94a9e966564)
there is a checkmark when you make an issue that clearly states not to request plugins in issues

**Comment by Fox-CZSK** [comment]
> ![image](https://user-images.githubusercontent.com/73998678/260702130-468b6b77-832c-45f8-916f-a94a9e966564.png) there is a checkmark when you make an issue that clearly states not to request plugins in issues

I know, but it wouldn't be possible to send it otherwise

**Comment by DaBluLite** [comment]
Deleting the checkmark doesn't make this any better, the issue guidelines were clear, and they are there for a reason. Plugin requests aren't issues.

**Comment by Fox-CZSK** [comment]
> Deleting the checkmark doesn't make this any better, the issue guidelines were clear, and they are there for a reason. Plugin requests aren't issues.

im sorry dude is my first mesege on this platfome
