### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RoddyPlaysYT** [Vendicated/Vencord#1656]
### Discord Account

RoddyPlaysYTube#3826

### What happens when the bug or crash occurs?

Please fix it verify server of two (when i try and done verify before popups again)

### What is the expected behaviour?

fix it verify server (its popup again)

### How do you recreate this bug or crash?

i Do used vencord
and i see server 
and i verifed complete and it again popup
FIX BUG!

### Errors

```
fix verify bug that popups im human and goes again popup verify 
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by nyakowint** [comment]
Can you like elaborate?
