### ISSUE TITLE
[Feature Request] New Settings saved, don't rely on cache!

### ISSUE THREAD

**Issue by tqgx** [Vendicated/Vencord#1750]
# Discord Account
tqgx

# What is it that you'd like to see?
All current Vencord implementations, whether Firefox Extensions or greayFork scripts, rely on local caching.Very inconvenient and privacy unfriendly for some users (ArkenFox script users, users who don't keep any history)

Nothing else, expect this feature to be implemented.You don't need to see the listings in your Settings through Discord, and there's a downside to choosing these features in Discord.If the official API is modified.Or unplug something. There are ways to deal with that

# Request Agreement
 This is not a plugin request

**Comment by Vendicated** [comment]
? I don't understand what any of this is supposed to mean

**Comment by Vendicated** [comment]
if you don't want cookies/localStorage to be persisted, use incognito mode or configure your browser to clear them on exit

**Comment by tqgx** [comment]
> if you don't want cookies/localStorage to be persisted, use incognito mode or configure your browser to clear them on exit
What I mean is.When you use a browser that does not save history, all Settings imported by Vencord disappear

**Comment by Vendicated** [comment]
yes? do you expect us to persist settings magically when you disable persistent storage

**Comment by tqgx** [comment]
> yes? do you expect us to persist settings magically when you disable persistent storage

yes.
