### ISSUE TITLE
Vencord Installer Virus

### ISSUE THREAD

**Issue by WhereTheCash** [Vendicated/Vencord#1752]
### Content

whats with the VirusTotal scan virus popup? 
https://www.virustotal.com/gui/file/d0674d9d07c2c47cc8eff05dc601766775b1a73febb800216fa9415811cc47f0

**Comment by Vendicated** [comment]
false positive. it's literally open source go read the code

**Comment by WhereTheCash** [comment]
> false positive. it's literally open source go read the code

I am reading it right now, and will update when fully audited

**Comment by VMGuy23** [comment]
how'd that audit go

**Comment by WhereTheCash** [comment]
everything seems to be according you should fix and communicate with VirusTotal to fix such false flags

**Comment by lumap** [comment]
virustotal is known to  be bad, these bfs even flag the firefox installer as a virus. a simple solution would be to not trust virus total (the right choice) and to not worry. if you really think something has a virus, use a VM.

**Comment by mantikafasi** [comment]
> virustotal is known to be bad, these bfs even flag the firefox installer as a virus. a simple solution would be to not trust virus total (the right choice) and to not worry. if you really think something has a virus, use a VM.

virustotal is not bad and its totally fine, it scans the file you uploaded using different antivirusses and out of 72 antivirusses only one random antivirus flagged vencord, which is totally normal

**Comment by lewisakura** [comment]
> everything seems to be according you should fix and communicate with VirusTotal to fix such false flags

We are not going to reach out to multiple antivirus vendors to resolve a false flag that realistically very few random antiviruses actually flag it for (wtf is Bkav Pro??). It's not something we can just 'fix' and it's not a VirusTotal thing - blame the random antiviruses that flag loads of things for no reason.
