### ISSUE TITLE
[Bug] Themes tab doesn't render

### ISSUE THREAD

**Issue by lon3lybutnotalone** [Vendicated/Vencord#1754]
### Discord Account

lon3ly_but_not_alone

### What happens when the bug or crash occurs?

Whenever i try to open the Themes tab in the settings, i get an error message saying the tab couldn't be loaded. I had tried uploading a theme from BetterDiscord, and when i did i got the error message.

### What is the expected behaviour?

The tab should just be loaded, there shouldnt be an error saying it couldnt render the tab.

### How do you recreate this bug or crash?

1. Open settings
2. Select "Themes" tab
3. See Error message

### Errors

yeah i couldnt open the dev console, im on chromebook and its so weird here, but i have a screenshot if it helps
![Screenshot 2023-09-25 11 41 03 PM](https://github.com/Vendicated/Vencord/assets/146051727/7a5dcca9-1319-462b-ab66-5a5f9b8ad053)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
