### ISSUE TITLE
[Feature Request] ShowAllChannels new plugin

### ISSUE THREAD

**Issue by Seef0x** [Vendicated/Vencord#1755]
### Content

Automatically show all channels in newly joined guilds

[Example](https://media.discordapp.net/attachments/676141965078822972/1156188424345239562/S3IqcuH.png)

**Comment by ImLvna** [comment]
> ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
