### ISSUE TITLE
[Feature Request] Additional options for Message Logger plugin

### ISSUE THREAD

**Issue by SoonBanned** [Vendicated/Vencord#1760]
### Content

I admit that I copied the title from another Issue ( #989 ) but I have some ideas in mind like:
-Keeping logs between restarts of discord and if it's possible a little menu to keep track of how many logs you have per server with the option to delete logs from one server or all in order to avoid having too much unnecessary data.

-Choosing the servers you want to activate the logger on but more simply like "right click on a guild and you have a option in the list to activate or deactivate"

I don't know if i'm doing this Issue right but I hope so.

**Comment by Vendicated** [comment]
ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
