### ISSUE TITLE
[Bug] Rich Presence bugging when switching channels / server

### ISSUE THREAD

**Issue by zeroquinc** [Vendicated/Vencord#1764]
### Discord Account

desiler

### What happens when the bug or crash occurs?

The bug happens when you switch channels or servers. Notice the gif below. It also happens on every profile, not just mine.

![Discord_Dpgl3OvAnw](https://github.com/Vendicated/Vencord/assets/39315068/b56d29ba-7b04-4a51-bb99-aa209e3f4541)

### What is the expected behaviour?

I expect it to not bug out, without Vencord it works fine. Note: this also happens without any plugins enabled or themes.

### How do you recreate this bug or crash?

1. Open a server and watch your Rich Presence
2. Switch to another server / channel
3. Notice it prints the Listening to Spotify (or whatever rich presence) twice.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
