### ISSUE TITLE
[Feature Request] Use DeepL in translate plugin

### ISSUE THREAD

**Issue by Sanceilaks** [Vendicated/Vencord#1786]
### Discord Account 
voidptr_t 
### What is it that you'd like to see? 
It would be convenient to be able to translate messages via DeepL.

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by FirstWiseman** [comment]
I have added an Engine Selector my self, tried to implement DeepL and Bypass the apiKey thing and it worked for a sec but now i cant translate at all not even in the browser anymore xD.

That would be the only problem with DeepL, you have to use an Api Key and to receive the free api key you have to give your payment informations :/

![image](https://github.com/Vendicated/Vencord/assets/54641477/5450ad02-eb16-41a0-a6da-63af6ce553c3)

**Comment by AshtonMemer** [comment]
DeepL API has a CORS policy that blocks requests from the frontend. A way to deal with this would be to use a proxy server, but then you would be sending your API key and potentially private message content to an individual's proxy server before DeepL.

**Comment by Sqaaakoi** [comment]
> DeepL API has a CORS policy that blocks requests from the frontend. A way to deal with this would be to use a proxy server, but then you would be sending your API key and potentially private message content to an individual's proxy server before DeepL.

we can just delete the CORS header in desktop clients (electron based) in the same way that CSP is modified https://github.com/Vendicated/Vencord/blob/main/src/main/index.ts#L90-L124

**Comment by AshtonMemer** [comment]
> we can just delete the CORS header in desktop clients (electron based) in the same way that CSP is modified [https://github.com/Vendicated/Vencord/blob/main/src/main/index.ts#L90-L124|](https://github.com/Vendicated/Vencord/blob/main/src/main/index.ts#L90-L124%7C)
> 
> it's also possible to make a "native" script that fetches that data for you

has this been done by an existing plugin yet?

**Comment by Sqaaakoi** [comment]
> > we can just delete the CORS header in desktop clients (electron based) in the same way that CSP is modified [https://github.com/Vendicated/Vencord/blob/main/src/main/index.ts#L90-L124|](https://github.com/Vendicated/Vencord/blob/main/src/main/index.ts#L90-L124%7C)
> > it's also possible to make a "native" script that fetches that data for you
> 
> has this been done by an existing plugin yet?

https://github.com/Vendicated/Vencord/blob/main/src/plugins/openInApp/native.ts
