### ISSUE TITLE
Firefox and Edge support 

### ISSUE THREAD

**Issue by iMonZ** [Vendicated/Vencord#1807]
### Content

Hey I can’t find it in the Firefox or edge store 

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by mantikafasi** [comment]
firefox support is dropped, for edge you can install from chrome web store

**Comment by iMonZ** [comment]
> firefox support is dropped, for edge you can install from chrome web store

Why is Firefox support dropped?
A lot of company pcs remove chrome store support for security reasons.

**Comment by iMonZ** [comment]
Is there any good alternative to Vencord. This project doesn't look like it receives much love

**Comment by MrDiamondDog** [comment]
You can use the userscript or you can get the firefox build and install it manually
