### ISSUE TITLE
[Bug] error upon trying to load plugin browser

### ISSUE THREAD

**Issue by UltraBlackLinux** [Vendicated/Vencord#1809]
### What happens when the bug or crash occurs?

I get an error after waiting like 10 seconds

### What is the expected behaviour?

not that

### How do you recreate this bug or crash?

click on the vencord/plugins button in the settings

I'm on discord web

### Errors

```
e@cc74d3737d867cde23d8.js:3478:795
Ts@cc74d3737d867cde23d8.js:3491:192
gu@cc74d3737d867cde23d8.js:3535:511
Ic@cc74d3737d867cde23d8.js:3528:91
mc@cc74d3737d867cde23d8.js:3528:19
hc@cc74d3737d867cde23d8.js:3527:867
oc@cc74d3737d867cde23d8.js:3524:642
uc@cc74d3737d867cde23d8.js:3525:49
Fi@cc74d3737d867cde23d8.js:3464:577
364448/rc/<@cc74d3737d867cde23d8.js:3522:555

```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by UltraBlackLinux** [comment]
My bad, but I'm not in the discord server yet...

**Comment by ImLvna** [comment]
https://discord.gg/RPsXv246
