### ISSUE TITLE
Not working on latest development build

### ISSUE THREAD

**Issue by cr1ptik** [Vendicated/Vencord#181]
Canary 155370 (e04d49d) Host 1.0.677 Windows 10 64-Bit (10.0.22000)

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/issues/183

**Comment by Vendicated** [comment]
(I will fix canary soon enough, just busy lately and would rather focus on more interesting things in the time I have. You're not missing out on anything by using stable so please just use stable for the time being!)
