### ISSUE TITLE
Vencord isnt working on portable discord

### ISSUE THREAD

**Issue by nizeyoral** [Vendicated/Vencord#1810]
### Content

Hey mate, could you fix this? I already tried it out and vencord just tells me that its the wrong folder lol?

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by MrDiamondDog** [comment]
> This form is ONLY FOR DEVELOPERS. YOUR ISSUE WILL BE CLOSED AND YOU WILL POSSIBLY BE BLOCKED FROM THE > REPOSITORY IF YOU IGNORE THIS.
