### ISSUE TITLE
[Feature Request] Update FakeNitro, with the custom icons feature

### ISSUE THREAD

**Issue by Sallyqwp** [Vendicated/Vencord#1811]
## Discord Account
sallyqwp

## What is it that you'd like to see?
Just update FakeNitro with the custom in-app icons

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by MrDiamondDog** [comment]
> ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.

**Comment by Vendicated** [comment]
this is a fair request and definitely doable

**Comment by MacroHard-Winux** [comment]
Please do it. It will be great :)

**Comment by Vendicated** [comment]
added

**Comment by EliasGagnef** [comment]
Is this also supposed to change the icon inside of Windows? It is not working for me on PTB

**Comment by ImLvna** [comment]
nope. only changes the icon in the top left
