### ISSUE TITLE
[Feature Request] Hide the Channels Tab

### ISSUE THREAD

**Issue by ItsOnlyMe360** [Vendicated/Vencord#1834]
### Discord Account
itsonlyme360

### What is it that you'd like to see?
A feature that allow users to hide the channels tab. Similar to [this](https://betterdiscord.app/plugin/Hide%20Channels) Better Discord plugin, but it is so necessary that I think it should be a feature.

_(a GIF as an example)_
![124384178-9618bd00-dcbf-11eb-970e-f78d8093dafc](https://github.com/Vendicated/Vencord/assets/126713125/a71eea16-ef9c-4353-b608-769770ca288d)

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by ImLvna** [comment]
ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
