### ISSUE TITLE
[Bug] readAllNotificationsButton not reading threads

### ISSUE THREAD

**Issue by mangkoran** [Vendicated/Vencord#1835]
### Discord Account

mangkoran

### What happens when the bug or crash occurs?

Threads are not read. Only regular channels are read

### What is the expected behaviour?

Threads are read

### How do you recreate this bug or crash?

1. Install `readAllNotificationsButton`
2. Make sure you participate in a thread and the thread has unread message
3. Click "Read all"

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by mangkoran** [comment]
Friendly ping @Vendicated

**Comment by nyakowint** [comment]
Use the inbox read all button lol

**Comment by mangkoran** [comment]
Sorry but then what's the point of this plugin?
