### ISSUE TITLE
[Bug] Plugins dont work

### ISSUE THREAD

**Issue by amawdiin** [Vendicated/Vencord#1838]
### Discord Account

amandin

### What happens when the bug or crash occurs?

oh i wish i could talk about this in discord but link doesnt work (i tried link from vencord.dev) so this issue is kinda breaking the rules but this is important

only "read all" button works, all of the other plugins simply dont work at all, even though they are enabled. yes i tried reinstalling, re-enabling, repairing, reloading, updating, everything i could think of 

### What is the expected behaviour?

i expect my enabled plugins to work instead of changing nothing 

### How do you recreate this bug or crash?

i honestly have no idea, yesterday i shut down my laptop, the next thing i knew this bug appeared. 

### Errors

```
Replace this text with your crash-log.
```
there was no crash though

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Cont0rt** [comment]
My discord crashed and is doing the exact same thing. There's only one plugin I have working and that's SpotifyControls. Glad to see I'm not the only one having issues.

**Comment by FieryFlames** [comment]
Discord released an update that changed the format of produced Discord code. Plugins will be fixed over the next few days probably. Plugins being broken was mentioned in the announcements channel.

**Comment by amawdiin** [comment]
oh okay its just that i also cant join the discord of vencord whatsoever

**Comment by criminalvibe** [comment]
Having the same issue. Verified that it wasn't working because I didn't have Read All enabled, enabled it and it's the only plugin that's working.

**Comment by CodeF53** [comment]
Here is what is happening:
![image](https://github.com/Vendicated/Vencord/assets/37855219/b9476773-a1e7-432f-8d4c-7284977d18a0)

In the future please try and use the discord's announcements channel before opening something on github

**Comment by fox3000foxy** [comment]
Same, but im using the Web extension one
![image](https://github.com/Vendicated/Vencord/assets/40730498/12778d88-a1b8-49f1-a151-73f7f64fa92c)

**Comment by DodoGames7** [comment]
It doesn't matter what you use. What Discord did applies to both web and their desktop app.

**Comment by fox3000foxy** [comment]
> It doesn't matter what you use. What Discord did applies to both web and their desktop app.

I know. Btw, after checking rules, im not allowed to talk into the server chat :/

**Comment by criminalvibe** [comment]
Same.

**Comment by DodoGames7** [comment]
That's because nobody can chat due to a lot of people being going to complain without ever reading for once. I suggest to wait until all channels are unlocked

**Comment by fox3000foxy** [comment]
Btw Vendetta works fine

**Comment by CodeF53** [comment]
"vencord is known to be broken"
![Screenshot_20231025-004455.png](https://github.com/Vendicated/Vencord/assets/37855219/f5d9c5b7-95f3-47b4-a3d6-461af21e6bfa)
Just wait until it's working.

**Comment by fox3000foxy** [comment]
> "vencord is known to be broken" ![Screenshot_20231025-004455.png](https://user-images.githubusercontent.com/37855219/277897895-f5d9c5b7-95f3-47b4-a3d6-461af21e6bfa.png) Just wait until it's working.

![image](https://github.com/Vendicated/Vencord/assets/40730498/b600187c-34de-4b9a-933e-8afde997ddec)

**Comment by fox3000foxy** [comment]
Btw i saw that the webpack chunk reduced to 207 items

**Comment by FieryFlames** [comment]
# Vencord is known to be broken.
### Commenting you have the same issue just clogs up the Vencord dev channel.
#### Please wait patiently while contributors work on fixing it.

**Comment by edulahariprasad** [comment]
can anyone please send me vencord discord server link

**Comment by fox3000foxy** [comment]
> can anyone please send me vencord discord server link

discord.gg/vencord

**Comment by fox3000foxy** [comment]
btw hi dev chat

**Comment by fox3000foxy** [comment]
lol

**Comment by FieryFlames** [comment]
bro stop 😭

**Comment by fox3000foxy** [comment]
> bro stop 😭

?

**Comment by fox3000foxy** [comment]
c'est le seul moyen d'ecrire dedans

**Comment by DodoGames7** [comment]
Just because channels are locked doesn't mean you can use this to chat 🤷‍♂️

**Comment by SuperErnD** [comment]
be silent please, do not spam with shit

**Comment by fox3000foxy** [comment]
dont lock that repo acces plz
im stop writing on it
but if someone have issue i want to be capable of reply

**Comment by blankripv** [comment]
guys daddy needs themes fixed chat 😞 i need themes brotha fix it NEOWWWWW or ill touch u

**Comment by Vendicated** [comment]
#1847
