### ISSUE TITLE
[Bug] Error in DMs

### ISSUE THREAD

**Issue by garv-shah** [Vendicated/Vencord#1841]
### What happens when the bug or crash occurs?

Currently in DMs, the side panel displays the following issue on the latest Vencord version:

<img width="336" alt="image" src="https://github.com/Vendicated/Vencord/assets/64292655/fa00810d-b201-4fdd-9ff7-3a069574cff5">

### What is the expected behaviour?

a normal side panel

### How do you recreate this bug or crash?

1. Install Vencord
2. Go to DMs

### Errors

```
TypeError: Cannot read properties of undefined (reading 'recipients')
    at index.tsx:82:41
    at iT (3761a6fb12b09e0724b2.js:1:717663)
    at l (3761a6fb12b09e0724b2.js:1:772873)
    at sj (3761a6fb12b09e0724b2.js:1:755889)
    at 3761a6fb12b09e0724b2.js:1:755755
    at sR (3761a6fb12b09e0724b2.js:1:755763)
    at sS (3761a6fb12b09e0724b2.js:1:752514)
    at sO (3761a6fb12b09e0724b2.js:1:752903)
    at r6 (3761a6fb12b09e0724b2.js:1:701538)
    at 3761a6fb12b09e0724b2.js:1:768416
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by blankripv** [comment]
hai the decorator daddy came back

**Comment by FieryFlames** [comment]
related to #1838

**Comment by blankripv** [comment]
decorator i need u to fucking bend over and let me rape u in a friendly way ty <3

**Comment by fox3000foxy** [comment]
stop writing shit plz (ironic ik)

**Comment by blankripv** [comment]
> stop writing shit plz (ironic ik)

beg and i will?

**Comment by blankripv** [comment]
beg like a good kitten

**Comment by blankripv** [comment]
rini dont fucking lock this 1 u fat monkey or daddy will get ANGY

**Comment by DodoGames7** [comment]
I swear this should be locked...

**Comment by MeguminSama** [comment]
Please see https://github.com/Vendicated/Vencord/issues/1838#issuecomment-1778627676
