### ISSUE TITLE
[Bug] <Themes doesn't work>

### ISSUE THREAD

**Issue by Tsaitou7361** [Vendicated/Vencord#1845]
### Discord Account

tsaitou7361

### What happens when the bug or crash occurs?

Theme doesn't work :(

### What is the expected behaviour?

I expect when I open Discord and enable a theme
then the theme will not work in the most screen (It just work on title bar)

### How do you recreate this bug or crash?

1. Open Discord
2. Install Vencord
3. Enable a theme
4. and you will see nothing has been changed...

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Tsaitou7361** [comment]
umm...

**Comment by MeguminSama** [comment]
See https://github.com/Vendicated/Vencord/issues/1847

**Comment by xsmashx88x** [comment]
so many good css's broken tthat never got turned into a plugin this sucks.. its crazy tho i have a css that changed the channel names and icon colors, works on browser not the windows desktop version

**Comment by D-u-c-k-s-e-l** [comment]
I'm sorry to necropost on this, but I'm trying to figure out why themes aren't working, and the linked issue was deleted.
