### ISSUE TITLE
READ THIS IF YOUR VENCORD IS BROKEN

### ISSUE THREAD

**Issue by Vendicated** [Vendicated/Vencord#1847]
## Vencord has now almost fully been fixed

Only very few plugins are still broken (FakeNitro partially, BetterFolders fully)

## How to update

- Discord Desktop: Use the Repair option in the installer
- Browser: We are waiting for google to approve the update. This may take a few days. The UserScript is fully up to date
- Vesktop: Update to Vesktop 0.4.1. Use the "Update Vencord" option when right clicking the Vesktop tray icon. If you're on Mac, use the MenuBar. If you cannot do this, go to your config folder (`%APPDATA%` on windows, `~/.config` on linux, `~/Library/Application Support` on mac) and delete `VencordDesktop/VencordDesktop/vencordDist`, then restart Vesktop.

## About Themes

Themes are still mostly broken. There is nothing we can do, you just need to wait for your theme's developer to fix it!

## Join Our Official Server To Keep Up With Announcements

https://vencord.dev/discord

**Comment by Tsaitou7361** [comment]
okay, thanks.
I tested that Basic Background is not affected!
