### ISSUE TITLE
plugin(AnonymiseFilenames) doesen't properly anonymise if filename contains more than 1 dot

### ISSUE THREAD

**Issue by KraXen72** [Vendicated/Vencord#186]
![image](https://user-images.githubusercontent.com/21956756/199250431-51823551-3248-4a70-83ea-805846c359c8.png)
![image](https://user-images.githubusercontent.com/21956756/199250459-748828a4-e9d1-4af7-a403-0fa29c99c648.png)

instead of splitting at first dot, it should split at last dot in string

**Comment by Vendicated** [comment]
this is hard to get right.

Foo.bar.zip should become ijssoqosqoksq.zip, but how about Foo.tar.gz?

**Comment by Ruthenic** [comment]
tbf that would be still identifiable as a tar file because file headers

**Comment by ArjixWasTaken** [comment]
Writing regex on phone is hard, lmao

**Comment by ArjixWasTaken** [comment]
Mfs, I sent the regex two days ago

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/199828992-bedd2ba0-4a94-4ab0-9bee-aec8cb358b3b.png)
@ArjixWasTaken  your regex broky

**Comment by KraXen72** [comment]
doesen't discord expose some more info about the file?
like can't you read it's mime type and use that or something?

**Comment by Vendicated** [comment]
why are you guys overcomplicating this

```js
const ex = file.endsWith(".tar.gz") ? "tar.gz" : file.slice(file.lastIndexOf(".") + 1)
```

**Comment by ArjixWasTaken** [comment]
> 

`.tar.bz2` is also a file extension that is in use...
you can't just hardcode `.gz`

**Comment by ArjixWasTaken** [comment]
> ![image](https://user-images.githubusercontent.com/21956756/199828992-bedd2ba0-4a94-4ab0-9bee-aec8cb358b3b.png) @ArjixWasTaken your regex broky

```js
/.*((?:\.tar)?\.[^.]+)$/
```
there, fixed
![image](https://user-images.githubusercontent.com/53124886/199840202-046c7466-6085-4d10-b1b8-0d67f21b7258.png)

**Comment by mantikafasi** [comment]
Just put a warning and say tar.gz is unsupported

**Comment by ArjixWasTaken** [comment]
ignore my typo
