### ISSUE TITLE
[Bug] Using Vencord on web prevents Discord from loading

### ISSUE THREAD

**Issue by 0xCUB3** [Vendicated/Vencord#1889]
### Discord Account

0xCUBE#9118

### What happens when the bug or crash occurs?

Rather than loading discord, a blank page opens.

### What is the expected behaviour?

Discord opens.

### How do you recreate this bug or crash?

1. Install Vencord on Chromium
2. Open Discord
3. Cry

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by ImLvna** [comment]
ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
read the announcements in the discord server

**Comment by VenomousSteam81** [comment]
Same issue. Be patient. _cries in vencord_

**Comment by Vendicated** [comment]
see pinned issue.
