### ISSUE TITLE
Custom Status Animation

### ISSUE THREAD

**Issue by zeyko-uma002** [Vendicated/Vencord#1892]
### Content

- I would like them to add the [Custom status (animated)] like **BetterDiscord** has, it is very useful to send and write different custom statuses either for work use (Patreon, etc) or messages to suit the person themselves.

_I will continue to wait as long as it takes for you to sort out the current problems._ fight-to~!

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
against our rules.
