### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by Choccymilkistaken** [Vendicated/Vencord#1897]
### Discord Account

choccymilkistaken

### What happens when the bug or crash occurs?

Every time I press "Show Icon" on SilentTyping plugin and restart the client, it does not hide the icon in the chat text box.

### What is the expected behaviour?

It prevents from hiding the icon from the chat box thing.

### How do you recreate this bug or crash?

1. Go to User settings
2. Go to Silent Typing plugin
3. Click on "Show Icon"
4. Restart the client and it SHOULD remove the icon, but it doesn't...

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by RadNotRed** [comment]
Cannot reproduce!!
