### ISSUE TITLE
[Bug] ImageZoom Gallery Zoom

### ISSUE THREAD

**Issue by RadNotRed** [Vendicated/Vencord#1900]
### Discord Account

radnotred1

### What happens when the bug or crash occurs?

This happens when you open a user's message with 2 or more attachments, when you unclick to zoom out, it closes the attachments.

### What is the expected behaviour?

I expect it to not show the zoom out magnifying glass while zooming 
Or it should just hide the zoom out magnifying glass completely 

### How do you recreate this bug or crash?

1) Open a user's attachment where there are 2 or more attachments
2) When you hover over, it will show the - magnifying glass and after you stop zooming, it will close the gallery.

### Errors

None

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
fixed via https://github.com/Vendicated/Vencord/commit/e37f62ac0a8d93bd354f09567e3e19dd7e8b7d63
