### ISSUE TITLE
so whats happening?

### ISSUE THREAD

**Issue by xsmashx88x** [Vendicated/Vencord#1904]
### Content

made a post about the css and was closed and linked to the update.. I know discord broke stuff and you posted update and got 99% of things working...

I am asking about the css cause for the browser it works just fine... I have a css that allows icon color change and many others from the discord, however on the windows version none of this works... whats the diff with the two to break all css tweak things?

the color css > https://gurzil.shx.gg/6hWxZlYrF.png via the browser as i said works.. amoung other useful css's i have but not on windows app as i said... will i have to wait for someone or the poster who did this to update it? or did something broke with the css thing on the vencord?

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
you need to update your css. i don't know what you want us to do, that's out of our control and the announcement says so.
