### ISSUE TITLE
ADD PLUGIN

### ISSUE THREAD

**Issue by miaucz** [Vendicated/Vencord#1916]
### Content

Can you add NotificationSounds plugin from BetterDiscord?

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by 0x3C50** [comment]
> I have read the requirements for opening an issue above
have you?

**Comment by ImLvna** [comment]
ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.
