### ISSUE TITLE
Reactions on messages don't work.

### ISSUE THREAD

**Issue by BudImCanadian** [Vendicated/Vencord#1922]
### Discord Account

deepinyahmum

### What happens when the bug or crash occurs?

Reactions from other server no longer work. Assuming its a plugin.

### What is the expected behaviour?

Emojis from other server to properly display. 

### How do you recreate this bug or crash?

Just try and use a reaction on someone's message. Won't work, will just dissapear. 

### Errors

No crash log. 

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Panniku** [comment]
are you perhaps using a nitro emoji using the fakenitro plugin?
