### ISSUE TITLE
plugin(NitroBypass): bug when trying to send an animated sticker Discord takes it as an attachment.

### ISSUE THREAD

**Issue by kaname-png** [Vendicated/Vencord#193]
Currently when you try to use an animated sticker and send it discord detects it as an attachment and you have to press enter to send it, something tedious, I do not know if this is the expected sharing, but it would be nice if the message box had text and when not that the sticker is sent directly.

https://user-images.githubusercontent.com/56084970/200437141-cb72c38c-a2ca-4223-b055-e070dd32d0b8.mp4

**Comment by Vendicated** [comment]
this is intended and changing it is a bad idea because some stickers convert very poorly so you probably don't wanna send it

**Comment by kaname-png** [comment]
I understand, but still with the current system animated stickers still convert badly to gif for some reason.

![Screenshot_20221107-234454_Discord.png](https://user-images.githubusercontent.com/56084970/200484804-d2348cff-c880-4dbe-b507-ffd28e6b4cb4.png)

And I think that since it is the expected result (passing the sticker as an attachment) it would be great if the message was sent directly together with the attached sticker automatically. And what just didn't do it when there is text in the message box. As mentioned above.

**Comment by Vendicated** [comment]
> I understand, but still with the current system animated stickers still convert badly to gif for some reason.

Yes, that's the point. Stickers are converted to gifs first because they are in an image format Discord doesn't support. Sometimes the conversion goes poorly, so you may want to see the result before sending it

**Comment by kaname-png** [comment]
Hmm, that sounds fair, but an option to customize that behavior would be nice.

**Comment by Vendicated** [comment]
this behaviour is the same as stock btw, it also just adds the sticker

![image](https://user-images.githubusercontent.com/45497981/200887802-eeb5c615-0838-40ca-ad08-be6be0c8ce4a.png)

**Comment by D3SOX** [comment]
Yeah, but only when you typed something.

Btw, a suggestion I had a while ago I wasn't sure if we want to implement this: When sending non-animated stickers it just adds the URL to the message, but that looks very ugly when sending it, so I think it would be better if it was downloaded and then attached as image. This could apply to emojis and stickers.

**Comment by ArjixWasTaken** [comment]
I thought this was intended...
Uploading the gif means that it won't show as a link

**Comment by ArjixWasTaken** [comment]
why is this still open?

**Comment by MeguminSama** [comment]
because at this point it's a feature request

**Comment by ArjixWasTaken** [comment]
Then the issue should be renamed, no?
