### ISSUE TITLE
Suggestion for Vencord Plugins:

### ISSUE THREAD

**Issue by Choccymilkistaken** [Vendicated/Vencord#1939]
### Content

Hi there,

I'm not entirely familiar with using Github, so I hope this message reaches the right people. I have a suggestion for the vencord app developers: could you consider adding a feature that allows users to hide certain buttons?

Here's a simple idea of how it could work:

Navigate to the 'Plugins' section.
Enter "Hide Buttons" or a similarly fitting name for this new plugin.
Once selected, this plugin would give users the option to choose which buttons they'd like to hide. For instance, the ability to hide the mentions button to prevent accidental @ mentions on Discord (which can be a bit bothersome at times), or even the call button.
If you need more ideas for this plugin, feel free to use this suggestion as a starting point.

Thanks for considering this!

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
css can do this. this form is also not for suggestions and you were very clearly told this when opening it
