### ISSUE TITLE
Message Logger Support

### ISSUE THREAD

**Issue by hackthedev** [Vendicated/Vencord#1942]
### Content

Hi its not an issue more like a super important thing to me.
The message logger is so extremely helpful when it comes to moderating server and creeps in dms.
Never let it die its so amazing.
I might donate at some point. Thats it! 

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by D3SOX** [comment]
There already is a message logger plugin and you haven't read the requirements for opening an issue...
