### ISSUE TITLE
[Feature Request] Implement Contextmenu for selected text in WebContextMenu plugin

### ISSUE THREAD

**Issue by MGThePro** [Vendicated/Vencord#1943]
### Content

Without this you can't copy or search any selected text via right click on vesktop

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by reedrw** [comment]
Additional context: https://github.com/Vencord/Vesktop/issues/202

**Comment by AstralPhnx** [comment]
+1 on this. I use this feature all the time and it's kinda baffling that it's not supported at all when I can use other clients like Armcord, load Vencord into them as a client mod and have this feature just work. It's a real pain in the backside

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/commit/8a7c0d7e61503ce60cc5308e96d54c420125aad0
