### ISSUE TITLE
[Bug] OpenASAR can no longer be installed with the installer

### ISSUE THREAD

**Issue by lockieluke** [Vendicated/Vencord#1962]
### Discord Account

lockieluke3389#5305

### What happens when the bug or crash occurs?

The current installer(built from source)fails to install OpenASAR with Vencord

### What is the expected behaviour?

An OpenASAR menu would appear in settings

### How do you recreate this bug or crash?

1. Install OpenASAR with Vencord Installer
2. Restart Discord and go to settings
3. OpenASAR menu is not there

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
wrong repo

you ignored the clear warnings telling you NOT to open an issue

we don't provide support for arrpc
