### ISSUE TITLE
[Bug] Vencord Web : Status dot and user assets are offset

### ISSUE THREAD

**Issue by EDM115** [Vendicated/Vencord#1969]
### Discord Account

edm115

### What happens when the bug or crash occurs?

Nearly all places that holds an asset on top of another asset have an offset.  
This applies to the red dot on the pinned icon, the user status (Online, Idle, ...), the user avatar in several places (User profile popout, chat list, members list, ...), the user banner (same), but also in the Shop.  
See screenshots for more

### What is the expected behaviour?

These assets shouldn't collide nor have an offset.

### How do you recreate this bug or crash?

1. Install Vencord Web extension
2. That's it

### Errors

Here's some screenshots :  

User Profile in DM :
![image](https://github.com/Vendicated/Vencord/assets/82015596/e753e526-15b8-45c2-bdcf-df51e1fd99a1)
  
DM's list :
![image](https://github.com/Vendicated/Vencord/assets/82015596/4a454bc7-6e6f-499b-ba58-e6e0723fdd38)
  
Placeholders in the Shop :
![image](https://github.com/Vendicated/Vencord/assets/82015596/79dbcb30-87e5-444e-8da3-4db7f84bd8e7)
  
Settings - My Account :
![image](https://github.com/Vendicated/Vencord/assets/82015596/b165e55b-b45c-4a92-b493-bf971f7bb596)
  
Chat toolbar :
![image](https://github.com/Vendicated/Vencord/assets/82015596/abd96413-c10a-4a2a-8cd4-8da9459af381)
  
Server Members list :
![image](https://github.com/Vendicated/Vencord/assets/82015596/e6f27753-e39f-4c77-8967-8c19485e1574)
  
User Profile (on click) :
![image](https://github.com/Vendicated/Vencord/assets/82015596/e8156fb6-b1ef-4745-94bf-4a2fa5c92918)
  
User Profile :
![image](https://github.com/Vendicated/Vencord/assets/82015596/9ae5bf73-01a4-410b-9d03-8f9ac0acb777)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by EDM115** [comment]
note that :  
- some profiles aren't affected by this (and may be affected after we change server/chat)
- the PlatformIndicators plugin have no effect on this

**Comment by josiauh** [comment]
what plugins you got enabled

**Comment by josiauh** [comment]
and what browser

**Comment by EDM115** [comment]
browser : chrome dev 121.0.6103.3  
extensions : a lot
![image](https://github.com/Vendicated/Vencord/assets/82015596/3255293c-a970-4c82-857b-0c54a2265fff)
![image](https://github.com/Vendicated/Vencord/assets/82015596/b5db5a21-fc5b-41e6-bfcb-4ca3f4c577ff)
![image](https://github.com/Vendicated/Vencord/assets/82015596/81294173-f3be-4dcc-83de-74006a64481e)
![image](https://github.com/Vendicated/Vencord/assets/82015596/f24f93f4-50fc-46b3-a7b8-2c5b3c77c49e)
![image](https://github.com/Vendicated/Vencord/assets/82015596/346afdef-1930-419d-a6b6-0c6eff83a0d1)
![image](https://github.com/Vendicated/Vencord/assets/82015596/e73d0e8d-5c93-4b17-b3ac-489e716a9d20)
plus WhoReacted and Wikisearch

BUT
after disabling all plugins, the bug is still present. no plugin is the source of this issue

**Comment by josiauh** [comment]
do you have some sort of theme enabled too

**Comment by EDM115** [comment]
yes sir  
- Dracula Pro - Van Helsing Variant
- EmojiReplace by DevilBro

but once again, disabling them changes nothing

**Comment by Vendicated** [comment]
theme issue
