### ISSUE TITLE
[Bug] Unable to connect to arRPC.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Vendicated/Vencord#1985]
### Discord Account

https://linksta.cc/going/380957121?https://discord.com/users/798720532848705576

### What happens when the bug ~~or crash~~ occurs?

When I visit https://canary.discord.com via Firefox, or install the Vencord Flatpak package, I see

> ![20240309T200034GMT](https://github.com/Vendicated/Vencord/assets/42837531/5be8b08c-a652-49b0-afe4-cb6d94810940)

### What is the expected behaviour?

arRPC should connect, or if it is, the banner shouldn't be present.

### How do you recreate this bug or crash?

1.	Install `cpe:/o:opensuse:tumbleweed:20240307`.

*	1.	Install https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-123.0-1.1.x86_64.rpm.
	1.	Install https://addons.mozilla.org/firefox/downloads/file/4185752/violentmonkey-2.16.0.xpi.
	1.	Add https://github.com/Vencord/builds/blob/0e55d2ddeb24b4b7dc72c21929529c1b3032f528/Vencord.user.js (from https://vencord.dev/download/) to ViolentMonkey.
	1.	```PS1
		firefox https://canary.discord.com
		```

*	1.	```.PS1
		flatpak install https://dl.flathub.org/repo/appstream/dev.vencord.Vesktop.flatpakref && `
		flatpak update app/dev.vencord.Vesktop/x86_64/stable --commit=70a623e0e430953bbd39aac618662b4009459692c82c335b1131f412e4e9b047
		```
	1.	```.PS1
		flatpak run app/dev.vencord.Vesktop/x86_64/stable
		```

### Errors

https://github.com/Vendicated/Vencord/files/13351817/console-export-2023-11-14_16-30-58.txt

### Request Agreement

- [ ] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Vendicated/Vencord/issues/1985#issuecomment-1810628323

It also occurs on

```.PS1
flatpak install https://dl.flathub.org/repo/appstream/dev.vencord.Vesktop.flatpakref
flatpak update app/dev.vencord.Vesktop/x86_64/stable --commit=70a623e0e430953bbd39aac618662b4009459692c82c335b1131f412e4e9b047`
```

**Comment by Vendicated** [comment]
can't reproduce and not vencord's fault either way! likely an issue on your/arrpc's end

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Vendicated/Vencord/issues/1985#issuecomment-2111487834

@Vendicated, do you know how to diagnose what component's fault it is, so that we might be certain? Regardless, I've reported this to https://github.com/OpenAsar/arrpc/issues/90#issue-2297485776 as directed. Thanks for the assistance.
