### ISSUE TITLE
[Feature Request] Charcounter

### ISSUE THREAD

**Issue by GamerKub-69** [Vendicated/Vencord#1991]
### Content

![goodgood](https://github.com/Vendicated/Vencord/assets/124099558/ad826168-6825-4c13-938f-c0944843fb8c)
Can i bring this back and ask why no one has actually made this yet. Its an amazing idea. and would make writing super long messages easier

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by GamerKub-69** [comment]
I mean not to be that guy, but if Vendetta has it, why doesn't the main thing have it

**Comment by MrDiamondDog** [comment]
Vendetta isn't made or maintained by us

**Comment by ImLvna** [comment]
I mean not to be that guy, but thats exactly what you were saying

**Comment by GamerKub-69** [comment]
yall cant understand what im saying

**Comment by ImLvna** [comment]
> vendetta
> the main thing

**Comment by affaxltd** [comment]
> yall cant understand what im saying

You're saying if Vendetta has it why Vencord doesn't.
The reason: Vencord isn't Vendetta.
Even if Ven is a part of both, they are still not the same project.

Pretty sure you just don't understand yourself

**Comment by TheKodeToad** [comment]
AFAIK ven only has one contribution to Vendetta
Anyway IDK what the purpose of this conversation is :sob:
