### ISSUE TITLE
[Plugin Reques] Charcounter

### ISSUE THREAD

**Issue by PluginRequester** [Vendicated/Vencord#1993]
### **Making this plugin would help when writing long messages**

- Would start off displaying 2000 limit, even with Nitro, unless disabled

- Would switch to 4000 once message is over 2000 **if subscription is active, or unless previous setting is disabled, in which case, it will always display 4000 when subscription is active** 

- Options to display; characters typed, characters remaining, both at once

**Could work the BD one 
https://betterdiscord.app/plugin/CharCounter
Or could work like the Vendetta one 
https://github.com/nexpid/VendettaPlugins/tree/main/plugins/char-counter**

_**I know y'all don't like people linking to other plugins, im just giving you ideas**_

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by ant0n-0x0000** [comment]
Duplicate issue to #1991 why would you close then reopen under an alt??

**Comment by MrDiamondDog** [comment]
I was thinking about making this plugin but now I don't want to.

**Comment by ant0n-0x0000** [comment]
@PluginRequester Stop spamming issues, we get it, we know what you want. Being weird will NOT get it to you faster :husk:
