### ISSUE TITLE
[Feature Request] Custom rtmp for streaming in discord

### ISSUE THREAD

**Issue by lera2od** [Vendicated/Vencord#1997]
### Content

I want to stream in discord with my obs overlay. I thought that discord streaming probably uses rtmp to stream and there should be a way to use this as the obs rtmp server.

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by MrDiamondDog** [comment]
If you use a virtual camera you can stream that

**Comment by lera2od** [comment]
there is no sound

**Comment by MrDiamondDog** [comment]
Then idk
