### ISSUE TITLE
[Bug] "ShowHiddenChannels" plugin blocks from moving categories

### ISSUE THREAD

**Issue by CavxL** [Vendicated/Vencord#2034]
### What happens when the bug or crash occurs?

Cannot move categories on my own discord server.

### What is the expected behaviour?

I should be able to move the categories.

### How do you recreate this bug or crash?

Enable "ShowHiddenChannels" plugin
Go on your own server and try to move categories above and below other categories

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Cats1337** [comment]
Check if "Show All Channels" is unchecked.
Tried with it unchecked, and it doesn't work. Checking it allows you to move channels around.

**Comment by Vendicated** [comment]
like Cats said, make sure you have that enabled. the plugin doesn't change anyhting about reordering, so it really shouldn't interefere

but even if it does somehow, it'd be best for you to just temporarily disable the plugin to reorder channels
