### ISSUE TITLE
Plugin - NitroBypass: Option to scale emotes to be larger just like stickers.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Vendicated/Vencord#204]
Title is pretty simple to understand, add a slider for emote size like the sticker size slider. Reason being is some emotes look very crusty at low res. Pretty sure max size for emotes is 128x.

**Comment by Vendicated** [comment]
The max size is actually 4096 like for most (if not all?) other files but you'll never:tm: find an emote this large but yes this is a good idea!
