### ISSUE TITLE
[Feature/Pulgin Request] Save Voice Messages/Memos

### ISSUE THREAD

**Issue by KrstlSkll69** [Vendicated/Vencord#2053]
### Content

The ability to easily save voice messages/memo**(as ether .mp3/.ogg/.wav files)**

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by ImLvna** [comment]
creep

**Comment by Vendicated** [comment]
- ViewRaw can do this
- please do not abuse this form.
