### ISSUE TITLE
[Bug] Toolbox actions are present even if plugin is disabled

### ISSUE THREAD

**Issue by Kyuuhachi** [Vendicated/Vencord#2079]
### Discord Account

kyuuhachi

### What happens when the bug or crash occurs?

Toolbox actions are present in the Vencord Toolbox regardless of whether the owning plugin is enabled or not.

### What is the expected behaviour?

They should only be present if the plugin is enabled.

### How do you recreate this bug or crash?

Define a tiny plugin with a toolbox action:
```js
import definePlugin from "@utils/types";

export default definePlugin({
    name: "0_Example",
    description: "Showcases a bug with toolbox actions",
    authors: [{ id: 236588665420251137n, name: "Kyuuhachi" }],

    toolboxActions: {
        async "Example action"() { }
    },
});
```

Open the Vencord Toolbox in the top right corner. The action(s) from the plugin are still there, even if the plugin is disabled.

This happens regardless of whether the plugin is in `src/plugins` or `src/userplugins`.

### Errors

None.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
fixed in https://github.com/Vendicated/Vencord/commit/3eada99ad623ae783a39eb2c8238ac66ed371132
