### ISSUE TITLE
[FEATURE REQUEST] SilentTyping enabled/disabled set cache

### ISSUE THREAD

**Issue by zero5enpai** [Vendicated/Vencord#2102]
### Content

Add a cache function to the enabled/disabled set bound to the channel ID. 
! The Show Icon option has to be enabled !

The plugin would be able to save your last set, whether DM or server channel. 
Would have to be saved beyond one discord session.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by mufaroxyz** [comment]
Do you have any example use cases for that? Just wondering

**Comment by rniii** [comment]
has been made, slightly different: https://codeberg.org/vee/cord/pulls/7
(icon is global, the slash command has a local subcommand)

**Comment by zero5enpai** [comment]
> Do you have any example use cases for that? Just wondering

Sure: 
People you dont want to hide your typing status from like close friends

**Comment by mufaroxyz** [comment]
> has been made, slightly different: https://codeberg.org/vee/cord/pulls/7

Pretty neat, though I was thinking of a different approach to that, like automatically saving the override for the specific channel id whenever it's enabled (on click, rather than a subcommand)

**Comment by zero5enpai** [comment]
thanks to @D3SOX for implementing such function <3
[Plugin Link](https://github.com/D3SOX/vencord-userplugins/tree/1609d75af01100edf6b2b6f1ce3f1b67d0cf3253/silentTyping)
