### ISSUE TITLE
Discord link not work 

### ISSUE THREAD

**Issue by Schrotty74** [Vendicated/Vencord#2111]
### Content

The discord link not work 

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by MrDiamondDog** [comment]
Works on my machine

**Comment by Schrotty74** [comment]
No get a error.

![IMG_0733](https://github.com/Vendicated/Vencord/assets/25227541/a22ed3de-02a8-477a-96ce-35d0f01bff59)

**Comment by aamiaa** [comment]
You might be ratelimited or banned from the server. Either way it's a you issue, the link works for everyone else.

**Comment by Schrotty74** [comment]
No not banned. its a new account. its only work for you but not other.

**Comment by Schrotty74** [comment]
Why close? Please remove the ban.
