### ISSUE TITLE
[Bug] MoreUserTags misaligned with native tags like Remix

### ISSUE THREAD

**Issue by alexiayaa** [Vendicated/Vencord#2119]
### Discord Account

alexiaya

### What happens when the bug or crash occurs?

Tags from MoreUserTags are not aligned with native Discord tags like Remix.

### What is the expected behaviour?

They should be aligned.

### How do you recreate this bug or crash?

One way is to have a moderator use the Remix feature of Discord.

<img width="428" alt="image" src="https://github.com/Vendicated/Vencord/assets/148620615/5af88f1c-e25a-4f20-8e01-1621cf24106c">

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
stock discord issue. for some weird reason they add 0.3em top to the remix tag, while the bot tag is 0.1em

this is without the plugin enabled, spoofing myself as a bot
![image](https://github.com/Vendicated/Vencord/assets/45497981/647d6d0b-05a6-4975-9e76-9800a8a686a6)

you can fix it with this css snippet
```css
.botTagRemix_abf2f2 {
    top: 0.1rem !important;
}
```

**Comment by Vendicated** [comment]
the plugin just repurposes the BOT badge component with no style changes. to fix this issue, we'd need to mess with default styles which is meh
