### ISSUE TITLE
A tired dev.

### ISSUE THREAD

**Issue by onstar9** [Vendicated/Vencord#2124]
### Content

Hello, I am a developer and I tried making my very own plugin for discord. But one thing keeps itching my brain, I don't know which part of it is wrong or where I made a mistake. 
I tried making a plugin like this https://betterdiscord.app/plugin/NotificationSounds but I couldn't make it.
So can you make it for Vencord and upload it to the plugins folder thx kbye.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by MrDiamondDog** [comment]
1. Don't make an issue for this. Use #coding or #vencord-dev in the Discord and we can help you
2. Show us your code. "Doesn't work" doesn't really help when we don't know what isn't working.

**Comment by TheKodeToad** [comment]
https://github.com/Vendicated/Vencord/pull/1765

**Comment by onstar9** [comment]
omg just make the plugin dood, or at least let us upload custom pluginsSSSSSSSSSSSSS

**Comment by onstar9** [comment]
WHY IS FEATURE REQUEST TEPM,PORAILY CLOSED
