### ISSUE TITLE
weird Parseer error on variable - firefox tampermonkey script version

### ISSUE THREAD

**Issue by SCARaw** [Vendicated/Vencord#2131]
### Content

```"use strict";var Vencord=(()=>{var Ww=Object.create;var pa=Object.defineProperty;var qw=Object.getOwnPropertyDescriptor;var Kw=Object.getOwnPropertyNames;var Yw=Object.getPrototypeOf,Zw=Object.prototype.hasOwnProperty;var Gi=(e=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(e,{get:(t,o)=>(typeof require<"u"?require:t)[o]}):e)(function(e){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+e+'" is not supported')});var y=(e,t)=>()=>(e&&(t=e(e=0)),t);var Mh=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports),Ye=(e,t)=>{for(var o in t)pa(e,o,{get:t[o],enumerable:!0})},Ph=(e,t,o,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of Kw(t))!Zw.call(e,i)&&i!==o&&pa(e,i,{get:()=>t[i],enumerable:!(r=qw(t,i))||r.enumerable});return e};var Ih=(e,t,o)=>(o=e!=null?Ww(Yw(e)):{},Ph(t||!e||!e.__esModule?pa(o,"default",{value:e,enumerable:!0}):o,e)),mr=e=>Ph(pa({},"__esModule",{value:!0}),e);function Xw(e){if(!e)return{};let t={},o=e.trim().split(`
`);for(var r=0;r<o.length;r++){var i=o[r],s=i.indexOf(":"),c=i.slice(0,s).trim().toLowerCase(),u=i.slice(s+1).trim();t[c]===void 0?t[c]=u:Array.isArray(t[c])?t[c].push(u):t[c]=[t[c],u]}return t}function Oc(e,t){return e==="arrayBuffer"&&t.arrayBuffer?t.arrayBuffer():new Promise((o,r)=>{var i=new FileReader;i.onload=s=>o(s.target.result),e==="arrayBuffer"?i.readAsArrayBuffer(t):e==="text"?i.readAsText(t,"utf-8"):r("unknown to")})}function Qw(e,t){return new Promise((o,r)=>{let i=t||{};i.url=e,i.data=i.body,i.responseType="blob",i.onload=s=>{var c=s.response;s.blob=()=>Promise.resolve(c),s.arrayBuffer=()=>Oc("arrayBuffer",c),s.text=()=>Oc("text",c),s.json=async()=>JSON.parse(await Oc("text",c)),s.headers=new Headers(Xw(s.responseHeaders)),s.ok=s.status>=200&&s.status<300,o(s)},i.ontimeout=()=>r("fetch timeout"),i.onerror=()=>r("fetch error"),i.onabort=()=>r("fetch abort"),GM_xmlhttpRequest(i)})}var h,a=y(()=>{"use strict";h=Qw});var f,n,l=y(()=>{"use strict";f=Symbol.for("react.fragment"),n=(...e)=>(n=Vencord.Webpack.Common.React.createElement)(...e)});var Ho={};Ye(Ho,{clear:()=>tM,createStore:()=>da,del:()=>zi,delMany:()=>eM,entries:()=>Uc,get:()=>gt,getMany:()=>Vw,keys:()=>oM,promisifyRequest:()=>qt,set:()=>Dt,setMany:()=>Jw,update:()=>fr,values:()=>nM});function qt(e){return new Promise((t,o)=>{e.oncomplete=e.onsuccess=()=>t(e.result),e.onabort=e.onerror=()=>o(e.error)})}function da(e,t){let o=indexedDB.open(e);o.onupgradeneeded=()=>o.result.createObjectStore(t);let r=qt(o);return(i,s)=>r.then(c=>s(c.transaction(t,i).objectStore(t)))}function Io(){return _c||(_c=da("VencordData","VencordStore")),_c}function gt(e,t=Io()){return t("readonly",o=>qt(o.get(e)))}function Dt(e,t,o=Io()){return o("readwrite",r=>(r.put(t,e),qt(r.transaction)))}function Jw(e,t=Io()){return t("readwrite",o=>(e.forEach(r=>o.put(r[1],r[0])),qt(o.transaction)))}function Vw(e,t=Io()){return t("readonly",o=>Promise.all(e.map(r=>qt(o.get(r)))))}function fr(e,t,o=Io()){return o("readwrite",r=>new Promise((i,s)=>{r.get(e).onsuccess=function(){try{r.put(t(this.result),e),i(qt(r.transaction))}catch(c){s(c)}}}))}function zi(e,t=Io()){return t("readwrite",o=>(o.delete(e),qt(o.transaction)))}function eM(e,t=Io()){return t("readwrite",o=>(e.forEach(r=>o.delete(r)),qt(o.transaction)))}function tM(e=Io()){return e("readwrite",t=>(t.clear(),qt(t.transaction)))}function Bc(e,t){return e.openCursor().onsuccess=function(){!this.result||(t(this.result),this.result.continue())},qt(e.transaction)}function oM(e=Io()){return e("readonly",t=>{if(t.getAllKeys)return qt(t.getAllKeys());let o=[];return Bc(t,r=>o.push(r.key)).then(()=>o)})}function nM(e=Io()){return e("readonly",t=>{if(t.getAll)return qt(t.getAll());let o=[];return Bc(t,r=>o.push(r.value)).then(()=>o)})}function Uc(e=Io()){return e("readonly",t=>{if(t.getAll&&t.getAllKeys)return Promise.all([qt(t.getAllKeys()),qt(t.getAll())]).then(([r,i])=>r.map((s,c)=>[s,i[c]]));let o=[];return e("readonly",r=>Bc(r,i=>o.push([i.key,i.value])).then(()=>o))})}var _c,Ao=y(()=>{"use strict";a();l();});var Hi,Fc=y(()=>{"use strict";a();l();Hi=class{set=new Set;get changeCount(){return this.set.size}get hasChanges(){return this.changeCount>0}handleChange(t){this.set.delete(t)||this.set.add(t)}add(t){return this.set.add(t)}remove(t){return this.set.delete(t)}getChanges(){return this.set.values()}map(t){return[...this.getChanges()].map(t)}}});var Co,ji=y(()=>{a();l();Co="4bb0db5"});var ma,Ch=y(()=>{a();l();ma="Vendicated/Vencord"});var jo,rM,$c,fa,d,Kr,k=y(()=>{"use strict";a();l();ji();Ch();jo="webpackChunkdiscord_app",rM="Vencord.Webpack.Common.React",$c=`Vencord/${Co}${ma?` (https://github.com/${ma})`:""}`,fa="1026515880080842772",d=Object.freeze({Ven:{name:"Vendicated",id:343383572805058560n},Arjix:{name:"ArjixWasTaken",id:674710789138939916n},Cyn:{name:"Cynosphere",id:150745989836308480n},Megu:{name:"Megumin",id:545581357812678656n},botato:{name:"botato",id:440990343899643943n},obscurity:{name:"obscurity",id:336678828233588736n},rushii:{name:"rushii",id:295190422244950017n},Glitch:{name:"Glitchy",id:269567451199569920n},Samu:{name:"Samu",id:702973430449832038n},Nyako:{name:"nyako",id:118437263754395652n},MaiKokain:{name:"Mai",id:722647978577363026n},echo:{name:"ECHO",id:712639419785412668n},katlyn:{name:"katlyn",id:250322741406859265n},nea:{name:"nea",id:310702108997320705n},Nuckyz:{name:"Nuckyz",id:235834946571337729n},D3SOX:{name:"D3SOX",id:201052085641281538n},Nickyux:{name:"Nickyux",id:427146305651998721n},mantikafasi:{name:"mantikafasi",id:287555395151593473n},Xinto:{name:"Xinto",id:423915768191647755n},JacobTm:{name:"Jacob.Tm",id:302872992097107991n},DustyAngel47:{name:"DustyAngel47",id:714583473804935238n},BanTheNons:{name:"BanTheNons",id:460478012794863637n},BigDuck:{name:"BigDuck",id:1024588272623681609n},AverageReactEnjoyer:{name:"Average React Enjoyer",id:1004904120056029256n},adryd:{name:"adryd",id:0n},Tyman:{name:"Tyman",id:487443883127472129n},afn:{name:"afn",id:420043923822608384n},KraXen72:{name:"KraXen72",id:379304073515499530n},kemo:{name:"kemo",id:299693897859465228n},dzshn:{name:"dzshn",id:310449948011528192n},Ducko:{name:"Ducko",id:506482395269169153n},jewdev:{name:"jewdev",id:222369866529636353n},Luna:{name:"Luny",id:821472922140803112n},Vap:{name:"Vap0r1ze",id:454072114492866560n},KingFish:{name:"King Fish",id:499400512559382538n},Commandtechno:{name:"Commandtechno",id:296776625432035328n},TheSun:{name:"ActuallyTheSun",id:406028027768733696n},axyie:{name:"'ax",id:273562710745284628n},pointy:{name:"pointy",id:99914384989519872n},SammCheese:{name:"Samm-Cheese",id:372148345894076416n},zt:{name:"zt",id:289556910426816513n},captain:{name:"Captain",id:347366054806159360n},nick:{name:"nick",id:347884694408265729n,badge:!1},whqwert:{name:"whqwert",id:586239091520176128n},lewisakura:{name:"lewisakura",id:96269247411400704n},RuiNtD:{name:"RuiNtD",id:157917665162297344n},hunt:{name:"hunt-g",id:222800179697287168n},cloudburst:{name:"cloudburst",id:892128204150685769n},Aria:{name:"Syncxv",id:549244932213309442n},TheKodeToad:{name:"TheKodeToad",id:706152404072267788n},LordElias:{name:"LordElias",id:319460781567639554n},juby:{name:"Juby210",id:324622488644616195n},Alyxia:{name:"Alyxia Sother",id:952185386350829688n},Remty:{name:"Remty",id:335055032204656642n},skyevg:{name:"skyevg",id:1090310844283363348n},Dziurwa:{name:"Dziurwa",id:1001086404203389018n},F53:{name:"F53",id:280411966126948353n},AutumnVN:{name:"AutumnVN",id:393694671383166998n},pylix:{name:"pylix",id:492949202121261067n},Tyler:{name:"\\\\GGTyler\\\\",id:143117463788191746n},RyanCaoDev:{name:"RyanCaoDev",id:952235800110694471n},Strencher:{name:"Strencher",id:415849376598982656n},FieryFlames:{name:"Fiery",id:890228870559698955n},KannaDev:{name:"Kanna",id:317728561106518019n},carince:{name:"carince",id:818323528755314698n},PandaNinjas:{name:"PandaNinjas",id:455128749071925248n},CatNoir:{name:"CatNoir",id:260371016348336128n},outfoxxed:{name:"outfoxxed",id:837425748435796060n},UwUDev:{name:"UwU",id:691413039156690994n},amia:{name:"amia",id:142007603549962240n},phil:{name:"phil",id:305288513941667851n},ImLvna:{name:"Luna <3",id:799319081723232267n},rad:{name:"rad",id:610945092504780823n},AndrewDLO:{name:"Andrew-DLO",id:434135504792059917n},HypedDomi:{name:"HypedDomi",id:354191516979429376n},Rini:{name:"Rini",id:1079479184478441643n},castdrian:{name:"castdrian",id:224617799434108928n},Arrow:{name:"arrow",id:958158495302176778n},bb010g:{name:"bb010g",id:72791153467990016n},Lumap:{name:"lumap",id:635383782576357407n},Dolfies:{name:"Dolfies",id:852892297661906993n},RuukuLada:{name:"RuukuLada",id:119705748346241027n},blahajZip:{name:"blahaj.zip",id:683954422241427471n},archeruwu:{name:"archer_uwu",id:160068695383736320n},ProffDea:{name:"ProffDea",id:609329952180928513n},ant0n:{name:"ant0n",id:145224646868860928n},philipbry:{name:"philipbry",id:554994003318276106n},Korbo:{name:"Korbo",id:455856406420258827n},maisymoe:{name:"maisy",id:257109471589957632n},Grzesiek11:{name:"Grzesiek11",id:368475654662127616n},Samwich:{name:"Samwich",id:976176454511509554n},coolelectronics:{name:"coolelectronics",id:696392247205298207n}}),Kr=(()=>Object.freeze(Object.fromEntries(Object.entries(d).filter(e=>e[1].id!==0n).map(([e,t])=>[t.id,t]))))()});function Ut(e,t=300){let o;return function(...r){clearTimeout(o),o=setTimeout(()=>{e(...r)},t)}}var gr=y(()=>{"use strict";a();l()});function hr(e,t=5){let o=0,r;return()=>(!r&&t>o++&&(r=e(),!r&&t===o&&console.error("Lazy factory failed:",e)),r)}function Ft(e,t=5,o=!1){let r=!0;o||setTimeout(()=>r=!1,0);let i=0,s=Object.assign(function(){},{[Wi]:void 0,[Yr](){return!s[Wi]&&t>i++&&(s[Wi]=e(),!s[Wi]&&t===i&&console.error("Lazy factory failed:",e)),s[Wi]}});return new Proxy(s,{...ga,get(c,u,p){return!o&&r?Ft(()=>Reflect.get(c[Yr](),u,p),t,!0):Reflect.get(c[Yr](),u,p)}})}var Nh,ga,Yr,Wi,Wo=y(()=>{"use strict";a();l();Nh=["arguments","caller","prototype"],ga={},Yr=Symbol.for("vencord.lazy.get"),Wi=Symbol.for("vencord.lazy.cached");for(let e of["apply","construct","defineProperty","deleteProperty","getOwnPropertyDescriptor","getPrototypeOf","has","isExtensible","ownKeys","preventExtensions","set","setPrototypeOf"])ga[e]=(t,...o)=>Reflect[e](t[Yr](),...o);ga.ownKeys=e=>{let t=e[Yr](),o=Reflect.ownKeys(t);for(let r of Nh)o.includes(r)||o.push(r);return o};ga.getOwnPropertyDescriptor=(e,t)=>{if(typeof t=="string"&&Nh.includes(t))return Reflect.getOwnPropertyDescriptor(e,t);let o=Reflect.getOwnPropertyDescriptor(e[Yr](),t);return o&&Object.defineProperty(e,t,o),o}});function ct(e,t=5){let o=hr(e,t),r=i=>{let s=o()??iM;return n(s,{...i})};return r.$$vencordInternal=o,r}var iM,Gc=y(()=>{"use strict";a();l();Wo();iM=()=>null});var ie,Ze=y(()=>{"use strict";a();l();ie=class{constructor(t,o="white"){this.name=t;this.color=o}static makeTitle(t,o){return["%c %c %s ","",`background: ${t}; color: black; font-weight: bold; border-radius: 5px;`,o]}_log(t,o,r,i=""){console[t](`%c Vencord %c %c ${this.name} ${i}`,`background: ${o}; color: black; font-weight: bold; border-radius: 5px;`,"",`background: ${this.color}; color: black; font-weight: bold; border-radius: 5px;`,...r)}log(...t){this._log("log","#a6d189",t)}info(...t){this._log("info","#a6d189",t)}error(...t){this._log("error","#e78284",t)}errorCustomFmt(t,...o){this._log("error","#e78284",o,t)}warn(...t){this._log("warn","#e5c890",t)}debug(...t){this._log("debug","#eebebe",t)}}});function an(e){if(typeof e=="string")return e;let t=e.source.replaceAll("\\i","[A-Za-z_$][\\w$]*");return new RegExp(t,e.flags)}function ha(e,t){let o=`Vencord.Plugins.plugins[${JSON.stringify(t)}]`;return typeof e!="function"?e.replaceAll("$self",o):(...r)=>e(...r).replaceAll("$self",o)}function zc(e,t){if(e.get){let o=e.get;e.get=function(){return t(o.call(this))}}else e.value&&(e.value=t(e.value));return e}function qi(e,t){let o=Object.getOwnPropertyDescriptors(e);o.match=zc(o.match,an),o.replace=zc(o.replace,r=>ha(r,t)),Object.defineProperties(e,o)}var Zr=y(()=>{"use strict";a();l()});var sM,qo,ya=y(()=>{"use strict";a();l();Ze();sM=(e,t,o)=>t,qo=sM});function Sa(e){if(ln!==void 0)throw"no.";return e.push([[Symbol("Vencord")],{},t=>eo=t]),e.pop(),eo?(ln=eo.c,!0):!1}function kn(e,...t){let o=new Error(`webpack.${e} found no module`);Xr.error(o,"Filter:",t)}function yr(e){if(typeof e!="function")throw new Error("Invalid filter. Expected a function got "+typeof e);let t=[];for(let o in ln){let r=ln[o];!r?.exports||(e(r.exports)&&t.push(r.exports),r.exports.default&&e(r.exports.default)&&t.push(r.exports.default))}return t}function kh(...e){let t=ba(...e);return t?eo.m[t]:null}function No(e,t){return Ft(e,t)}function Wc(e,t){return ct(e,t)}function to(e){return Ft(()=>uo(e))}function Ki(...e){let t=uo(Pe.byProps(...e),{isIndirect:!0});return t||kn("findByProps",...e),t}function M(...e){return Ft(()=>Ki(...e))}function Dh(...e){let t=uo(Pe.byCode(...e),{isIndirect:!0});return t||kn("findByCode",...e),t}function Ro(...e){return Ft(()=>Dh(...e))}function Lh(e){let t=uo(Pe.byStoreName(e),{isIndirect:!0});return t||kn("findStore",e),t}function Ie(e){return Ft(()=>Lh(e))}function qc(...e){let t=uo(Pe.componentByCode(...e),{isIndirect:!0});return t||kn("findComponentByCode",...e),t}function Kc(e){return ct(()=>{let t=uo(e,{isIndirect:!0});return t||kn("findComponent",e),t})}function We(...e){return ct(()=>{let t=uo(Pe.componentByCode(...e),{isIndirect:!0});return t||kn("findComponentByCode",...e),t})}function cn(...e){return ct(()=>{let t=uo(Pe.byProps(...e),{isIndirect:!0});return t||kn("findExportedComponent",...e),t[e[0]]})}async function Eh(e,t=/\.el\("(.+?)"\)(?<=(\i)\.el.+?)\.then\(\2\.bind\(\2,"\1"\)\)/){let o=kh(...e);if(!o){let s=new Error("extractAndLoadChunks: Couldn't find module factory");Xr.warn(s,"Code:",e,"Matcher:",t);return}let r=o.toString().match(an(t));if(!r){let s=new Error("extractAndLoadChunks: Couldn't find entry point id in module factory code");Xr.warn(s,"Code:",e,"Matcher:",t);return}let[,i]=r;if(!i||!Number(i)){let s=new Error("extractAndLoadChunks: Matcher didn't return a capturing group with the entry point, or the entry point returned wasn't a number");Xr.warn(s,"Code:",e,"Matcher:",t);return}return await eo.el(i),eo(i)}function Ta(e,t=/\.el\("(.+?)"\)(?<=(\i)\.el.+?)\.then\(\2\.bind\(\2,"\1"\)\)/){return()=>Eh(e,t)}function yt(e,t,{isIndirect:o=!1}={}){if(typeof e=="string")e=Pe.byProps(e);else if(Array.isArray(e))e=Pe.byProps(...e);else if(typeof e!="function")throw new Error("filter must be a string, string[] or function, got "+typeof e);let[r,i]=uo(e,{isIndirect:!0,isWaitFor:!0});if(r)return void t(r,i);Rh.set(e,t)}function lM(e){jc.add(e)}function cM(e){jc.delete(e)}function Yc(...e){let t={},o=eo.m;e:for(let r in o){let i=o[r].original??o[r],s=i.toString();for(let c of e)if(typeof c=="string"&&!s.includes(c)||c instanceof RegExp&&!c.test(s))continue e;t[r]=i}return t}function xa(e){let t=eo.m[e];if(!t)return null;let o=`
// [EXTRACTED] WebpackModule${e}
// WARNING: This module was extracted to be more easily readable.
//          This module is NOT ACTUALLY USED! This means putting breakpoints will have NO EFFECT!!```

i think it was composed like it so you can find yourself in the code?
![image](https://github.com/Vendicated/Vencord/assets/78019378/053975a2-953f-4dc0-b213-b1a4209ffce4)
sorry if i cause you stress over it, i just wanted to make sure thing works on my browser - i fail to see better so far, but remain optimistic 

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Curve** [comment]
Please use Code-Blocks to make this more readable:

<pre>
```
... the code
```
</pre>

**Comment by SCARaw** [comment]
did that, does not seems like it gave expected result

**Comment by Vendicated** [comment]
either script corrupt (redownload) or you're using an ancient browser (update)
