### ISSUE TITLE
[Feature Request] Support for Kick.com in the CustomRCP plugin

### ISSUE THREAD

**Issue by allegedlegend** [Vendicated/Vencord#2139]
### Content

Just curious if it would be possible for the Vencord team to add the ability to enter a Kick.com URL in the CustomRCP Plugin? It currently allows for Twitch.tv and YouTube.com URLs, but will not allow for Kick.com. Thanks so much for your consideration.

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
not possible, discord limitation
