### ISSUE TITLE
[Bug] RelationshipNotifier shows no longer in server notification incorrectly

### ISSUE THREAD

**Issue by moxie-coder** [Vendicated/Vencord#2148]
### Discord Account

moxiethespecialist

### What happens when the bug or crash occurs?

![image](https://github.com/Vendicated/Vencord/assets/124418090/a944d17b-0596-4bbd-ae68-ba011a755005)
There was an outage at the time and one server became unavailable. However...
![image](https://github.com/Vendicated/Vencord/assets/124418090/a6d3e6ed-4644-4ab5-9d0e-46d43c3f4dcf)
This shows up, which isn't right since I never left that server in question, so I thought I'd bring this up since it shouldn't show up during an outage.

(P.S: Not sure if I'm allowed to make an issue but I'm guessing I can since I contributed to the repo, and vencord in general. Also I'm sponsoring because I love vencord <3)

### What is the expected behaviour?

For it to not show up during an outage.

### How do you recreate this bug or crash?

None, random outage happened, I'm not sure how to recreate it.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by moxie-coder** [comment]
> i think thats not possible to avoid

probably, due to discords api stuff

**Comment by Vendicated** [comment]
it is possible to avoid, we just need to fix the code

**Comment by Vendicated** [comment]
should be fixed

**Comment by moxie-coder** [comment]
> should be fixed

nice
