### ISSUE TITLE
[Bug] Calls sound cutting

### ISSUE THREAD

**Issue by Rotwo** [Vendicated/Vencord#2162]
### Discord Account

.rotwo

### What happens when the bug or crash occurs?

When I'm on a call, I can hear the other people but the sound cuts / pops all the time.
Also the other people hear me cutted.

### What is the expected behaviour?

The sound starts to fail whenever you enter a call.

### How do you recreate this bug or crash?

1. Update Vencord to the last version
2. Enter a call in a VC of a server
3. Talk or hear the other people

### Errors

```
There is not any error.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
not a vencord issue

**Comment by Rotwo** [comment]
> not a vencord issue. vencord doesn't even touch calls
I think it's a vencord issue bc I uninstalled Vencord and the problem disappeared, but sorry if I'm not right.
