### ISSUE TITLE
[Bug] The ShowMeYourName and PlatformIndicators plugin together cause unexpected behavior

### ISSUE THREAD

**Issue by CuriousCodingCanadian** [Vendicated/Vencord#2163]
### Discord Account

ees4.

### What happens when the bug or crash occurs?

When using the PlatformIndicators and ShowMeYourName plugin, it displays 3 dots next to people's usernames and display names (on people's messages and in their profiles), even when there is enough space to display them.

### What is the expected behaviour?

The expected behavior is for the full username/display name to be shown when there is enough space to do so.

### How do you recreate this bug or crash?

1. Enable the PlatformIndicators and ShowMeYourName plugins
2. Look at people's profiles or their messages. You will see the first letter of their display/user name, and then 3 dots. persists after reloads and window resizes.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by MrDiamondDog** [comment]
You have streamer mode on.

**Comment by CuriousCodingCanadian** [comment]
Oh.
