### ISSUE TITLE
[FEATURE REQUEST] Add a toggle to customrpc plugin

### ISSUE THREAD

**Issue by starstriker0** [Vendicated/Vencord#2168]
### Content

 i am someone who likes to change rich presence and switch from custom to the games that it detects, and i often see it not displaying the one i want, so it would be nice to have a button possibly next to the profile on the home screen to pull up a menu that could configure the rich presence, and a switch to toggle it on and off, im sorry if this sounds stupid, but its just an idea i had while configuring the plugin

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
just turn the plugin off

**Comment by ha-rt** [comment]
I support this, but I would like to add a recommendation. Instead of a new plugin, possibly add a toggle below the activity on the users profile?

**Comment by Vendicated** [comment]
turn the plugin off or use game activity toggle plugin
