### ISSUE TITLE
Vencord may be blocked due to hardened user.js Firefox

### ISSUE THREAD

**Issue by nopeless** [Vendicated/Vencord#2195]
### Content

Related query string: `VencordNative is not defined`

If you are like me and totally forgot that you installed that one hardened user.js script and a few days later didn't make the connection why Vencord wasn't loading this is the issue.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Mm2PL** [comment]
Do you know which options cause this to happen? I can replicate this even on a profile without special about:config/user.js modifications done.

**Comment by nopeless** [comment]
@Mm2PL no. honestly i don't even remember which user.js i got. and later im figuring out even more issues. in short, i had some issues with custom user.js, and resetting that made vencord work again. meaning that it might be the souce of an issue, but that doesn't mean there are others.
