### ISSUE TITLE
[Bug] Spotify Listen along does not work with Vencord active

### ISSUE THREAD

**Issue by SteffenCarlsen** [Vendicated/Vencord#2244]
### Discord Account

taf1337

### What happens when the bug or crash occurs?

The listen along session never starts. It's basically a "spinner" that goes on forever but never syncs. This is without any plugins related to spotify enabled as well. Reproducable with the Spotify plugin enabled too.

I removed Vencord to ensure something wasen't broken on Discord's side and it worked as expected.

### What is the expected behaviour?

I can listen along to someone else/invite someone else to listen along to my spotify.

### How do you recreate this bug or crash?

1. Find someone to listen with.
2. CLick the "+" sign in the chat
3. Click "Invite @User to Listen to Spotify"
4. Click "Send invite"
5. User joins the listen along

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Sqaaakoi** [comment]
.
![search results for "listen" in support](https://github.com/Vendicated/Vencord/assets/37475903/f0d2ac13-073b-4fe8-bee6-e7e3f5e1523a)
