### ISSUE TITLE
[Bug] ShowHiddenChannels is NOT working properly!

### ISSUE THREAD

**Issue by Niqutincho** [Vendicated/Vencord#2294]
### Discord Account

.niqui

### What happens when the bug or crash occurs?

This bug happens on a few servers, and in some others it doesnt, but basically when you try to see users with permission to certain hidden channel, they wont appear correctly. 
For example on a ticket on certain server, which is hidden, you cant see whos the person with access to the ticket, but in other server you can.

### What is the expected behaviour?

I expect ShowHiddenChannels to show everyone who has perms to see/talk in the ticket correctly in every server and not just a few.

I will attach images of how it looks in a server (where it is not working properly) and how it works in another server (where it is working properly and showing every member with access to the channel)

1- https://ibb.co/VD80SgF (this is how it looks like and doesnt show all members with access)
2- https://ibb.co/MDpNMpk (this is how it looks on another server where it actually shows the full info of people with access to it)

### How do you recreate this bug or crash?

1- Join this server https://discord.gg/s4KgPQa4 (I am giving this one cause this is the one where the bug occurs, but might be happening with a lot more)
2- Scroll to see all the opened tickets which are shown by the plugin
3- Click on any of those, you will see you cant see whos the person with access to the channel, just the owner, the ticket bot and some roles but not the person who created it and has actual access to the ticket, but you can do that in other servers.

### Errors

```
Replace this text with your crash-log.
```
No crashes.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Scyye** [comment]
the server where you cant see the users with access to the ticket- what is the ticket bot they use?

**Comment by Niqutincho** [comment]
> the server where you cant see the users with access to the ticket- what is the ticket bot they use?

Ticket Tool#4843

**Comment by Niqutincho** [comment]
> the server where you cant see the users with access to the ticket- what is the ticket bot they use?

![image](https://github.com/Vendicated/Vencord/assets/69437725/0d1ef0bc-b3a0-47a3-be11-7ee5b44f04f2)

Ticket Tool#4843

right there I uploaded a new screenshot.

**Comment by Scyye** [comment]
and youre sure the users the tickets are with, are still in the server?

**Comment by Niqutincho** [comment]
> and youre sure the users the tickets are with, are still in the server?

mhm im 100% sure lol

**Comment by Scyye** [comment]
the screenshot you provided shows that its working completely fine.
![image](https://github.com/Vendicated/Vencord/assets/97131358/013b9a5b-8860-4462-825b-d53f52e868a9)

**Comment by Niqutincho** [comment]
> the screenshot you provided shows that its working completely fine. ![image](https://private-user-images.githubusercontent.com/97131358/343869440-013b9a5b-8860-4462-825b-d53f52e868a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDcxMTYsIm5iZiI6MTcxOTUwNjgxNiwicGF0aCI6Ii85NzEzMTM1OC8zNDM4Njk0NDAtMDEzYjlhNWItODg2MC00NDYyLTgyNWItZDUzZjUyZTg2OGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE2NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YjJhNjhmOWRlM2U5ZTk1NmE0YmI3NzBjZDdkMDg4NDZlNmUzY2Q3ZGM2NGQzOGUwY2ZlOWJkNDc1YWVhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mVjkflnjIxKK7YgwBj4O_61LYQk4d6Syf-qO82H63Go)

That person right there is literally showing Ticket Tool and that user, zfrosty, who is the server owner. It shows the Owner and the Bot but not the member who created the ticket, which shows correctly in other servers.
![image](https://github.com/Vendicated/Vencord/assets/69437725/32adba4e-0752-419d-a91a-fe48f91a22e3)
 Here is an example of how it SHOULD look like . That server uses Tickets#6981 bot, and is showing the server owner, the bot, and the member who created the ticket ( the guy named Will Smith )

**Comment by Scyye** [comment]
oh, so this is a misunderstanding with how the bot works.

Closed tickets, are, well closed. and so only staff have access to them.

its 100% accurate in what its showing you.

**Comment by Niqutincho** [comment]
> oh, so this is a misunderstanding with how the bot works.
> 
> Closed tickets, are, well closed. and so only staff have access to them.
> 
> its 100% accurate in what its showing you.

No, it was just an example, it happens with opened tickets as well.
Here is an opened ticket in that server so you see it doesnt show the member either.
![image](https://github.com/Vendicated/Vencord/assets/69437725/52b025a3-92d7-4cd2-b1c0-dc13959614b7)

join the server and check yourself if you want

**Comment by Scyye** [comment]
advertising a cheat development server on a vencord bug report is crazy ✨

**Comment by Niqutincho** [comment]
> advertising a cheat development server on a vencord bug report is crazy ✨

??
I was just showing you the server. It is not a cheating server anymore as it is discontinued.
