### ISSUE TITLE
[Bug] Transparent window prevents hideable taskbar from showing.

### ISSUE THREAD

**Issue by RabbyDevs** [Vendicated/Vencord#2301]
### Discord Account

rabbydevs

### What happens when the bug or crash occurs?

When "Automatically Hide Taskbar" is enabled on windows, and the transparent window setting is enabled, unexpected behavior occurs.

### What is the expected behaviour?

Taskbar unhides properly when mouse moves to the bottom of the screen.

### How do you recreate this bug or crash?

1. Enable "Automatically hide taskbar"
2. Enable transparent window.
3. Move mouse up from the bottom of the screen to hide it.
4. Move it back down. It should unhide when you do this.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
such things are provided by electron / chromium. we have no control over it
