### ISSUE TITLE
[Bug] themes don't work

### ISSUE THREAD

**Issue by KrutoySigma** [Vendicated/Vencord#2308]
### Discord Account

swewzeex

### What happens when the bug or crash occurs?

themes don't work

### What is the expected behaviour?

themes don't work

### How do you recreate this bug or crash?

themes don't work

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Gentleman2292** [comment]
same issue here

**Comment by pandystar123** [comment]
yep same here

**Comment by schoeneBiene** [comment]
https://discord.com/channels/1015060230222131221/1024351821873037462/1222749727083462686

**Comment by AftmostSeeker80** [comment]
![Screenshot_2024-03-28-10-11-27-218-edit_dev.beefers.vendetta.jpg](https://github.com/Vendicated/Vencord/assets/55350217/ffcac5ca-983d-4d67-b093-bd958325c582)

Since you won't bother reading the linked message above, have a screenshot
