### ISSUE TITLE
[Bug] <Always animate isn't working>

### ISSUE THREAD

**Issue by ZverolovZ** [Vendicated/Vencord#2311]
### Discord Account

zverolovz

### What happens when the bug or crash occurs?

Always Animate is on but it isn't animate. It's on 

### What is the expected behaviour?

I'm expecting that it'll animate 
![chrome_EwqweVLWZq](https://github.com/Vendicated/Vencord/assets/165322819/72dfdc08-ed06-4db2-89f3-01fa07fc6c16)
![Discord_pFyZJU7wrX](https://github.com/Vendicated/Vencord/assets/165322819/c8f63c3b-4c96-4f58-8a62-dd1e96fc1d2e)

### How do you recreate this bug or crash?

Turn on plugin Always animate and look how it'll not animate anything

### Errors

Looks like i have got no errors with always animate

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
works fine for me. update vencord or use support channel if it doesnt work
