### ISSUE TITLE
Crashing when opening someones stream

### ISSUE THREAD

**Issue by BudImCanadian** [Vendicated/Vencord#2312]
### Discord Account

deepinyahmum

### What happens when the bug or crash occurs?

Every time I open someone's stream. Full crashes discord. If I stream and open someone else's stream, it will work. But if I click anywhere outside of discord, it will crash again. 

### What is the expected behaviour?

To be able to not crash

### How do you recreate this bug or crash?

Have a friend stream their game
Open said friends stream.

### Errors

none

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
try if this also happens on stock discord without vencord. it is very unlikely to be related to vencord

also your error log contained your spotify token so you should change your spotify password and remove and readd spotify to your discord

**Comment by BudImCanadian** [comment]
Weird. I fully re-installed discord, and it does appear to be doing the same thing unrelated to vencord. Could anyone confirm if they are also experiencing this?

**Comment by Durango-alt** [comment]
> Weird. I fully re-installed discord, and it does appear to be doing the same thing unrelated to vencord. Could anyone confirm if they are also experiencing this?

got the same problem, unistalled vencord, problem solved

**Comment by masteri212** [comment]
What fixed it for me was turning hardware acceleration off.
