### ISSUE TITLE
[Bug] Many plugins in version 650f405 are BROKEN

### ISSUE THREAD

**Issue by Tsaitou7361** [Vendicated/Vencord#2315]
### Discord Account

tsaitou7361

### What happens when the bug or crash occurs?

Many plugins in version 650f405 are BROKEN

### What is the expected behaviour?

Any plugins won't work

### How do you recreate this bug or crash?

1. Update to 650f405
2. And boom!

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Dziurwa14** [comment]
discord update, just wait, stop complaining

**Comment by Tsaitou7361** [comment]
Okay
