### ISSUE TITLE
[Bug] PinDMs: alt up/down doesn't work correctly when using recent message sort order

### ISSUE THREAD

**Issue by Vendicated** [Vendicated/Vencord#2322]
### What happens when the bug or crash occurs?

It just doesn't navigate in the correct order

### What is the expected behaviour?

It should have the correct order

### How do you recreate this bug or crash?

1. Set sort order to recent message
2. Pin a few dms
3. Have bottom pin message you so it goes to top
4. Try using keyboard navigation
5. Observe that it doesn't behave correctly

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
cc @Syncx but i might also fix it soon

**Comment by Vendicated** [comment]
cc @Syncxv but i might also fix it soon

**Comment by puppy-girl** [comment]
When collapsing a category with the last message sort order the channel that's left open won't be the channel you have open. It seems to find the position of the current channel based on its position in custom sorting order: if the currently open channel were at the top of the list in last message sort but at the bottom of the list in custom sort it'll leave open the channel currently at the bottom of the list instead.

**Comment by Nuckyz** [comment]
Fixed in #2324
