### ISSUE TITLE
[Bug] Volume Booster: Volume only goes to 200%, 201-400% automtically reset.

### ISSUE THREAD

**Issue by wlxxd** [Vendicated/Vencord#2325]
### Discord Account

! wlxd

### What happens when the bug or crash occurs?

If you try to update the stream volume to 201-400% it automatically gets reset to 200% every time.

### What is the expected behaviour?

The Volume should stay the same.

### How do you recreate this bug or crash?

1. Open Discord
2. Go in a Voice Chat
3. Try to change the volume to 201-400%.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Tr0llie** [comment]
this is a really weird thing that is happening to me lately... im pretty sure that is client side and not a server side issue as the volume boost works from client side.

**Comment by Vendicated** [comment]
can't reproduce
