### ISSUE TITLE
[Bug] can't decrypt messages

### ISSUE THREAD

**Issue by Milkpooch** [Vendicated/Vencord#2334]
### Discord Account

i_m_r_a_n

### What happens when the bug or crash occurs?

When a friend of me send a crypted message, i can see the lock logo sayign theres a cypted message, when i try to click on the "decrypt message" button nothing happens?

### What is the expected behaviour?

normally theres a little screen asking to put a password to decrypt the message but it doesn't seem to show up?

### How do you recreate this bug or crash?

1. ask someone to encrypt a message
2. try decrypting the encrypted message he sent with the password

### Errors

Uncaught (in promise) Error: Invisible stream not detected! Please copy and paste the StegCloak text sent by the sender.
    at detach (index.js:19:35306)
    at index.js:8:50194
    at index.js:8:50194
    at index.js:8:37453
    at t.exports.reveal (index.js:8:146852)
    at ef (index.tsx:202:30)
    at VN (index.tsx:221:24)
    at onClick (index.tsx:133:31)
    at onClick (WebpackModule773176:2:1741)
    at Object.eB (58661.cbedde580b7529f6272e.js:12:853927)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by waresnew** [comment]
It works for me

Can you send the encrypted text?
