### ISSUE TITLE
[Bug] Trojan detected by windows defender in VencordInstallerCli.exe

### ISSUE THREAD

**Issue by Chaython** [Vendicated/Vencord#2340]
### What happens when the bug or crash occurs?

Using git bash to inject vencord into discord, it's blocked by windows defender 
![image](https://github.com/Vendicated/Vencord/assets/6486343/40e9c4ab-68d1-424a-b542-512ff050f810)
https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Znyonm&threatid=2147890445

### What is the expected behaviour?

Inject vencord

### How do you recreate this bug or crash?

1. $ pnpm inject
2. file: C:\Users\Chay\Vencord\dist\Installer\VencordInstallerCli.exe detected as trojan

### Errors

```
$ pnpm inject

> vencord@1.7.4 inject C:\Users\Chay\Vencord
> node scripts/runInstaller.mjs

Downloading VencordInstallerCli.exe
Finished downloading!
Now running Installer...
Something went wrong. Please check the logs above.

```
"0x8DC355D65086932" - in C:\Users\Chay\Vencord\dist\Installer\etag

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
false positive just exempt it

**Comment by Chaython** [comment]
> false positive just exempt it
As I am compiling the source code, why not compile the injector locally too, this should remove any false positives...
As it shares a sha256 I assume somewhere in the injection code it's just downloading it...

**Comment by Vendicated** [comment]
what?

**Comment by Vendicated** [comment]
it downloads the cli installer binary from https://github.com/Vencord/Installer. this is exactly the same as the gui you normally install with, just as a cli instead.

compiling it from source requires go installed and takes some time, so no this is not an option.

just whitelist it in defender
