### ISSUE TITLE
[Bug] <title> I HAVE INSTALLED EVERY THING I NEED TO FOR THE BROWSER VERSION

### ISSUE THREAD

**Issue by NotChumps** [Vendicated/Vencord#2368]
### Discord Account

justaguy.247

### What happens when the bug or crash occurs?

look at the screenshots for context 
![Screen Shot 2024-04-19 at 12 23 59 PM](https://github.com/Vendicated/Vencord/assets/167559472/c2edc992-57d5-4076-92fd-75d82dc1da73)
![Screen Shot 2024-04-19 at 12 24 03 PM](https://github.com/Vendicated/Vencord/assets/167559472/ce30dbb3-729d-4646-9a63-42c926b037a5)

### What is the expected behaviour?

I expect that vencord patches this so I can use it and I am not mad I am just confused

### How do you recreate this bug or crash?

1. have all the vencord browser extenches and
2. download all the sofware (For The BROWSER VERSION NOT THE APPLICATION )
3. (BE ON GOOGLE)
4. and then go to the vencord page part is setting 
5. go to plugins
6. and themes

### Errors

```
i do not know how to get the crash log
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
use our support channel for support

**Comment by NotChumps** [comment]
> use our support channel for support

o ok sorry i did not know and it was just an issue so i thought that was were i put it
