### ISSUE TITLE
[Bug] Vencord is not working whien switching to another account

### ISSUE THREAD

**Issue by MNDL-27** [Vendicated/Vencord#2374]
### Discord Account

mndl27

### What happens when the bug or crash occurs?

SO i switched to my secondary account its there is no option for Vencord it feels like it was not even installed the I switched to the main account if Vencord is installed it is there but not on my other account

### What is the expected behaviour?

I expect it to work when switching account 
![image](https://github.com/Vendicated/Vencord/assets/96876555/25331d47-7f63-44c8-a9b6-1b68bb3e3dc2)

### How do you recreate this bug or crash?

switch account

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Tr0llie** [comment]
it is an expected behavior (iirc), settings only sync when it's the same account.

**Comment by Vendicated** [comment]
use our support channel
