### ISSUE TITLE
[Bug] MemberCount showing 0 online members while viewing threads

### ISSUE THREAD

**Issue by FairwellNoob** [Vendicated/Vencord#2379]
### Discord Account

fairwellnoob

### What happens when the bug or crash occurs?

The members online in the channel is 0

### What is the expected behaviour?

The members online in the channel should be listed correctly (in this case, it should be 5 online)

### How do you recreate this bug or crash?

I have honestly no idea. Some servers have this, some don't. I've tried creating a forum channel in my own server while it was community, disabling community, going back into the forum channel, and now it's working. But when I go to another server, all of a sudden it doesn't work anymore.
![Screenshot_2](https://github.com/Vendicated/Vencord/assets/79961729/8699786e-2f71-4550-9e04-eed297dc8236)
![Screenshot_1](https://github.com/Vendicated/Vencord/assets/79961729/44b09704-15f5-4710-a881-ac1678dc2c16)

### Errors

[discord.com-1713874622997.log](https://github.com/Vendicated/Vencord/files/15076677/discord.com-1713874622997.log)
[discord.com-1713874619273.log](https://github.com/Vendicated/Vencord/files/15076680/discord.com-1713874619273.log)
[discord.com-1713874616051.log](https://github.com/Vendicated/Vencord/files/15076681/discord.com-1713874616051.log)
[discord.com-1713874612258.log](https://github.com/Vendicated/Vencord/files/15076682/discord.com-1713874612258.log)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Tr0llie** [comment]
repair ur vencord via the installer, also u should ask this in support channel. This bug often happens if your discord is outdated, (iirc) but im not entirely sure since it happens to me **only** when discord is outdated. If you are in the latest version of discord and it still happens then try asking in support, if they ask u to come here again then u probably just have to wait until someone who knows better than me (almost everyone) respond to this thread.

**Comment by Tr0llie** [comment]
> repair ur vencord via the installer, also u should ask this in support channel. This bug often happens if your discord is outdated, (iirc) but im not entirely sure since it happens to me **only** when discord is outdated. If you are in the latest version of discord and it still happens then try asking in support, if they ask u to come here again then u probably just have to wait until someone who knows better than me (almost everyone) respond to this thread.

Just because i update my discord to fix this issues doesn't mean it will always fix your issue.

**Comment by FairwellNoob** [comment]
> repair ur vencord via the installer, also u should ask this in support channel. This bug often happens if your discord is outdated, (iirc) but im not entirely sure since it happens to me **only** when discord is outdated. If you are in the latest version of discord and it still happens then try asking in support, if they ask u to come here again then u probably just have to wait until someone who knows better than me (almost everyone) respond to this thread.

I was using Vesktop, and there was no notification asking me to update.

**Comment by Vendicated** [comment]
it doesn't support threads iirc

**Comment by Tr0llie** [comment]
> it doesn't support threads iirc

i just noticed that it was a thread lol

**Comment by Huderon** [comment]
This should be fairly simple to add now, I think. It used to be that the thread member count was lazyloaded, or capped at 50 or something, but you can just grab it like this now `Vencord.Webpack.findStore("ThreadMemberListStore").getMemberListSections(Vencord.Webpack.findStore("SelectedChannelStore").getCurrentlySelectedChannelId())`. If you make it a feature request it'd probably be a good first issue

**Comment by electricsteve** [comment]
Hey shouldn't this issue be closed?
