### ISSUE TITLE
[Bug] <title>3y3 button not appearing 

### ISSUE THREAD

**Issue by PassLoad** [Vendicated/Vencord#2394]
### Discord Account

kyotosoul

### What happens when the bug or crash occurs?

the 3y3 button doesnt appear when you try to change your profil theme i have disadled and enable the plugin mulitple times but the issue is still there please fix this bug

### What is the expected behaviour?

3y3 button not showing

### How do you recreate this bug or crash?

i dont know

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by HAHALOSAH** [comment]
sounds like a Discord web user

**Comment by Tr0llie** [comment]
> sounds like a Discord web user

it happens sometime on canary also, usually i would just refresh discord or repair but idk whats his issue..
I use web most of the time and for me i've never seen it dissaper... I feel like this guy should go to support channel first

**Comment by Vendicated** [comment]
works for me and this issue contains no relevant info (e.g. error logs) so there's nothing we can do

if you're still experiencing this issue, use our support channel
