### ISSUE TITLE
[Bug] ValidUser - Display bug

### ISSUE THREAD

**Issue by Soulivan71** [Vendicated/Vencord#2411]
### Discord Account

soulivan71

### What happens when the bug or crash occurs?

When Im typing <@165533461241653403> in message bar its displaying unknown user but when I send it its not displaying as unknown user (in dm too)
![image](https://github.com/Vendicated/Vencord/assets/36502190/308fc315-1acf-49a8-aeb2-a0e38ca481b4)

### What is the expected behaviour?

Display bug

### How do you recreate this bug or crash?

Write an userid
Send message

### Errors

Im using >
canary 290415 (c496312) Host 1.0.340 x64 (47455) Windows 10 64-bit (10.0.19045)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
so what's supposed to be the bug here?

**Comment by Soulivan71** [comment]
Should display the user no ?

**Comment by Vendicated** [comment]
it fetches & displays the user when you hover the mention. there's nothing out of the ordinary here
