### ISSUE TITLE
Question about some mods

### ISSUE THREAD

**Issue by marss72** [Vendicated/Vencord#2419]
### Content

I want to use Vencord. But there's one small problem. My friend and I tested the FakeNitro plugin and it actually streams in Nitro quality, so it's not only client side, so how does it work? That's one of the reasons I want to use Vencord. Also, I've heard that Message Logger is bannable on Better Discord. Is it the same on Vencord, or are the messages stored entirely client-side so that I cannot get banned for it?

Also, can I view the source code of some plugins that are not entirely client-side? Thanks.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
all plugins are safe. read the [faq](https://vencord.dev/faq)

> Also, I've heard that Message Logger is bannable on Better Discord

misinformation spread by people wanting to scare you into not using the plugin

> can I view the source code of some plugins

https://github.com/Vendicated/Vencord/tree/main/src/plugins

**Comment by Sqaaakoi** [comment]
> My friend and I tested the FakeNitro plugin and it actually streams in Nitro quality, so it's not only client side, so how does it work? 

discord just doesn't check on the server side for stream quality. they do check for bitrate afaik

> Is it the same on Vencord, or are the messages stored entirely client-side so that I cannot get banned for it?

MessageLogger does not actually "save" messages by design
