### ISSUE TITLE
Game Activity Toggler doesn't work

### ISSUE THREAD

**Issue by Katerang31** [Vendicated/Vencord#2423]
### Content

it's not working as u can see it shows that i'm listening to Spotify and my brother can see it too on his account
and when i click on it there's no screen sharing sound
![image](https://github.com/Vendicated/Vencord/assets/78563324/766753b8-edbc-4de2-b4f4-7d092e0d9877)

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by Katerang31** [comment]
Ok it works but not for spotify
it's not showing that i'm playing cs2 or other games
but spotify mmmmmmmm

**Comment by CatGirlDShadow** [comment]
> Ok it works but not for spotify it's not showing that i'm playing cs2 or other games but spotify mmmmmmmm

Spotify inegration nas separate toggle on Settings>Integrations>Spotify where you can disable spotify being shown
