### ISSUE TITLE
[Bug] Crash when streaming on Vesktop using Linux Mint

### ISSUE THREAD

**Issue by MattheDev53** [Vendicated/Vencord#2434]
### Discord Account

@magicmangames53812

### What happens when the bug or crash occurs?

When trying to stream an application or monitor, the client soft locks after selecting the application or monitor, hanging at "Loading audio Sources...". voice chatting is still possible and the client still animates everything properly, but no longer responds to user input. the desktop environment eventually reports that Vesktop is no longer responding.

### What is the expected behaviour?

For Audio sources to load and to be able to stream

### How do you recreate this bug or crash?

1. Join voice Channel
2. Click Share your Screen Button
3. Click on a window/screen
4. Client softlocks

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
wrong repo

**Comment by MattheDev53** [comment]
Oh, sorry.
