### ISSUE TITLE
[Bug] FakeNitro notifies of missing permission with native emojis

### ISSUE THREAD

**Issue by pwall2222** [Vendicated/Vencord#2470]
### What happens when the bug or crash occurs?

If you use a Discord emoji like \\:sob: in a channel, where you have no permissions for embeds, the "missing permissions" pop-up appears.

### What is the expected behaviour?

That the preflight pop-up didn't show up and the message sent.

### How do you recreate this bug or crash?

- Have FakeNitro enabled
- Be in a channel where you have no embeds permission
- Use a Discord native emoji (like \\:sob:)

### File

I went digging for the file where this occurred and it was probably in the [canSendEmoji function](https://github.com/Vendicated/Vencord/blob/f74da73086b2b361490e028c999c80b3ac2ba76a/src/plugins/fakeNitro/index.tsx#L812), I don't know how to patch it because I am not acostumed to the API and I don't know how to setup a developer environment.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Nuckyz** [comment]
Fixed in https://github.com/Vendicated/Vencord/commit/6547cc10f7f515652de6513326342ea3e87535ba
