### ISSUE TITLE
Discord unloading when in background

### ISSUE THREAD

**Issue by Vendicated** [Vendicated/Vencord#2478]
### Content

When Discord is in the background for a prolonged period of time, it sometimes unloads. When you come back, it takes a few seconds to "re-connect" and fetch new messages. Supposedly it also disconnects you from voice when this happens

There are [many reports of this happening on stock Discord](https://www.reddit.com/r/discordapp/comments/1buyl5o/comment/l1l6nc8/) but according to some other people, it only happens with Vencord.

The following needs to be investigated:
- I think if Vencord is causing, it's most likely DisableCallIdle. Does disabling this plugin fix it / enabling this plugin cause it?
- Does running Discord/Vesktop with `--disable-renderer-backgrounding` fix it?
- Does setting `backgroundThrottling: false` in the electron BrowserWindow options fix it?

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
It does seem to be the DisableCallIdle plugin. If you have this issue, check if it's enabled. If yes, try disabling it and see if the issue is fixed (and report back here). If not, post your list of enabled plugins

**Comment by trwy7** [comment]
For me this is only on vesktop, I have had this happen once with vencord, and never with stock

**Comment by Naviamold1** [comment]
It happens to me as well, but I don't use 'DisableCallIdle'. 
Issues really started after updating Discord to their x64 bit version. Also, the 'Discord installed in wrong place' popup pops up in Vencord Installer since installing Vencord on that version.

**Comment by VL4DST3R** [comment]
Been having issues with this for a long time as well. It seems to be random when it happens, but indeed it must be a period of inactivity, happening even while on voice chat. This also causes it to be very hard to realize you're speaking to yourself and have been since disconnected from the call.

**Comment by Cats1337** [comment]
I haven't used the DisableCallIdle plugin but I was having the issue of randomly disconnecting and reconnecting to voicechats. adding `--disable-renderer-backgrounding` to my Target in Properties has fixed it.

**Comment by byeoon** [comment]
Turning off DisableCallidle did not fix the issue, I will try --render thingy soon

**Comment by byeoon** [comment]
I might have found a potential link to this. Unloads were occuring more frequently due to lack of disk space (< 20GB) and after cleaning up my computer it seemed to have stopped. Is it possible that this is a factor?

**Comment by Sqaaakoi** [comment]
> I might have found a potential link to this. Unloads were occuring more frequently due to lack of disk space (< 20GB) and after cleaning up my computer it seemed to have stopped. Is it possible that this is a factor?

almost certainly a coincidence with some workaround added to vencord being implemented around the same time?

**Comment by VL4DST3R** [comment]
> Unloads were occuring more frequently due to lack of disk space (< 20GB)

I'm... also curious of this, as I'm in a similar situation on my main machine (~20-30gb free atm) where I was experiencing issues, but on my laptop with hundreds of gigs of free space it seemed to work a lot more reliably.

Now, like @Sqaaakoi saiid, it sounds too stupid not to be just a coincidence, but the issue itself seems to be not well enough understood, enough to make me consider even stuff like this.

**Comment by Vendicated** [comment]
discord recently added a bunch of command line flags that disable backgrounding

so did vencord
https://github.com/Vendicated/Vencord/commit/a0778f6a2e786889d11f2b627f2ac03f7696c2e5
https://github.com/Vendicated/Vencord/commit/86aabe73eb4987d4fd9a96bc528f891d1998e876

if it was fixed in the past two weeks, that's likely why. i highly doubt free space has anything to do with this

**Comment by VL4DST3R** [comment]
So far for me it seems to no longer silently unload, fingers crossed it stays this way.

**Comment by Koishukaze** [comment]
> it stopped unloading a couple days ago and now its back to it since a new update?

I can also say it has returned back for me

**Comment by Sqaaakoi** [comment]
> > it stopped unloading a couple days ago and now its back to it since a new update?
> 
> I can also say it has returned back for me

I have also noticed my client unloading recently when it is in the background, and it even happens when in voice channels like it used to

**Comment by Vendicated** [comment]
Try again with https://github.com/Vendicated/Vencord/commit/4ec01d0f40a4b1d4ca8fb7fb8a78a23a9ea3055e

**Comment by R00tB33rMan** [comment]
> Try again with latest update ([4ec01d0](https://github.com/Vendicated/Vencord/commit/4ec01d0f40a4b1d4ca8fb7fb8a78a23a9ea3055e))

Hey! I'm still encountering this issue, I'm afraid. I can confirm that it occurs with and without the `DisableCallIdle` feature. I hope this additional feedback helps!
