### ISSUE TITLE
[Bug] FakeNitro incorrectly replacing twitch sub emotes even if you can use them

### ISSUE THREAD

**Issue by Vendicated** [Vendicated/Vencord#2499]
### What happens when the bug or crash occurs?

When using a twitch subscriber emote while being subscribed to the streamer, FakeNitro will still replace it

### What is the expected behaviour?

It should not be replaced

### How do you recreate this bug or crash?

1. Try to use some twitch sub emote that you have access to use
2. Observe that it gets turned into a FakeNitro emote

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Nuckyz** [comment]
This is already fixed
