### ISSUE TITLE
setting/plugin to disable spellcheck on note textfield

### ISSUE THREAD

**Issue by KraXen72** [Vendicated/Vencord#250]
simple regex patch to add a `spellcheck="false"` to note textfield
thanx

**Comment by zachjmurphy** [comment]
@KraXen72 Why would someone need this feature?

**Comment by KraXen72** [comment]
i use the note field to write people's horrible secrets there

**Comment by KraXen72** [comment]
pls just like tell me wheres the note component created ill yeet the spellcheck myself ig
