### ISSUE TITLE
[Bug] Message Logger don't log edits even tho i unchecked and checked back the setting

### ISSUE THREAD

**Issue by Draze999** [Vendicated/Vencord#2500]
### Discord Account

draze999

### What happens when the bug or crash occurs?

When i'm writing a message and editing it after, only the default behavior is there, i don't see any history or logs. Same thing for others's message

### What is the expected behaviour?

When a message is edited, it should log the old message content above

### How do you recreate this bug or crash?

1. Write a message
2. Edit the message
3. Take note.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Draze999** [comment]
![image](https://github.com/Vendicated/Vencord/assets/71888778/b028dacf-ccad-4721-960a-c780a6bd215b)

**Comment by rozbrajaczpoziomow** [comment]
known /shrug

**Comment by Draze999** [comment]
Well, i didn't had the problem until i updated 1 hour ago

**Comment by Vendicated** [comment]
fixed
