### ISSUE TITLE
[Bug] MessageLogger broken when image appended

### ISSUE THREAD

**Issue by jarvis09-yann** [Vendicated/Vencord#2527]
### Discord Account

jarvis09

### What happens when the bug or crash occurs?

This bug occurs when a Discord Bot appends an image to a preexisting message.
Here is an example of code that would cause this type of issue:

```cs
// D#+
DiscordMessage msg = await ctx.RespondAsync("Loading...");

// logic

using (FileStream file = new(screenshotFilePath, FileMode.Open))
{
    DiscordMessageBuilder messageFile = new();
    messageFile.AddFile(file);
    await msg.ModifyAsync(messageFile);
}
```
(This was also tested with Discord.py, if you need more informations about the bot please ask @QAEZZ (the bot's developer)

This bug can be fixed by disabling MessageLogger or reloading the Discord client.

![the problem](https://cdn.nest.rip/uploads/5148b5f2-b798-44e0-a316-2aa0d40dde3a.png)

PS: "(modifié)" just means "(edited)" but in French

### What is the expected behaviour?

I expect the image to be shown after the message is edited.

This image is what is expected to happen:
![what SHOULD work](https://cdn.nest.rip/uploads/1fc7c292-186c-4500-b358-a6be00cd1a8d.png)

### How do you recreate this bug or crash?

1. Enable MessageLogger plugin
2. Send a message using a Discord bot
3. Append an image to that message using same Discord bot
4. The client will not see the image until they reload their Discord client (see 1st image)

### Errors

There is not output to the console whatsoever (that is related to the bug)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by QAEZZ** [comment]
Hello, I am one of the developers of the bot shown.

The MessageLogger plugin doesn't take into account added files after a message is sent; it only reflects the content changed.

I'm not well-versed in JS/TS, but I think [this](https://github.com/Vendicated/Vencord/blob/main/src/plugins/messageLogger/index.tsx#L105) snippet of code is to blame:
```
// plugins/messageLogger/index.tsx

// L105 - L120
    renderEdit(edit: { timestamp: any, content: string; }) {
        return (
            <ErrorBoundary noop>
                <div className="messagelogger-edited">
                    {Parser.parse(edit.content)}
                    <Timestamp
                        timestamp={edit.timestamp}
                        isEdited={true}
                        isInline={false}
                    >
                        <span className={styles.edited}>{" "}({i18n.Messages.MESSAGE_EDITED})</span>
                    </Timestamp>
                </div>
            </ErrorBoundary>
        );
    },

    makeEdit(newMessage: any, oldMessage: any): any {
        return {
            timestamp: new Date(newMessage.edited_timestamp),
            content: oldMessage.content
        };
    },
```

I assume it has something to do with the parser, or some other code not checking if the message attachments were updated after the message is sent.

Here is reproducible code, similar to the snippet in C#, in Discord.py.
```py
msg = await ctx.reply("loading...")
await asyncio.sleep(2)

file = discord.File(path.expanduser("~/Pictures/cat.png"))
await msg.edit(content="_ _")
await msg.add_files(file)
```
I assume (I know, a lot of assumptions :trollface:), that this is what D#+ does in the background. The underscores to bypass the restriction of no empty messages.

**Comment by rushiiMachine** [comment]
i didn't even know you could add files after sending a message

**Comment by reinitd** [comment]
> i didn't even know you could add files after sending a message

Me neither!

**Comment by Vendicated** [comment]
should be fixed via https://github.com/Vendicated/Vencord/commit/319a99c293004d089cf83685c8e70e53d51c3c91
