### ISSUE TITLE
[Bug] ViewIcons Incompatible with Simplified Profile Experiment

### ISSUE THREAD

**Issue by Bloofield** [Vendicated/Vencord#2534]
### Discord Account

Bloofield

### What happens when the bug or crash occurs?

When you've been picked for the new simplified profile experiment (or have enabled it manually), the plugin ceases to function.

### What is the expected behaviour?

When clicking on icons/banners on a users profile, it opens an image modal.

### How do you recreate this bug or crash?

1. Go on an account with the experiment enabled/Enable the experiment through Vencord
2. Open a user profile modal (large)
3. Click on the icon/banner

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Bloofield** [comment]
This may not need to be reported, but I thought I might as well report it in case the plugin dev wants to port the plugin over to the new experiment.

**Comment by Sqaaakoi** [comment]
For a while I've considered taking action to try porting plugins to the new simplified profile; this will help a lot

**Comment by Sqaaakoi** [comment]
@AutumnVN opened a PR to fix this see #2535
