### ISSUE TITLE
Nitro Bug

### ISSUE THREAD

**Issue by thanhcodervietnam** [Vendicated/Vencord#2538]
### Discord Account

thanh_coder_vietnam

### What happens when the bug or crash occurs?

when I put an emoji in my profile and hit "Save changes". But the "Save changes" line keeps repeating and never saves to my profile

https://streamable.com/47berv

### What is the expected behaviour?

I hope Vencord can fix that (that's all)

### How do you recreate this bug or crash?

­

### Errors

­

### Request Agreement

- [ ] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
you need nitro
