### ISSUE TITLE
I need technical help, freeze the game when minimizing the window, provided that I log in to the voice chat in the discord

### ISSUE THREAD

**Issue by Gxtod** [Vendicated/Vencord#2541]
### Content

The problem is related to the **sound drivers**, apparently something in the game is blocking the sound driver from my headphones, Here are 3 topics with similar problems:
https://www.reddit.com/r/discordapp/comments/khwz6z/having_problems_with_discord_and_snowrunner_help/?rdt=39033
and:
https://www.reddit.com/r/snowrunner/comments/gc966r/game_freezes_when_alttab/
and:
https://www.playground.ru/snowrunner/forum/zavisanie_igry_pri_alt_tab-1678654

This problem is somehow related to the configuration of the audio equipment in the system, my headset and headphones are XIBERIA, apparently the game somehow affects the virtual **audio driver**

I strongly ask you to solve this problem, it was tested on 2 systems, in both cases there are long lags and slowdowns, provided that a VOICE chat is open in the discord

The system:

AMD Ryzen 7 5700G AM4
Sapphire Nitro+ Radeon RX 5700 XT 8GB
16 GB DDR4 4000 Mhz CL19
Audio headset - Xiberia K3 (Hi-Fi 7.1) USB
Windows 11 2023 - 23H2 - Corporative

AMD Ryzen 7 5700G AM4
Yeston Radeon RX 6800 16 ГБ (not XT version)
32 GB DDR4 3600 Mhz CL14
Audio headset - Oklick HS-L950G Cobra (7.1) USB
Windows 11 Insider Dev Build 26080.1201 (KB5037135) 24H2 - March 15 - LAST UPDATE

this problem is definitely not due to problems with the Windows operating system. The problem is sewn up somewhere at the audio driver level while using voice chat in the discord and the game at the same time. I'm asking for help.

https://steamcommunity.com/app/1465360/discussions/0/7204143093502663926/

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by programminglaboratorys** [comment]
sounds like a discord issue, in vencord we don't deal with discord problems

**Comment by lewisakura** [comment]
We do not modify Discord natives (where voice chats take place) and Vencord wouldn't cause such an issue, and we aren't Discord support.

Plus, this is a direct copy/paste from that Steam discussion, where it was already answered that you need to contact the audio driver company.
