### ISSUE TITLE
i am banned in the vencord discord server without a warning and without breaking rules

### ISSUE THREAD

**Issue by jojommeke** [Vendicated/Vencord#2576]
### Content

how can i apply? i was banned for "spam", i just posted a server ad in #offtopic and i read the rules and there are none about server invites or something like that, now i don't know what to do

![image](https://github.com/Vendicated/Vencord/assets/93141222/d5010d54-c68e-4534-b668-d56fcd312217)

### Request Agreement

- [x] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
don't advertise lmao
