### ISSUE TITLE
HUGE MEMEORY LEAK

### ISSUE THREAD

**Issue by NaysKutzu** [Vendicated/Vencord#2579]
### Content

https://mythical.pics/i?i=1718494676

ITS USING 32GB RAM!

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by lewisakura** [comment]
there is no information about this that means your memory leak is caused by vencord, as such we cannot take action on it.

also, in future, please just upload the file straight to github or to a not-suspicious looking hosting service

**Comment by Vendicated** [comment]
please expand the process list dropdown (`>`) and check which process specifically is taking the memory. enable the command line info column in your task manager and show that for the relevant process
