### ISSUE TITLE
[Bug] My discord app stay stuck on a blackscreen, after I turn on the ''hardware acceleration"

### ISSUE THREAD

**Issue by Soulivan71** [Vendicated/Vencord#2583]
### Discord Account

soulivan71

### What happens when the bug or crash occurs?

On start

### What is the expected behaviour?

I expect discord launching

### How do you recreate this bug or crash?

1 - Turn on an activitie in a VC
2 - Clic on : "Discord want to turn on hardware material acceleration for activities'
3 - Yes, its restarting the app and then not working anymore

### Errors

```
Replace this text with your crash-log.
```
![image](https://github.com/Vendicated/Vencord/assets/36502190/97c0edcf-6623-4271-b2e9-45052f92153c)
1st log I have when I launch app
![image](https://github.com/Vendicated/Vencord/assets/36502190/0e9f7708-4b8a-4450-9e32-cfed6e079b38)
2nd discord app
What can I do do have again my app without losing anything from my settings / plugins

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
lol ![image](https://github.com/Vendicated/Vencord/assets/45497981/4155fa0c-f1f1-460d-bec9-90af48ccd441)

**Comment by Soulivan71** [comment]
> lol ![image](https://private-user-images.githubusercontent.com/45497981/340459864-4155fa0c-f1f1-460d-bec9-90af48ccd441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjAwNjYsIm5iZiI6MTcxODY1OTc2NiwicGF0aCI6Ii80NTQ5Nzk4MS8zNDA0NTk4NjQtNDE1NWZhMGMtZjFmMS00NjBkLWJlYzktOTBhZjQ4Y2NkNDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIxMjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYmNiMDU3NzdjNmVmMjA1OGJhNGMzNWZkZWJjYmJiMGRkZTVmYzc2MWJiYzA0YjhiYmMyM2U0ODQ2ODM3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdXN6oHqBVNdq3Ez-cFv_Hw7lREQsDhizC4jrJOkvG4)

What Im missing ?

**Comment by rozbrajaczpoziomow** [comment]
you're not on stable lmfao
