### ISSUE TITLE
[Bug] guilds application tab not opening when betterfolders>sidebar is enabled

### ISSUE THREAD

**Issue by ThatsSasi** [Vendicated/Vencord#2605]
### Discord Account

sasiuwu

### What happens when the bug or crash occurs?

essentially when betterfolders is enabled, if the sidebar option is enabled, it prevents the tab from opening

### What is the expected behaviour?

i expect the tab to be opened at least, even better if in the sidebar

### How do you recreate this bug or crash?

1 enable betterfolders
2 enable sidebar
3 try to open the guilds application tab (if present)

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by lewisakura** [comment]
You can't use Vencord with BetterDiscord.

**Comment by Nuckyz** [comment]
Fixed in https://github.com/Vendicated/Vencord/pull/2867
