### ISSUE TITLE
When vencord on android?

### ISSUE THREAD

**Issue by Murchik0v** [Vendicated/Vencord#2611]
### Content

I would like to see vencord also as an android client, I was looking for alternatives to vencord on Android but couldn’t find them.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Faf4a** [comment]
There's [Vendroid](https://github.com/Vencord/Vendroid), however it's not being worked on actively

Some alternatives:
https://github.com/pyoncord/Pyoncord
https://aliucord.com/
