### ISSUE TITLE
I replace the existing plugin code with a modified one?

### ISSUE THREAD

**Issue by Murchik0v** [Vendicated/Vencord#2621]
### Content

I changed the code called translate for personal use so that it [translate](https://github.com/Vendicated/Vencord/tree/main/src/plugins/translate) not only into English but also the same Russian.
Can I replace the existing plugin code with a modified one?

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Scyye** [comment]
open a PR, although im confused as to what you actually did...

**Comment by Murchik0v** [comment]
> open a PR, although im confused as to what you actually did...
