### ISSUE TITLE
Reopen issue #2628

### ISSUE THREAD

**Issue by HypheX** [Vendicated/Vencord#2629]
### Content

My issue #2628 was wrongfully closed. I did go through the support channel, we tried repairing with the installer, deleting the Vencord files, reinstalling discord after deleting all of its files. Nothing is working

I got a (relucant) go-ahead to post the issue, as nobody could figure out my issue.

**I am currently attempting to replicate the issue in a fresh EndeavourOS VM.**
### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by HypheX** [comment]
> ### Content
> 
> My issue #2628 was wrongfully closed. I did go through the support channel, we tried repairing with the installer, deleting the Vencord files, reinstalling discord after deleting all of its files. Nothing is working
> 
> I got a (relucant) go-ahead to post the issue, as nobody could figure out my issue.
> ### Request Agreement
> 
>     * [x]  I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
this is a support request and doesn't belong here. do not open further requests or you will be blocked
