### ISSUE TITLE
[Bug] Can't move categories above other categories with ShowHiddenChannels enabled

### ISSUE THREAD

**Issue by Apacpua** [Vendicated/Vencord#2639]
### What happens when the bug or crash occurs?

Whenever I enable ShowHiddenChannels plugin, I can't move categories above other categories in my server and I also can't move categories blow or above certain channels or move those channels below or above the category. There's always conflicts.

### What is the expected behaviour?

The expected behavior is that I can freely move channels and categories in my own server.

### How do you recreate this bug or crash?

1. Enable ShowHiddenChannels plugin;
2. In your discord server, move a category over another category;
3. Notice that the category does not move.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by LyubomirT** [comment]
Can confirm, this is happening to me as well.

**Comment by littlegiqnt** [comment]
Still an issue, although for me only the top category does not move

**Comment by Vendicated** [comment]
should be fixed
