### ISSUE TITLE
[Bug] ShowAllRoles causing clipping issues with Profiles that contains lots of roles!

### ISSUE THREAD

**Issue by ColynOrg** [Vendicated/Vencord#2649]
### What happens when the bug or crash occurs?

when clicking a persons profile whom has lots of roles, the profile just gets stuck, you're not able to scroll up or down, leaving to have to use the right click menu if you want to try and add them as a friend and such.
![image](https://github.com/Vendicated/Vencord/assets/90815473/e26fe1fe-af0b-4216-8394-2ab9c4ab7938)

### What is the expected behaviour?

I expect ShowAllRoles to handle this kind of problem with profiles that have plenty of roles, possibly some sort of scrolling feature perhaps. 

### How do you recreate this bug or crash?

1. click on a persons profile whom may have a lot of roles.
2. you'll discover that you can not do anything besides receiving a clipped profile, not being able to scroll or add them as a friend etc unless you use the right click menu.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Luna-devv** [comment]
Very funny - 1. why would you have that many roles - 2. I haven’t really tested it with that many roles to be fair and I haven’t large screens - 3. question is how to solve this, scroll(?), limit the amount of roles (?) like 50(?), add a setting to set the amount(?)

**Comment by Luna-devv** [comment]
Adding this to your quick css makes the roles scrollable if the roles list is longer than the height of discord
```css
[class*="userPopoutInner_"] >
[class*="body_"] {
    overflow-y: scroll;
}

[class*="userPopoutInner_"] >
[class*="body_"]::-webkit-scrollbar {
    display: none;
}
```

https://github.com/Vendicated/Vencord/assets/71079641/98d0d937-aa46-4911-b63f-0a1a04958901

**Comment by CJStyles123** [comment]
> Very funny - 1. why would you have that many roles - 2. I haven’t really tested it with that many roles to be fair and I have large screens - 3. question is how to solve this, scroll(?), limit the amount of roles (?) like 50(?), add a setting to set the amount(?)

i was thinking scroll but like the same way as if you were hovering over a long status bubble within a profile and it just shows the rest of the content. here's an example of how i copied the same behavior but with my about me.
![example](https://github.com/Vendicated/Vencord/assets/90815473/748043fc-12f0-4296-8f14-f1196fc108a9)

**Comment by ColynOrg** [comment]
this issue is fixed so far for canary build as they also add a scroller to the popout. just awaiting for the release on stable build.
