### ISSUE TITLE
Cant find Apple Music RPC

### ISSUE THREAD

**Issue by BateleJack** [Vendicated/Vencord#2658]
### Content

I saw there is a pluging for Apple Music RPC on GitHub but cant find in Vencord

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by ImLvna** [comment]
you are most likely on discord web. this plugin is only available on discord desktop or vesktop

**Comment by BateleJack** [comment]
Im using Win11 Vencord

**Comment by BateleJack** [comment]
Oh okay, is it possible to see it on Windows?

**Comment by Vendicated** [comment]
mac only
