### ISSUE TITLE
[Bug] UserVoiceShow not working properly

### ISSUE THREAD

**Issue by terminaate** [Vendicated/Vencord#2664]
### Discord Account

terminaate

### What happens when the bug or crash occurs?

It doesn't show current user's voice channel - 
![изображение](https://github.com/Vendicated/Vencord/assets/91433379/08b12906-d612-491b-bbca-92c08ae893e8)
I guess it's happening because of discord ui update

### What is the expected behaviour?

Display the current user's voice channel

### How do you recreate this bug or crash?

Open any user's profile that currently in any voice chat

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Error-Cezar** [comment]
Bump, also occures since the new profile UI update

**Comment by alexonpeace** [comment]
Any updates on this?
This is the only plugin that I actively use

**Comment by Gitorian** [comment]
I also have the same issue. Can I help to resolve this somehow?

**Comment by Nuckyz** [comment]
The plugin is currently completely broken. Wait for a fix.

**Comment by Nuckyz** [comment]
The plugin has been fixed and will soon be available again

**Comment by Error-Cezar** [comment]
W Nuckyz
