### ISSUE TITLE
[Feature request] VCLog

### ISSUE THREAD

**Issue by Packsolite** [Vendicated/Vencord#2700]
### Content

A plugin to log all users you where in a voice channel with.
On public servers you sometimes want to know who just joined and instantly left your channel, or who you where talking to a few hours or even days ago. A plugin that logs all your voice channel history would be greatly helpful.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Faf4a** [comment]
Wrong repository, read the Issue template descriptions. 

Requests plugins here: https://github.com/Vencord/plugin-requests

![image](https://github.com/user-attachments/assets/9280bfb9-7c79-42ae-826c-75ed13ded9e4)
