### ISSUE TITLE
I was banned from the blackbox server for helping community members with their queries 

### ISSUE THREAD

**Issue by GrenFlem** [Vendicated/Vencord#2703]
### Content

I was sending messages in #support, and assisting people with their questions. A moderator showed up and purged my messages and the questions people asked, i asked why, they deleted that message aswell. So i said they are making it seem like only moderators are allowed to answer questions. Someone said "the morty guy is more helpful and nice" Then someone asked for their banner to be approved, so the moderator said "ask the morty guy to approve your banner if he is better than me" then i said i cannot approve banners, the moderator responded with "no shit", followed by him banning permanently from the server.

this is unacceptable moderation on their behalf, let alone in a support channel where questions are welcome. This is not a welcoming community.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by GrenFlem** [comment]
this is completely unwelcoming behavior and shouldn't be endorsed

**Comment by Vendicated** [comment]
and what does that have to do with vencord?? we have no affiliation and even if we did, it wouldn't belong here
