### ISSUE TITLE
[Bug] Message Logger Collapse Message strange behavior when removing message history from top to bottom!

### ISSUE THREAD

**Issue by ColynOrg** [Vendicated/Vencord#2711]
### Discord Account

CJStylesOrg

### What happens when the bug or crash occurs?

When I delete messages starting from the top of the thread downwards, the messages automatically collapse again after each deletion from the top. However, if I delete messages from any other position in the messages (not starting from the top), the collapsed messages remain expanded and do not collapse.
![Preview](https://files.catbox.moe/76dum4.gif)

### What is the expected behaviour?

I expect the message logger deleted messages to not collapse when removing the messages history from the top, the behavior should be just as the same as when you're not deleting from the very top.

### How do you recreate this bug or crash?

1. Enable the 'Message Logger' Plugin
2. Toggle on the 'Collapse Messages' option within it's Plugin Settings.
3. Start deleting a couple messages, once you start removing it's histroy from the top to bottom or bottom to top, you notice both share a different behavior.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
i wouldn't really consider this an issue, seems like expected behaviour

blocked messages do the same too
