### ISSUE TITLE
[Bug] VC Narrator speak twice every sentence

### ISSUE THREAD

**Issue by Soulivan71** [Vendicated/Vencord#2716]
### What happens when the bug or crash occurs?

Every action is saying twice. 
I can send an example if u need

### What is the expected behaviour?

The narrator only speak once

### How do you recreate this bug or crash?

Its happening everytime (even after restart app)

### Errors

No error

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
can't reproduce. use our support channel if you need help.
