### ISSUE TITLE
[Bug] Issue with platform indicators

### ISSUE THREAD

**Issue by Lncvrt** [Vendicated/Vencord#2722]
### Discord Account

@lncvrt

### What happens when the bug or crash occurs?

![image](https://github.com/user-attachments/assets/5a70b716-9d15-416d-a80a-48812d5f7db9)
The bug is the icon for platform indicators console is messed up

### What is the expected behaviour?

Should be a proper icon

### How do you recreate this bug or crash?

Find a person on a console then use platform indicators

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by coopeeo** [comment]
I believe that image is correct, it's showing a fridge.
Well it's a Xbox Series X from the angle like the picture below
![Xbox Series X (rotated about 45° to the left)](https://github.com/user-attachments/assets/b48ca361-db32-4776-98bd-f44eff5aa22c)
I mean the icon looks like its more like rotated 35° to the left but whatever.

**Comment by Lncvrt** [comment]
it doesn't really make much sense to me though
theres a lot better icons like a xbox one for example

**Comment by Shavixinio** [comment]
No, fridge is the best icon

**Comment by korbosoft** [comment]
> it doesn't really make much sense to me though theres a lot better icons like a xbox one for example

the icon IS an xbox one, they are jokingly calling it a fridge.

**Comment by KrstlSkll69** [comment]
> > it doesn't really make much sense to me though theres a lot better icons like a xbox one for example
> 
> the icon IS an xbox one, they are jokingly calling it a fridge.

nuh uh it is fridge... gamin fridge

**Comment by coopeeo** [comment]
> > it doesn't really make much sense to me though theres a lot better icons like a xbox one for example
> 
> the icon IS an xbox one, they are jokingly calling it a fridge.

NUH UH ITS A FRIDGE

**Comment by KrstlSkll69** [comment]
> > > it doesn't really make much sense to me though theres a lot better icons like a xbox one for example
> > 
> > 
> > the icon IS an xbox one, they are jokingly calling it a fridge.
> 
> NUH UH ITS A FRIDGE

![that's-what-i'm-saying](https://github.com/user-attachments/assets/512f7ea1-4e40-4a67-ac0d-d5b8cf57b76e)

**Comment by Lncvrt** [comment]
the fridge icon looks stupid idk where this is going but it should look like a xbox one imo
![1067333-200](https://github.com/user-attachments/assets/5ebfbd41-2847-44af-8b35-7fb52658b0d4)
something like this

**Comment by Lncvrt** [comment]
but more simple probably

**Comment by coopeeo** [comment]
> the fridge icon looks stupid idk where this is going but it should look like a xbox one imo ![1067333-200](https://private-user-images.githubusercontent.com/171465674/352786447-5ebfbd41-2847-44af-8b35-7fb52658b0d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMzQ1MTQsIm5iZiI6MTcyMjEzNDIxNCwicGF0aCI6Ii8xNzE0NjU2NzQvMzUyNzg2NDQ3LTVlYmZiZDQxLTI4NDctNDRhZi04YjM1LTdmYjUyNjU4YjBkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQwMjM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGI0MmEzZjUyNzE3ZmI0MzVhNzM0NTlmMzUzZTAzNzhlZWMwYWFkZTgwYzY5MzFkMGNmM2Y2YTE4YmEyOGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tfyz272Rwp3jgjhUQAzBT8CAipgWCCyBycXnxz6SHck) something like this

nuh uh it should still be the xbox series x mini fridge

**Comment by thororen1234** [comment]
> but more simple probably

I think it should be either the Xbox Series S toaster or the Xbox Series X mini fridge first they are actual products from the meme second they are consoles third why not?

**Comment by Lncvrt** [comment]
i originally thought it didn't look right because it's just not that detailed but a new icon would probably be a good idea

**Comment by Shavixinio** [comment]
The fridge is funny, let it stay

**Comment by nyakowint** [comment]
nopppp fridge is forever 
![image](https://github.com/user-attachments/assets/726deb95-7c85-4067-9b2e-4267255604f7)

**Comment by Lncvrt** [comment]
this is the most braindead issue report on here but its so small and not detailed it doesnt look like a console

**Comment by nyakowint** [comment]
average vencord github issue

I think mutual agreement is the fridge is staying. At least for now... not that serious :shipit: :P

**Comment by sadan4** [comment]
The fridge must stay.

**Comment by Lncvrt** [comment]
then leave the fridge how it is, it just doesn't seem right though lmao
