### ISSUE TITLE
[BUG] Translate 

### ISSUE THREAD

**Issue by Shadowlegend2008** [Vendicated/Vencord#2756]
### Content

for some reason there is no longer the possibility to translate the sentences using the button. I'm also sure that I have activated the possibility that shows me the button to translate the sentences but it's not there at all. Can you please fix this problem
translate the translation works when someone writes a sentence and it automatically translates it for you but the problem is that if someone writes a message and you want to translate it there is no button to translate the sentence that someone else wrote and this is a problem

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
1. 
![image](https://github.com/user-attachments/assets/873e113e-7f19-41cb-a8ae-86303f110e39)

2.
![image](https://github.com/user-attachments/assets/a987cc91-c838-4855-8f21-4546812b66ec)

**Comment by Shadowlegend2008** [comment]
Thanks for your help, I hope you can resolve the problem
