### ISSUE TITLE
[Bug] Java script error

### ISSUE THREAD

**Issue by aelixi** [Vendicated/Vencord#2757]
### Discord Account

enrc

### What happens when the bug or crash occurs?

![image](https://github.com/user-attachments/assets/ba5b9760-0ad3-452d-ae35-2567ede2ee57)

### What is the expected behaviour?

expected behaviour is vencord to just open

### How do you recreate this bug or crash?

download vencord using git clone and pnpm inject

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Nuckyz** [comment]
Use the support channel on the discord server
