### ISSUE TITLE
[Bug] button is invisible

### ISSUE THREAD

**Issue by 2JENO** [Vendicated/Vencord#2758]
### Discord Account

LJeno

### What happens when the bug or crash occurs?

![image](https://github.com/user-attachments/assets/1cc026fd-0261-4b7e-a725-f0b6d8a1daee)

### What is the expected behaviour?

idk

### How do you recreate this bug or crash?

just move mouse on messege

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by surgedevs** [comment]
![image](https://github.com/user-attachments/assets/f91f8f35-2a1a-47f1-bf88-667e2526b6e0)

**Comment by 2JENO** [comment]
oh sorry

**Comment by 2JENO** [comment]
oh and fixed on current update sorry..........

**Comment by 2JENO** [comment]
nvm fixed
