### ISSUE TITLE
Bug: arRPC plugin not working on web

### ISSUE THREAD

**Issue by hotsno** [Vendicated/Vencord#276]
The arRPC plugin isn't working for me using the userscript in a browser.

I see this in my browser's console:
`Starting plugin WebRichPresence (arRPC)`
but not any other relevant output/errors.

I've confirmed that pasting [bridge_mod.js](https://github.com/OpenAsar/arrpc/blob/main/examples/bridge_mod.js) directly into my browser's console gets arRPC working so it seems like a Vencord issue.

Browser: Brave
OS: macOS 13.0.1
Userscript version: 1.0.0.1669865203194

Also I've tried the extension as well.

**Comment by Vendicated** [comment]
disable brave shield

**Comment by hotsno** [comment]
I have, I'm the person who was having issue with it earlier :)

**Comment by hotsno** [comment]
II've confirmed that it doesn't work in Chrome as well a few days ago as well.

**Comment by hotsno** [comment]
Actually, I just checked Chrome again, and though it doesn't work, it's at least showing an error:
```
Uncaught (in promise) TypeError: Rp.lookupApp is not a function
    at Ep (userscript.html?name=Vencord.user.js&id=983c6b8f-575f-415e-b54a-e9b78d2d09e8:52:5695)
    at wt.onmessage (userscript.html?name=Vencord.user.js&id=983c6b8f-575f-415e-b54a-e9b78d2d09e8:52:6801)
Ep @ userscript.html?name=Vencord.user.js&id=983c6b8f-575f-415e-b54a-e9b78d2d09e8:52
wt.onmessage @ userscript.html?name=Vencord.user.js&id=983c6b8f-575f-415e-b54a-e9b78d2d09e8:52
```
This is seems like the same error I'm getting when I use this [userscript](https://github.com/OpenAsar/arrpc/blob/main/ext/userscript.js) from the arRPC repo, so I assume that this error isn't related to Vencord.

However, the fact that I'm not even getting this error on Brave is weird, and maybe related to Vencord?

**Comment by Vap0r1ze** [comment]
Might be something with your log levels in the console? not sure

**Comment by hotsno** [comment]
@Vap0r1ze ah that's a good thought. I put the log level to verbose and now see the error in Brave.

So now we know this is the same issue that the arRPC userscript and extension is having, feel free to close this issue if it makes sense.
