### ISSUE TITLE
[Bug] Vencord on macOS does not support multi-user setups

### ISSUE THREAD

**Issue by miklosakos** [Vendicated/Vencord#2764]
### Discord Account

miklos_akos

### What happens when the bug or crash occurs?

If user x installs Vencord using the installer on macOS where more than one user is present, user y's instance will try to read from user x's `Application Support` directory.
<img width="632" alt="image" src="https://github.com/user-attachments/assets/31d1ebc3-f210-4b8c-9423-d0baeee89b92">

### What is the expected behaviour?

I expect Vencord to be able to handle multi-user setups.

### How do you recreate this bug or crash?

1. Create user x
2. Install Vencord as user x
3. Sign into Vencord as user x
4. Switch to user y
5. Try to launch the Discord app

### Errors

```
Uncaught Exception:
Error: Cannot find module '/Users/vic/Library/Application Support/Vencord/dist/patcher.js'
Require stack:
- /Applications/Discord.app/Contents/Resources/app.asar/index.js
- 
at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
at s._resolveFilename (node:electron/js2c/browser_init:2:121618)
at Module._load (node:internal/modules/cjs/loader:993:27)
at c._load (node:electron/js2c/node_init:2:13801)
at Module.require (node:internal/modules/cjs/loader:1240:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> (/Applications/Discord.app/Contents/Resources/app.asar/index.js:1:1)
at Module._compile (node:internal/modules/cjs/loader:1373:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
at Module.load (node:internal/modules/cjs/loader:1215:32)
```
Output of `whoami`
```
miklos_akos@YiffBook-Pro ~ % whoami
miklos_akos
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Sqaaakoi** [comment]
Not a macOS only issue, can occur on Linux too. Could be be fixed (in theory) by `chmod -R 666` the Vencord directory and moved to a non-user specific path.
This might be easier to fix along with the asar-bundle feature branch

**Comment by itsvic-dev** [comment]
> Could be be fixed (in theory) by `chmod -R 666` the Vencord directory and moved to a non-user specific path.

@Sqaaakoi not sure how good of an idea that is, considering (iirc at least) vencord stores user settings and such in that folder as well. for now, we have multiple copies of the app in the user-specific applications directory (`/Users/$USER/Applications`) instead

**Comment by lumap** [comment]
a maybe better idea would be to `mv /Applications/Discord.app ~/Applications/Discord.app` and do all the work from there. other users can just re-download Discord for themselves.

**Comment by CrownAlexanRaven** [comment]
Hypothetically, the install location could be moved to a shared directory like  `/Users/Shared/Vencord`, then `chmod -R 666` the directory. 
That might cause some problems with installing, I'm not exactly sure how Vencord handles its installation.

**Comment by Vendicated** [comment]
I don't think this is something that needs fixing. you can just install discord for your own user instead of for everyone and won't have this issue

for example on mac drag it into your user application folder. on linux, there are various ways (e.g. user installed flatpak or discord in `~/.local/share`)
