### ISSUE TITLE
[Bug] messagetags plugin keeps deleting the message tags i set

### ISSUE THREAD

**Issue by ComfortableMilk4454** [Vendicated/Vencord#2779]
### Discord Account

estrobink1 (id is 1208425348312596550)

### What happens when the bug or crash occurs?

messagetags plugin keeps deleting the message tags i set. been happening for ~a week now.

> **Vencord**: v1.9.7 • [5160f90](<https://github.com/Vendicated/Vencord/commit/5160f90>) (Vesktop v1.5.3) - 3 Aug 2024
**Client**: stable ~ Vesktop v1.5.3
**Platform**: MacIntel
⚠️ Activity Sharing disabled

### What is the expected behaviour?

for it to not delete half of my tags

### How do you recreate this bug or crash?

wait for tag to delete itself 

### Errors

```
don't see any errors
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by sadan4** [comment]
ive ran into this, idk what is causing it tho

**Comment by ComfortableMilk4454** [comment]
@sadan4 good to know it's not just me!

**Comment by Vendicated** [comment]
if you're switching between canary and stable, that's why. they aren't shared between those at the moment

otherwise you should try reinstalling vesktop

**Comment by ComfortableMilk4454** [comment]
i have tried reinstalling vesktop & im not switching between canary & stable

**Comment by ComfortableMilk4454** [comment]
oh u closed it as not planned i didnt notice just woke up, rip guess i wont be able to use messagetags xd.

**Comment by Vendicated** [comment]
because it's a support matter, not a bug. you should stick to the support channel like the issue template tells you

**Comment by ComfortableMilk4454** [comment]
Well I thought it was a bug and I asked 3 times in support across 2 days and nobody responded to me so I asked here, sorry

**Comment by ComfortableMilk4454** [comment]
resolved itself, thanks
