### ISSUE TITLE
Unable to use themes in browser with Vencord extension

### ISSUE THREAD

**Issue by Spacellary** [Vendicated/Vencord#278]
### Using `extension-v2` from latest release.

* [Screenshot 1] Clicking the Edit CSS button only brings a blank (about:blank) page with no CSS edior.
* [Screenshot 2] Alternatively, GitHub raw links aren't working either.

#### Screenshots (click for full size):
<img src="https://user-images.githubusercontent.com/39604793/205304326-dda5e2e6-ab50-40c5-b29a-3620a05c36a0.png" width="300">

<img src="https://user-images.githubusercontent.com/39604793/205304414-f150e4f4-d178-434c-9052-d26e0396405c.png" width="300">

**Comment by Vendicated** [comment]
don't use that file, use the ones below

**Comment by Spacellary** [comment]
oh

**Comment by Spacellary** [comment]
I'm stewpid, thanks Ven-senpai
Much love~

**Comment by justchokingaround** [comment]
![image](https://user-images.githubusercontent.com/44473782/205384466-97bb9563-dd4d-4937-a69c-718f01f64c2c.png)

the same exact link works in the client

**Comment by Vendicated** [comment]
what build, what browser, what file did you install

**Comment by justchokingaround** [comment]
yes sorry, should've mentioned that:

Im using the userscript with tampermonkey in brave

**Comment by Vendicated** [comment]
use the extension then or use a proper github pages link, I cannot modify headers in the userscript

**Comment by justchokingaround** [comment]
using the extension fixed the problem :+1:

**Comment by ThatOneVideoGamer** [comment]
This might need to be reopened, I'm having this happen in Firefox with the add-on and nothing says there are any updates. My custom CSS in quickCSS still works from when it was working before, but opening the window now to edit it shows a blank window. GitHub raw links fail to fetch as well and don't do anything.

**Comment by Vendicated** [comment]
Firefox issue

**Comment by ThatOneVideoGamer** [comment]
> Firefox issue

I'm sorry, I'm confused? Firefox is a supported browser, no? I don't see anything in the repo about Firefox being unsupported

**Comment by Vendicated** [comment]
The issue is caused by Firefox and there's nothing we can do to fix it because it simply doesn't apply the networking rules. It works fine on any Chromium based browser

**Comment by ThatOneVideoGamer** [comment]
> The issue is caused by Firefox and there's nothing we can do to fix it because it simply doesn't apply the networking rules. It works fine on any Chromium based browser

Ohhh ok! Would you mind adding that to the repo for others to see? (Any maybe suggesting something like Stylus as an alternative for CSS?)

**Comment by Spacellary** [comment]
I hope these things get ironed out in Firefox'd end, I wad thinking of switching back to it but the more I wait the more Edge just works for me. Tough seeing it like that.

**Comment by Henry-Hiles** [comment]
I currently use thorium, it's pretty good. Ungoogled chromium is decent too
