### ISSUE TITLE
Vencord doesn't restart properly.

### ISSUE THREAD

**Issue by h4rldev** [Vendicated/Vencord#279]
#### Info
```OS```: Windows 10 x64 (win32)
```Discord```: Stable (Stable 161884 (ba55f09))
```Vencord```: Latest (Daf3a1d)

#### Issue
The restart button / prompt when updating doesn't restart Discord properly, often causing issues.

#### Examples: 
- Green circle in vc stops working (possibly more issues with vc).
- Build issues.

**Comment by h4rldev** [comment]
I installed it via the pnpm method

It shows "build errors" on restart after updates

I'll try to see if it's a plugin issue.

I don't see any errors in console that are related to vencord or anything else, I can take a screenshot the next time I see anything though.

It might also be just an issue with openasar aswell (although I doubt it is) 
(I will run a clean discord + vencord and wait for an update to see if there's issues).

Ok, green circle issue resolved, 
It was a theme issue that only occurs when restarting through vencord, 
All i had to to was clear my quickcss.

**Comment by Vendicated** [comment]
The manual install method isn't supported. Figure it out yourself or use the proper install method via the installer

(You likely need to install the newly added dependencies)

**Comment by h4rldev** [comment]
I got this before the installer existed, I'll try to reinstall it with the installer then. Thanks, i guess?
