### ISSUE TITLE
[Bug] Game activity toggle button hover effect persistent

### ISSUE THREAD

**Issue by equmaq** [Vendicated/Vencord#2802]
### Discord Account

@equmaq

### What happens when the bug or crash occurs?

Hover popup for the game activity button does not go away
![image](https://github.com/user-attachments/assets/a63b0ed1-d0d5-4682-a81b-a812426d9bab)

### What is the expected behaviour?

It going away
![image](https://github.com/user-attachments/assets/4468569b-e18e-46a1-9994-a50c064e68fb)

### How do you recreate this bug or crash?

(In windows)
1. Move your cursor really fast over the game activity toggle and off of the discord window.

### Errors

```
Sad css womp womp :(
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by equmaq** [comment]
That title sounds dumb, what idiot would write it like that?

**Comment by Vendicated** [comment]
not a vencord issue. we just use discord's tooltip component
