### ISSUE TITLE
[FEATURE REQUEST - BlurNSFW] - Blur Embedded Media

### ISSUE THREAD

**Issue by MightyLoggor** [Vendicated/Vencord#2837]
### Content

[The topic in the discord support](https://discord.com/channels/1015060230222131221/1026515880080842772/1280570489236095078)

Regarding the BlurNSFW, it would be ideal that it worked on linked images and embeds too.

At the moment it only blurs images(files) sent in the channel. If the image is embedded in a link or it's a pure image link from the web, the image is not blurred.

It would be interesting for the plugin to blur those embedded media too. Especially images.

Examples:
![image](https://github.com/user-attachments/assets/c0186123-f606-4070-8dff-2f3da8b5ed4e)
![image](https://github.com/user-attachments/assets/6c90303b-09a5-4b11-a9ba-09c9983f86fa)

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Nuckyz** [comment]
Fixed by https://github.com/Vendicated/Vencord/commit/43b3c137ceb5ee8b02147936ef17334a1845089b
