### ISSUE TITLE
[Feature Request] Auto Backup/Export Vencord

### ISSUE THREAD

**Issue by hairyfred** [Vendicated/Vencord#285]
Add a feature to allow auto exporting Vencord settings at a chosen interval to directory of choice.

Why?

explod

**Comment by MeguminSama** [comment]
Thanks for the request! I'm going to merge this with https://github.com/Vendicated/Vencord/discussions/313

**Comment by JunkiEDM** [comment]
Can we re-open this since discussions are dead and this hasn't been added afaik?
Cloud sync just automatically removed like a week of QuickCSS that I have to redo now so this would be useful to prevent that from happening again
