### ISSUE TITLE
TimeBarAllActivities: deprecated

### ISSUE THREAD

**Issue by fawni** [Vendicated/Vencord#2874]
### Content

discord now adds the time bar on their own (for now?)

vesktop with TimeBarAllActivities enabled
![image](https://github.com/user-attachments/assets/99a2c5bc-db89-4d5b-8523-4734eba28505)

completely stock discord
![image](https://github.com/user-attachments/assets/f0230630-1821-49fe-9ef3-de6c490a4a0d)

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
hi fawni

**Comment by fawni** [comment]
hi kitty

**Comment by Vendicated** [comment]
i ate it

**Comment by fawni** [comment]
bone appetit
