### ISSUE TITLE
failed to patch this install 

### ISSUE THREAD

**Issue by 12num0** [Vendicated/Vencord#2879]
### Discord Account

12num0

### What happens when the bug or crash occurs?

failed to patch this install 

![photo_2024-09-15_21-26-16](https://github.com/user-attachments/assets/aa389ab4-ac04-4a66-a0cf-1b841742c63d)
when I deleted and down loaded back the discord it showed this (photo 2)

![photo_2024-09-15_21-34-57](https://github.com/user-attachments/assets/ffbae8ae-bf92-46ee-a7f5-aca459f607b1)

### What is the expected behaviour?

.

### How do you recreate this bug or crash?

idk

### Errors

failed to patch this install 

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by 12num0** [comment]
I fixed it

**Comment by 12num0** [comment]
I fixed it

**Comment by loveuseless** [comment]
> I fixed it

Как?
