### ISSUE TITLE
Spotify controls disappears randomly

### ISSUE THREAD

**Issue by Commandtechno** [Vendicated/Vencord#288]
not sure if anyone else is having this issue but every once in a while the songs just disappear and usually reappear once a new song starts

![image](https://user-images.githubusercontent.com/68407783/205465665-18e07a14-d10e-45b2-9749-8433ed9b1a26.png)

![image](https://user-images.githubusercontent.com/68407783/205465668-3803c0fb-06ed-4216-8313-9d56bbb5bcf9.png)

**Comment by somerandomcloud** [comment]
This is just spotify/discord being weird, happens with SpotifyControls for BD as well for the same reason

**Comment by Vendicated** [comment]
yeah it just uses the data discord gives it, so there's not much that can be done to fix it (but also I never had this issue tbh)

**Comment by Commandtechno** [comment]
Ok I have found the culprit
![WS disconnected](https://commandtechno.com/i/7yx3ao10ezoy.png)

But the websocket is still open with pings still being sent and my Spotify presence is still active ?
![WS still open](https://commandtechno.com/i/7yx3gq9ck3td.png)
![Spotify presence](https://commandtechno.com/i/7yx3hks1dyc5.png)

**Comment by Commandtechno** [comment]
Update #3: It's because I had another Spotify connected with presence turned off which meant that the WS always disconnected which for some reasons cancels both of them in this plugin? Well removing it fixes it but still a strange issue 🤔.

**Comment by Vendicated** [comment]
look at the Spotifystore class of the plugin. it just consumes discords events and dispatches changes whenever there's an event

**Comment by shirtfulness** [comment]
for me, it straight up doesnt work

**Comment by Vendicated** [comment]
use our support channel instead of necroing two years old threads.
