### ISSUE TITLE
[Bug] FakeNitro showing VC reactions as useable

### ISSUE THREAD

**Issue by Obsidianninja11** [Vendicated/Vencord#2897]
### Discord Account

obsidianninja11

### What happens when the bug or crash occurs?

FakeNitro incorrectly shows the vc emojis as useable when they aren't.
![image](https://github.com/user-attachments/assets/5037228a-5cb0-4de8-a1d7-db661173f20b)

### What is the expected behaviour?

I expected FakeNitro to not change this picker modal.

### How do you recreate this bug or crash?

1. Turn on the FakeNitro plugin
2. Join a voice channel
3. Click the emoji button and expand the emoji picker
4. Use an emoji you don't have access to (it won't work, but fakenitro will make it look like it will)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Nuckyz** [comment]
Fixed in https://github.com/Vendicated/Vencord/pull/2901
