### ISSUE TITLE
Problem with updating client

### ISSUE THREAD

**Issue by ArttX** [Vendicated/Vencord#293]
When trying to use in-app updater or manual update.
Client can not resolve `@vap` path.
```
X [ERROR] Could not resolve "@vap/core/ipc"
    src/plugins/shikiCodeblocks/api/shiki.ts:21:29:
      21 │ import { WorkerClient } from "@vap/core/ipc";
         ╵                              ~~~~~~~~~~~~~~~
  You can mark the path "@vap/core/ipc" as external to exclude it from the bundle, which will remove this error.
```

P.S. If it is path to code, then is not exists in `tsconfig.json`

**Comment by Vendicated** [comment]
because you are missing dependencies. Use the official build

**Comment by ArttX** [comment]
@Vendicated 
What is meant with official build?
I used method for power users, this is article, that is found in official readme.
Is this method not recommended to use anymore and installer should be used instead?

**Comment by Vendicated** [comment]
The method is meant for power users and developers. If you can't figure out basic issues like this you shouldn't be using it. A plugin added dependencies that you are missing, you need to install dependencies to fix it

**Comment by ArttX** [comment]
@Vendicated
I am developer. I am developing Discord bots and websites. So I understand what I am doing. 😆
My concern was than I don't have idea where to look for missing dependencies. 
But thanks for answer.

**Comment by MeguminSama** [comment]
@ArttX For the sake of politeness & supporting less experienced developers, if you're looking to develop with Vencord, I suggest learning how node.js and npm works.

The official Node.JS guide is good for getting an overview https://nodejs.dev/en/learn and also has a guide covering npm, which would cover the issue you are facing https://nodejs.dev/en/learn/an-introduction-to-the-npm-package-manager/

tsconfig.json is used for managing typescript configuration, and does not actually have anything to do with dependencies, which are discussed in depth in the guides linked :)

**Comment by ArttX** [comment]
@MeguminSama 
I know how node.js and npm works. I already have 4 years experience. Also I am working with TS a lot.
I only wanted to get newest update of Vencord for use.
Thanks for answers.

**Comment by DiamondMiner88** [comment]
Doesn't seem like you do if you don't know how to run `pnpm install` :trollface:

**Comment by ArttX** [comment]
@DiamondMiner88 
I already installed Vencord week ago and used it.
Now there is new update. And build-in updater is failing with same error: `Could not resolve "@vap/core/ipc"`
So I tried to do `git pull`, but git says that there is no new changes.
As there is no changes, then there is nothing to `pnpm install` or `pnpm build`
