### ISSUE TITLE
read out OS trusted CA cert for company networks/ignore TLS mode

### ISSUE THREAD

**Issue by castdrian** [Vendicated/Vencord#295]
certain network functionality, (such as fetching themes, reviewDB, pronounDB etc..) does not work when the trusted CA cert is self signed (such as on company networks), there's an extension for VSC for instance, which just passes down the OS cert to vsc and thus making stuff like copilot functional, ideally vencord should do this or have a toggle to completely ignore TLS overall

**Comment by ArjixWasTaken** [comment]
Ignoring TLS is a security risk, and since you mentioned company certs, I assume you are on a company computer? You wouldn't want to risk infecting company property.

**Comment by castdrian** [comment]
I'm aware, hence the slash there, no TLS is more of an emergency solution, preferably what https://github.com/ukoloff/win-ca does should be done

**Comment by Vendicated** [comment]
this is heavily out of scope and a security hole I'm not willing to open. You can probably do this on an os level or might just be able to solve it via a vpn?

**Comment by castdrian** [comment]
aight, guess this is another client mod that's unusable on a modified cert, not really much that can be done OS level as the cert is already installed as trusted cert, if you as I said added the ability to lazy load that cert as well that'd be solved

**Comment by Vendicated** [comment]
there doesn't even seem to be an api that can import certificates into electron that works on Mac/Windows. Have you tried following this article https://support.kaspersky.com/CyberTrace/1.0/en-US/174127.htm

**Comment by Vendicated** [comment]
actually scratch that, you can easily do it by passing a command line flag to discord
https://www.electronjs.org/docs/latest/api/command-line-switches#--ignore-certificate-errors

**Comment by castdrian** [comment]
discord itself definitely ignores the self signed cert error, so hence why I was saying it'd probably something that can be done here to fix this besides it being incredibly niche

**Comment by Vendicated** [comment]
try passing that flag and it should work

**Comment by castdrian** [comment]
played around a bit, it seems to either ignore the flag or not work regardless :(
![Discord_5qlRe2LSKR](https://user-images.githubusercontent.com/22133246/205926749-74e0ac5c-89df-49eb-a992-7d244a937116.png)

**Comment by ArjixWasTaken** [comment]
> there doesn't even seem to be an api that can import certificates into electron that works on Mac/Windows. Have you tried following this article https://support.kaspersky.com/CyberTrace/1.0/en-US/174127.htm 

https://github.com/ukoloff/electron-win-ca

For windows at least

**Comment by castdrian** [comment]
> https://github.com/ukoloff/electron-win-ca
> 
> For windows at least

yeah this is used by the vsc extension I linked earlier (https://github.com/ukoloff/win-ca/blob/master/vscode/index.js), despite this issue being closed and marked as non planned, I feel like it'd still be good to have vencord be able to properly function with self signed CA certs, Discord itself does and every clientmod I've come across in the past didn't really care for this a all - which understandably is a very niche thing - but to me feels like an important oversight

**Comment by Vendicated** [comment]
feel free to open a pull request. If it's secure and doesn't add much bloat I wouldn't mind adding it

**Comment by castdrian** [comment]
gotcha, maybe consider to reopen as enhancement, to track?
