### ISSUE TITLE
[Bug] ViewIcons is not working properly

### ISSUE THREAD

**Issue by ScruffyEspy** [Vendicated/Vencord#2962]
### Discord Account

.serious_person_not_found

### What happens when the bug or crash occurs?

The bug happens then i wanna see someone pfp or banner but instead of image there appear grey rectangle
![Screenshot_81](https://github.com/user-attachments/assets/e092827e-acb1-4374-b8d8-de39d9fa95b4)

### What is the expected behaviour?

I expect Vencord/Discord to makes avatars and banners in user profiles clickable and being able to download them

### How do you recreate this bug or crash?

1. Press on anyone pfp or banner

### Errors

I cant find it

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
this issue is known and is being fixed. also, do not open issues without permission of a support server moderator
