### ISSUE TITLE
[Feature Request] Better Autocorrect Plugin?

### ISSUE THREAD

**Issue by Jasrajthelegend** [Vendicated/Vencord#3007]
### Content

[Feature Request] Possibility for Better Autocorrect in terms of it not taking forever after correcting one word to correct another, also plus if you would freshen up the UI of autocorrect and be able to choose your engine of autocorrect you prefer

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Julienraptor01** [comment]
Would indeed be nice

Would also be cool to be able to configure the language(s)
Personally it feel random wether it picks english or french as the language to autocorrect and it's very annoying
Would be nice if it allowed to specify a layered list of languages or at least to pin it to a single one
