### ISSUE TITLE
ViewIcon opening the banner when clicking the nitro upsell button in someone's profile

### ISSUE THREAD

**Issue by KotonBads** [Vendicated/Vencord#302]
![nitro upsell](https://user-images.githubusercontent.com/66117568/206485629-962c15b4-ea42-416d-b601-0022ae5202a0.gif)

click goes through the nitro upsell

**Comment by Vendicated** [comment]
don't click the nitro upsell :trollface: (this is not easily fixable without patching the nitro button which isn't really worth the effort imo cause this is basically a non-issue)
