### ISSUE TITLE
    noProfileThemes a broken

### ISSUE THREAD

**Issue by michelle1574** [Vendicated/Vencord#3031]
### What happens when the bug or crash occurs?

not working

### What is the expected behaviour?

it work

### How do you recreate this bug or crash?

get a user nitro then enable no work

### Errors

not can

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
use our support channel.
