### ISSUE TITLE
[Bug] <Vencord Platform Plugin doesnt work

### ISSUE THREAD

**Issue by n29cibnf** [Vendicated/Vencord#3039]
### What happens when the bug or crash occurs?

![image](https://github.com/user-attachments/assets/fff217ed-97b1-48b6-b842-0ad151e30e52)

using the plugin but the other person doesn't have any indicator of them being on what platform, bc they are using invisible mode

### What is the expected behaviour?

however it works fine with online/dnd/idle users,

### How do you recreate this bug or crash?

just communicating with a user who is in invisible mode

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by k26pl** [comment]
discord does not send platform info for offline users, this is impossible
