### ISSUE TITLE
[Bug] appleMusic.desktop not present in vencord

### ISSUE THREAD

**Issue by MrEnder0** [Vendicated/Vencord#3066]
### Discord Account

mr.ender

### What happens when the bug or crash occurs?

When I go to the plugins menu in the settings I can not find the Apple Music plugin. Im not sure if this is on purpose or if it was left out on accident, it seems excessive to build the whole vencord from source if I want to use this plugin.

### What is the expected behaviour?

Be able to search and find Apple Music plugin within the default Vencord install.

### How do you recreate this bug or crash?

1. Go to settings
2. Go to plugin menu
3. Search for apple

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
use our support channel
