### ISSUE TITLE
[Crashing] <Vencord call timer crashing>

### ISSUE THREAD

**Issue by Snowy633** [Vendicated/Vencord#3067]
### Discord Account

snowy03383

### What happens when the bug or crash occurs?

Hi i'm new to github, The crash always happens when i turn on the "Call Timer" plugin when im in a call, but when i turn it off discord works fine. I installed the extension version of the Vencord plugin.

### What is the expected behaviour?

Potentially overriding? i don't really know i do not have much knowledge on tech nor anything tech savy i just moderate and fix servers.

### How do you recreate this bug or crash?

I turn on the plugin called "Call Timer" then it crashes 100% of the time anytime i join a call, but to stop it i simply turn off the plugin.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by jamesbt365** [comment]
![image](https://github.com/user-attachments/assets/e70a1439-177e-41ce-83c6-7658b4a482bc)

Thing is you were in the discord server *first* you just happen to be ignoring the blatant instructions that say to not to open issues without permission.

Stop ignoring instructions.

If you read the information that is provided to you when you joined the server you would see that we are already aware of the problem.

**Comment by Snowy633** [comment]
okay ty james
