### ISSUE TITLE
[Bug] <title>The CallTimer is not working.

### ISSUE THREAD

**Issue by panzerbrechend** [Vendicated/Vencord#3068]
### What happens when the bug or crash occurs?

The CallTimer is no longer working. Reinstalling and repairing, as well as turning the plugin off and on again, have not helped either. Is this a known issue? How can I resolve it?

### What is the expected behaviour?

I don't understand

### How do you recreate this bug or crash?

I don't understand

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by jamesbt365** [comment]
After everything saying not to open bug reports if you aren't a contributor or got permission in the discord server, you did it anyway?

Use the Vencord support server, there are multiple links to it when you went to go open an issue.
