### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by idkthrowaway123** [Vendicated/Vencord#3073]
### What happens when the bug or crash occurs?

emoji autocomplete/preview is no longer working for me on build 2dc8c2b with favoriteemojifirst plugin enabled, disabling it restores expected functionality, i have reinstalled vencord already, no change

### What is the expected behaviour?

.

### How do you recreate this bug or crash?

.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Fapo39** [comment]
> > I am using Discord Stable or tried on Stable and this bug happens there as well
> 
> this is just a straight up lie but looking at how the issue form is setup here I guess you have to check it. x.x It works just fine on Discord Stable it's only bugged when using Vencord.

it's not, I am using discord stable & vencord and having same issue, the preview for emoji is gone and the emoji itself wont load unless typing the full string, disabling the plugin fixes it
