### ISSUE TITLE
[Bug] Pinned Messages appearing duplicated after new Vencord update

### ISSUE THREAD

**Issue by santacapra** [Vendicated/Vencord#3077]
### What happens when the bug or crash occurs?

Ever since the latest Vencord update (13 December 2024), Pinned messages now appear duplicated. Meaning they appear both in the Pinned messages tab, and also in the regular direct messages at the same time. Selecting one will select them both

### What is the expected behaviour?

It should only be in Pinned messages if it's a pinned message

### How do you recreate this bug or crash?

Happens upon opening a DM that's in the pinned messages category

### Errors

![image](https://github.com/user-attachments/assets/c518a07e-c813-4ab9-85be-27741e45f597)
![image](https://github.com/user-attachments/assets/cae5a9e1-0888-4047-a04f-4aac26b4f1cc)
![image](https://github.com/user-attachments/assets/37b97e14-0f1d-49aa-bf8f-c1d6f059b3e4)
![image](https://github.com/user-attachments/assets/c1ee5880-a504-46b9-8dba-9467dc568b79)
![image](https://github.com/user-attachments/assets/4c6f4909-fa06-4655-83b0-f73de58d93d3)
![image](https://github.com/user-attachments/assets/b7b9450a-d707-4af2-885c-da26bcc8778b)

I'm not fully aware what "Discord Stable" is so forgive me if this report is in error. But i am using the plugin on Vencord for pinned messages and it links to this github page

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by jamesbt365** [comment]
Alongside you ignoring the contributor agreement, this is already fixed with 40a8cf1a85510f2b4c302e84a52946f7d63fe86e, which is on every platform but the chrome extension.

**Comment by santacapra** [comment]
Whoa, i did not ignore anything, I have no idea how this works lol. I thought i was being helpful
Also I don't know what Commit 40a8cf1 is, to me it looks like a bunch of code and idk how to implement it

**Comment by jamesbt365** [comment]
> Whoa, i did not ignore anything

![image](https://github.com/user-attachments/assets/19c14e6f-0c6a-4c15-b5bb-70475c5d9d20)
![image](https://github.com/user-attachments/assets/8600d1ba-e88c-4b5b-a6dc-955b00e991de)

> Also I don't know what Commit https://github.com/Vendicated/Vencord/commit/40a8cf1a85510f2b4c302e84a52946f7d63fe86e is, to me it looks like a bunch of code and idk how to implement it

Exactly the reason you are told to use the discord server for support.
