### ISSUE TITLE
[Bug] QuickReply moves caret to the beginning of the message.

### ISSUE THREAD

**Issue by ofluffydev** [Vendicated/Vencord#3085]
### What happens when the bug or crash occurs?

More of a programming logic bug and not a crashing one, but when you use quick reply in the middle of typing a message it will move your caret to the beginning of the message. Not the worst bug but I've done it like 10 times today on accident, it's getting pretty annoying.

### What is the expected behaviour?

When you activate quick reply with ctrl up/down it should preserve the location of the caret in the message.

### How do you recreate this bug or crash?

1. Type something into the message box
2. Attempt to use a quick reply
3. Caret at the beginning of the message...a 

### Errors

n/a

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [x] I have read the requirements for opening an issue above

**Comment by Sqaaakoi** [comment]
I'm currently trying to fix this. I can explain why this happens, and why this is slightly harder to fix than I initially thought.

The listener for the keyboard events is set on the document itself, but this occurs after we have a chance to cancel the browser moving the caret.

I'll still try to find a way to fix this though.

**Comment by Sqaaakoi** [comment]
i forgot preventDefault existed
