### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by MeguminSama** [Vendicated/Vencord#309]
### Want to contribute to Vencord?

Feature requests have moved to https://github.com/Vendicated/Vencord/discussions/categories/ideas

**Comment by ArjixWasTaken** [comment]
- [ ] Global Settings Sync (must be privacy-friendly. Password protected encryption perhaps?)

As for this one, do user notes sync?
Cause you can set a note for yourself, we could be storing the data to be synced there.

**Comment by MeguminSama** [comment]
In the process of moving these to Discussions, please could you repost that here: https://github.com/Vendicated/Vencord/discussions/313 :) Thanks!
