### ISSUE TITLE
[Bug] <title>Failed Vencord

### ISSUE THREAD

**Issue by Accelar17** [Vendicated/Vencord#3092]
### Discord Account

@accelar

### What happens when the bug or crash occurs?

![Снимок экрана 2024-12-19 211557](https://github.com/user-attachments/assets/922cc0a5-4bd9-4313-906d-22db7a31a2d3)

### What is the expected behaviour?

I just started the PC and went to discord, I see my theme is not working correctly, I go to the settings and it gives an error, I reinstalled discord and cleared the cache, but nothing helped

### How do you recreate this bug or crash?

I don't know

### Errors

```
Replace this text with your crash-log.
```
![изображение_2024-12-19_212832837](https://github.com/user-attachments/assets/39194aba-0536-4108-8997-bf2d07795c12)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
use our support channel
