### ISSUE TITLE
how to Run vencord locally ??

### ISSUE THREAD

**Issue by HaddajiDev** [Vendicated/Vencord#3113]
### Content

how to run vencord locally

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by nin0-dev** [comment]
It looks like you did not read the issue template as you have opened this issue, which suggests that you lack the ability to read through instructions (which in this case was to not use this form if you are not a maintainer). However, this skill is required to install a devbuild.

**Comment by Vendicated** [comment]
If you mean how to build it from source, check https://docs.vencord.dev/installing

But this is only recommended if you are a developer and know what you're doing. In any case, use our support channel instead of opening issues

**Comment by HaddajiDev** [comment]
i found no support in your support channel.. thank you though
