### ISSUE TITLE
Issue with PowerShell installer

### ISSUE THREAD

**Issue by wntiv-main** [Vendicated/Vencord#36]
The PowerShell installer has the following error
```
C:\Users\USER\Vencord\install.ps1 : Resources folder does not exist. Outdated version?
At line:1 char:1
+ C:\Users\USER\Vencord\install.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,install.ps1
```
This is caused by the wrong path being used. On line 69:
```
$resources = "$folder/resources"
```
This will produce a path like `C:/Users/USER/AppData/Local/app-VERSION/resources` when the data is actually in `C:/Users/USER/AppData/Local/Discord/app-VERSION/resources`. To fix this, line 69 should be changed to:
```
$resources = "$discord_root/$folder/resources"
```

**Comment by Vendicated** [comment]
🦀 🦀  Powershell installer is gone 🦀 🦀

**Comment by Ruthenic** [comment]
:crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab:

**Comment by MeguminSama** [comment]
🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀
