### ISSUE TITLE
you guys fucking closed my issue as "spam" while i was trying to make a comment

### ISSUE THREAD

**Issue by 3flowin** [Vendicated/Vencord#365]
like what?????

**Comment by somerandomcloud** [comment]
1. It wasnt an issue
2. It was informal as shit, the title was just mouth sounds

**Comment by MeguminSama** [comment]
Looks open to me. I am however going to close it as spam now.
![image](https://user-images.githubusercontent.com/27697325/209409857-8f70cb9b-275d-49cd-911a-2e8ac6675d3f.png)
