### ISSUE TITLE
Green ring of voice activity coming delayed after we speak

### ISSUE THREAD

**Issue by Harry830** [Vendicated/Vencord#372]
So whenever I join a call , when I speak , the green ring that indicates my voice detection is very delayed.

**Comment by ArjixWasTaken** [comment]
how is this a vencord bug?

**Comment by Harry830** [comment]
> how is this a vencord issue?
because it happened after installing vencord , not only me , all my friends

**Comment by ArjixWasTaken** [comment]
dunno how true the "not only me, but all my friends" statement is, but at least for me, it aint delayed

also, to prove that this is a vencord issue, you should have uninstalled vencord to see if that fixes the delay
I assume you didn't do that, so you are just making a wild guess that vencord is at fault.

**Comment by MeguminSama** [comment]
To diagnose the cause of the issue:

- Disable all plugins
- Fully close Discord
- Reopen

Does the issue still occur?

If yes, it's Discord.
If no, it's Vencord.

**Comment by ArjixWasTaken** [comment]
@MeguminSama well, there is the possibility that a plugin is not at fault, but vencord itself

in that case, disabling the plugins, and the delay persists, does not mean that it is discord's fault
it could still be vencord for all we know

Which I highly doubt, but let's be paranoid

**Comment by MeguminSama** [comment]
Vencord on its own does minimal changes to Discord itself

but yes all avenues should be tested as this is an issue people (myself included) run into a lot.

I still think it's a Discord issue, but there's no harm in testing.

**Comment by ArjixWasTaken** [comment]
> Vencord on its own does minimal changes to Discord itself

well, there aren't currently any plugins that mess with the audio, so disabling the plugins doesn't make sense
the only reasonable thing that the plugins might be at fault at is making the client lag more

which vencord itself could also be doing, thats my reasoning behind suggesting to uninstall vencord

(I also still think it is a discord issue, it could also be a CSS issue, did @Harry830 install themes? themes do cause lag)

**Comment by Harry830** [comment]
i did install amoled-cord theme (https://luckfire.github.io/amoled-cord/src/support/compiled.css)

**Comment by ArjixWasTaken** [comment]
that didn't really add a delay for me

actually, what do you mean by delay? can you record a video that shows it?
are you talking about the time it takes for the border to turn green? cause that is normal
or does it delay turning the border gray when not talking?

**Comment by Harry830** [comment]
so like , i speak and after like 0.5-2 second . then the border turns green and when i stop speaking , same after 0.5-2 sec it turns back from green

**Comment by aaxyi** [comment]
afaik it is a discord issue
i have this issue for years, maybe it's intentional

**Comment by abUwUser** [comment]
@Harry830 does this happen without Vencord on your machine?

**Comment by razzeking** [comment]
this is happening to me aswell and its only happening when having bd or vencord in this case insstalled

**Comment by Niclassslua** [comment]
A reinstall fixed the issue for me!

**Comment by MeguminSama** [comment]
Known Discord bug. Not caused by Vencord.
