### ISSUE TITLE
Crash or something i guess

### ISSUE THREAD

**Issue by TaxEvasiqn** [Vendicated/Vencord#377]
watch someone's stream in a vc then pop open to another tab then close that tab then discord just crashes and restarts

**Comment by MeguminSama** [comment]
This is a known Discord issue that has been happening for a long time, not a Vencord issue.

If you think otherwise, please try and get some error logs or something that identify that Vencord is the cause.

**Comment by TaxEvasiqn** [comment]
oh oops
