### ISSUE TITLE
REMOVE this exit shortcut

### ISSUE THREAD

**Issue by StabilityFuture** [Vendicated/Vencord#385]
https://github.com/Vendicated/Vencord/commit/15aa2299c3220aa5964981b0958338b6fad1d5b9
 Add Ctrl+Q Exit shortcut on Windows 

How to disable this feature? I don't want my discord closing when I do that on ANY OTHER APP!

**Comment by C10udburst** [comment]
<:trolley:1024751352028602449>

**Comment by MeguminSama** [comment]
Yeah idk why this was added as a default feature

**Comment by senkmen18** [comment]
+

**Comment by vanillyn** [comment]
yeah just make it ctrl + d

**Comment by Vendicated** [comment]
Ah, I didn't notice this works even when the app isn't focused, that's of course not good

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vendicated/Vencord/commit/ae9fe7fcfd49b6b178e55f36cc3d12e286a6134c
