### ISSUE TITLE
Blurry text on screen

### ISSUE THREAD

**Issue by CreepsoOff** [Vendicated/Vencord#412]
Hello, on the left is Discord, and on the right Vencord, with/without themes is the same, very blurry, how can I fix it? thank you.
![comparaison](https://user-images.githubusercontent.com/51055703/212431294-d5e69053-5305-429e-b344-4e2976abde8a.png)

**Comment by Vendicated** [comment]
Not caused by Vencord, it's your theme, system, ...

**Comment by CreepsoOff** [comment]
I have no themes on, and I have a 1920x1080 screen, both my external and internal (laptop) screen are blurry, with normal Discord it's fine, aswell with other clients, any ideas?

**Comment by Vendicated** [comment]
No idea. It'd be easier if you gave info about your system, branch etc

Also try updating your gpu driver and make sure you don't run Discord with weird flags or enabled experiments

**Comment by Vendicated** [comment]
also try disabling hardware acceleration in DIscord settings

**Comment by CreepsoOff** [comment]
> also try disabling hardware acceleration in DIscord settings

It was only that... I'm sorry for disturbing, thanks for the help. (and also I didn't see that I shouldn't report issues on Canary, it's my bad, thanks for the help tho, it got resolved !)

**Comment by Vendicated** [comment]
No worries, you're welcome!
