### ISSUE TITLE
Patcher Error

### ISSUE THREAD

**Issue by zachjmurphy** [Vendicated/Vencord#42]
With the commit 88542b9ede71fd89b1edef41175131aa0dc5027f

You now get this error when attempting to patch: 
![image](https://user-images.githubusercontent.com/114436131/193920057-aeeb9f29-8a9f-4ff0-9e91-cc79a8ed1d44.png)

**Comment by Vendicated** [comment]
pnpm run patch*

**Comment by zachjmurphy** [comment]
> 

![image](https://user-images.githubusercontent.com/114436131/193920541-38278c13-6b86-41bf-bc90-e3a64615c5e2.png)

**Comment by Ruthenic** [comment]
no `pnpm patch` works as well

**Comment by zachjmurphy** [comment]
`pnpm patch` isn't functional for me.

**Comment by Ruthenic** [comment]
`pnpm patch` and `pnpm run patch` do the same thing

**Comment by zachjmurphy** [comment]
> 

![image](https://user-images.githubusercontent.com/114436131/193920661-0b1c32d2-4ef4-4849-9894-22fb7baa7a42.png)

**Comment by Ruthenic** [comment]
actually that's really goofy, `pnpm run patch` should work

**Comment by zachjmurphy** [comment]
> actually that's really goofy, `pnpm run patch` should work

`pnpm run patch` seems to work
