### ISSUE TITLE
fakeNitro plugin conflicts with reactions

### ISSUE THREAD

**Issue by ikrishagarwal** [Vendicated/Vencord#427]
### Issue 

The FakeNitro plugin unlocks all of the locked emojis for reactions too but if you try to use it nothing will happen. In my case, I have many servers having the same emojis with the same name, so within a server it becomes a tough task to find the correct emojis which correspond to the same server.

### Possible Fix
1. You can sort the emojis server-wise, like how the default emoji modal works, and implement the same when we search for emojis.
2. Don't run the code when the user has opened the reaction emoji modal.
3. Chop the unavailable emojis and just don't show them.

*The second fix is the best according to me.*

**Comment by Delphox** [comment]
If this is implemented, please do it with a toggle. Using unavailable reactions is useful to quickly and stealthly check if you're blocked by someone (as the blocked user check that shakes the screen has priority over the emoji availability check).

**Comment by Vendicated** [comment]
should be fixed now
