### ISSUE TITLE
[Bug] last update broke reactions

### ISSUE THREAD

**Issue by Kirihan** [Vendicated/Vencord#458]
### Discord Account

Aleister#3982

### What happens when the bug or crash occurs?

Updated once again an hour ago and when i click on a reaction i dont see it highlighted as reacted and the number doesnt change but when I hover over it it shows i've reacted.

1 react (not mine):
![image](https://user-images.githubusercontent.com/45792238/214975150-21eaba87-e89c-4841-b4aa-252af1feeca4.png)

2 react (reacted and it doesnt update)
![image](https://user-images.githubusercontent.com/45792238/214975266-063e41be-6dc8-4606-86f4-d3c8126fea80.png)

and after i react again the reaction dissapears till I restart the client.

### What is the expected behaviour?

React highlights when reacted and user reacted count increases

### How do you recreate this bug or crash?

1. look for someone's reaction.
2. react to it.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Stock discord bug
