### ISSUE TITLE
[Bug] QuickCSS :has() selector doesn't work

### ISSUE THREAD

**Issue by RobertRR11** [Vendicated/Vencord#506]
### Discord Account

RobertR11#7841

### What happens when the bug or crash occurs?

Using the CSS :has() selector in the QuickCSS editor doesn't do anything. Other selectors like :not() do work though.

Example of :has() that removes the nitro button above the direct messages list, which does work in other CSS editors like Stylus, but not in Vencord:
```css
.channel-1Shao0:has(a[href="/store"]) {
    display: none;
}
```

### What is the expected behaviour?

I expect the :has() selector to properly apply to elements.

### How do you recreate this bug or crash?

1. Open Vencord settings
2. Open the QuickCSS editor from quick actions
3. Write CSS that uses a :has() selector, like in the example above
4. Observe that nothing happens

### Errors

```
none
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Captain8771** [comment]
:has() is not implemented on the electron version discord runs on (Electron v13 iirc). However, discord canary has switched to electron 22 so we may be seeing it come very soon.

**Comment by RobertRR11** [comment]
I have just downloaded and tested canary and it does work there, so I guess I'll have to wait for stable to update.

**Comment by RobertRR11** [comment]
This issue is already closed and not related to Vencord, but I just wanted to mention that Discord has now updated electron on the stable channel and the :has() selector now works.
