### ISSUE TITLE
[very small Bug] Plugin settings toggle buttons do not have "checked" class when toggled

### ISSUE THREAD

**Issue by refact0r** [Vendicated/Vencord#509]
### Discord Account

refact0r#1494

### What happens when the bug or crash occurs?

Unlike the vencord and updater pages, the toggle buttons on the plugins page don't get a `checked-16gMAN` class when toggled on. This means that themes can't change the color of the button when toggled on. (i hate green)

### What is the expected behaviour?

The toggle button should have 
`class="container-1QtPKm default-colors checked-16gMAN"` when toggled on
`class="container-1QtPKm default-colors"` when toggled off

### How do you recreate this bug or crash?

Open plugins page

### Errors

None

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
can't you just use the css :checked pseudoclass

**Comment by refact0r** [comment]
i don't think so because the checkbox's container div has the color, not the checkbox itself

**Comment by unlwly** [comment]
I also noticed this because my theme didn't do the thing with the thing and then the thing looks bad (green >:()

**Comment by ArjixWasTaken** [comment]
> i don't think so because the checkbox's container div has the color, not the checkbox itself

`:has` is what you want, dunno about electron compatibility tho

**Comment by lewisakura** [comment]
> > i don't think so because the checkbox's container div has the color, not the checkbox itself
> 
> `:has` is what you want, dunno about electron compatibility tho

#506 - its only available on canary as of present, electron 13 doesn't have it
