### ISSUE TITLE
[Bug] Crash error

### ISSUE THREAD

**Issue by uhlow** [Vendicated/Vencord#523]
### Discord Account

low#6421

### What happens when the bug or crash occurs?

When i press any button about vencord in the settings tab my discord just crash. I was enabling some plugins and then after i enable and restarted the discord started to bug out. My friend installed vencord at the same time and the same thing was happening. Everything isn't working only the button "updater" is working.

### What is the expected behaviour?

Not crash and work just fine.

### How do you recreate this bug or crash?

1. Go to discord settings
2. Click any button related to vencord
3. Crash

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by MeguminSama** [comment]
#522
