### ISSUE TITLE
Discord Crashes whenever i click anything that has to do with Vencord

### ISSUE THREAD

**Issue by blozheadz77821** [Vendicated/Vencord#527]
### Discord Account

SilverEra#1828

### What happens when the bug or crash occurs?

Ever since Vencord has needed to update, whenever I hit any button that has to do with vencord it crashes.

### What is the expected behaviour?

Vencord should be opening menus as usual, but it crashes whenever I hit anything that has to do with it

### How do you recreate this bug or crash?

Wait until Vencord needs an update. Then, just hit any vencord button.

### Errors

There's no logs???

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by MeguminSama** [comment]
Update vencord using the GUI installer
