### ISSUE TITLE
vencord broken atm

### ISSUE THREAD

**Issue by ogmicco** [Vendicated/Vencord#535]
discord crashes when clicking any of these:
![image](https://user-images.githubusercontent.com/107354268/221418927-5dbb6585-340e-4b46-8765-3a0f22de2d54.png)
![image](https://user-images.githubusercontent.com/107354268/221418949-009d6809-c08c-4fbc-aeea-7d23b6a4e887.png)

### Request Agreement

- [X] This is not a support or plugin request

**Comment by somerandomcloud** [comment]
update Vencord using the rightmost button (that says "Update") in the installer

**Comment by ogmicco** [comment]
tried that, didn't fix it. my friend also has vencord and he's having the same issue

**Comment by somerandomcloud** [comment]
are you possibly on canary??

**Comment by somerandomcloud** [comment]
We really need templates lmfao. 

What platform are you on?
What client are you using? (desktop/web/armcord/...)
What discord are you using? (stable/canary/ptb)
Are there any errors in console? (CTRL + SHIFT + I). If there is any red text that might relate to vencord, post them here

**Comment by ogmicco** [comment]
platform: w10
client: desktop
release: stable

error:
28d2894a3ee59d7bcf93.js:8755 Error: Vencord could not find the Card Component
    at o (internal.tsx:26)
    at Sa (28d2894a3ee59d7bcf93.js:1608)
    at yu (28d2894a3ee59d7bcf93.js:1662)
    at Oc (28d2894a3ee59d7bcf93.js:1655)
    at Ic (28d2894a3ee59d7bcf93.js:1655)
    at hc (28d2894a3ee59d7bcf93.js:1654)
    at ic (28d2894a3ee59d7bcf93.js:1651)
    at uc (28d2894a3ee59d7bcf93.js:1652)
    at Fo (28d2894a3ee59d7bcf93.js:1591)
    at 28d2894a3ee59d7bcf93.js:1649
r.<computed> @ 28d2894a3ee59d7bcf93.js:8755
ds @ 28d2894a3ee59d7bcf93.js:1616
Es.i.componentDidCatch.n.callback @ 28d2894a3ee59d7bcf93.js:1617
Bi @ 28d2894a3ee59d7bcf93.js:1598
Tu @ 28d2894a3ee59d7bcf93.js:1646
Ou @ 28d2894a3ee59d7bcf93.js:1646
mu @ 28d2894a3ee59d7bcf93.js:1646
(anonymous) @ 28d2894a3ee59d7bcf93.js:1657
vc @ 28d2894a3ee59d7bcf93.js:1658
uc @ 28d2894a3ee59d7bcf93.js:1652
Fo @ 28d2894a3ee59d7bcf93.js:1591
(anonymous) @ 28d2894a3ee59d7bcf93.js:1649
28d2894a3ee59d7bcf93.js:1853 POST https://discord.com/api/v9/metrics net::ERR_BLOCKED_BY_CLIENT
O._end @ 28d2894a3ee59d7bcf93.js:1853
O.end @ 28d2894a3ee59d7bcf93.js:1851
(anonymous) @ 28d2894a3ee59d7bcf93.js:1857
i.then @ 28d2894a3ee59d7bcf93.js:1857
I @ 28d2894a3ee59d7bcf93.js:8645
(anonymous) @ 28d2894a3ee59d7bcf93.js:8646
T @ 28d2894a3ee59d7bcf93.js:8646
t._flush @ 28d2894a3ee59d7bcf93.js:5563
t.increment @ 28d2894a3ee59d7bcf93.js:5563
(anonymous) @ 28d2894a3ee59d7bcf93.js:2325
E @ 28d2894a3ee59d7bcf93.js:1074
h @ 28d2894a3ee59d7bcf93.js:1074
T @ 28d2894a3ee59d7bcf93.js:1075
o.componentDidCatch @ 28d2894a3ee59d7bcf93.js:2325
Es.i.componentDidCatch.n.callback @ 28d2894a3ee59d7bcf93.js:1617
Bi @ 28d2894a3ee59d7bcf93.js:1598
Tu @ 28d2894a3ee59d7bcf93.js:1646
Ou @ 28d2894a3ee59d7bcf93.js:1646
mu @ 28d2894a3ee59d7bcf93.js:1646
(anonymous) @ 28d2894a3ee59d7bcf93.js:1657
vc @ 28d2894a3ee59d7bcf93.js:1658
uc @ 28d2894a3ee59d7bcf93.js:1652
Fo @ 28d2894a3ee59d7bcf93.js:1591
(anonymous) @ 28d2894a3ee59d7bcf93.js:1649
28d2894a3ee59d7bcf93.js:1853 POST https://discord.com/api/v9/metrics net::ERR_BLOCKED_BY_CLIENT

**Comment by Vendicated** [comment]
this issue has already been fixed and fixes are mentioned everywhere on the Discord, and you didn't even use the correct issue template. Please at least put in some effort to fix your issues yourself
