### ISSUE TITLE
[Bug] Rendering error

### ISSUE THREAD

**Issue by Wh1rr** [Vendicated/Vencord#549]
### Discord Account

Whirr#4387

### What happens when the bug or crash occurs?

When in settings, under any of the vencord tabs, nothing is rendered apart from an error box.

### What is the expected behaviour?

Rendering the component

### How do you recreate this bug or crash?

1. Go to settings
2. Click on one of the Vencord settings

### Errors

```
TypeError: Cannot read property 'TOP' of undefined
    at Z1 (index.tsx:64)
    at Sa (3ce5a3a3ee1992708511.js:1654)
    at yu (3ce5a3a3ee1992708511.js:1708)
    at Oc (3ce5a3a3ee1992708511.js:1701)
    at Ic (3ce5a3a3ee1992708511.js:1701)
    at hc (3ce5a3a3ee1992708511.js:1700)
    at ic (3ce5a3a3ee1992708511.js:1697)
    at uc (3ce5a3a3ee1992708511.js:1698)
    at Fo (3ce5a3a3ee1992708511.js:1637)
    at 3ce5a3a3ee1992708511.js:1695
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Seath1337** [comment]
same here...

**Comment by itsnotrin** [comment]
On linux (Fedora)- not working for me either.
No errors in the terminal if I launch it through there but discord still errors out.
I get this in dev tools on discord:

![image](https://user-images.githubusercontent.com/30768410/222256134-40db9e95-735a-47d6-8bdc-ab4e4fea2a15.png)
