### ISSUE TITLE
[Bug] Invisible Chat not working

### ISSUE THREAD

**Issue by TanukiAI** [Vendicated/Vencord#560]
### Discord Account

Tami#7071

### What happens when the bug or crash occurs?

There is no Invisible Chat Icon to use (and the plugin has no other options than setting a password so it is enabled)

### What is the expected behaviour?

Show the Invisible Chat icon ^^

### How do you recreate this bug or crash?

1. Install Vencord
2. Enable Invisible Chat
3. No Button

### Errors

```
No crash
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by SammCheese** [comment]
#566 will fix this issue, wait for it to be merged
