### ISSUE TITLE
[Bug] MessageLogger Bug

### ISSUE THREAD

**Issue by icdmkg2** [Vendicated/Vencord#573]
### Discord Account

Or#4429

### What happens when the bug or crash occurs?

Logs that the message logger has saved are not showing up.

### What is the expected behaviour?

for the logs to show up after a restart 

### How do you recreate this bug or crash?

1.Message someone and delete the messages
2. Force quit discord (restart your pc or alt f4)
3. Go back to that dm 

Note: the bug happens some time and not always

### Errors

None

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by somerandomcloud** [comment]
Not a bug. Won't be resolved

**Comment by ArjixWasTaken** [comment]
> Logs that the message logger has saved are not showing up.

the message logger doesnt even save any logs, so you are lying
