### ISSUE TITLE
[Suggestion/Idea] Put all discord user settings to tabs

### ISSUE THREAD

**Issue by emir4169** [Vendicated/Vencord#58]
It would be interesting to have a plugin/css that puts all the discord user settings within tabs in the discord home menu.

**Comment by Vendicated** [comment]
I still don't know what exactl you mean by this, could you please elaborate / show a mockup?

**Comment by emir4169** [comment]
![image](https://user-images.githubusercontent.com/89991965/197377129-3f6e27ae-61c4-466e-b800-b82e6cf8b9d5.png)
this is a mockup that i screenshotted from my browser
it works well to show what i mean just pretend that each tab is a different setting and you get it

**Comment by ItzOnlyAnimal** [comment]
do you mean this?
![image](https://user-images.githubusercontent.com/24845294/197377468-346a3243-81c9-46bf-98aa-8fc38f2d93bd.png)

**Comment by emir4169** [comment]
> do you mean this? ![image](https://user-images.githubusercontent.com/24845294/197377468-346a3243-81c9-46bf-98aa-8fc38f2d93bd.png)
no

**Comment by kekkodance** [comment]
then what??

:trollface:

**Comment by emir4169** [comment]
![image](https://user-images.githubusercontent.com/89991965/197579367-e8f66cd4-2188-4622-8505-daf11b4c9cbe.png)
these

**Comment by MeguminSama** [comment]
Please do an actual mockup, otherwise nobody will have any idea what you're asking for. Otherwise, I'll probably close this issue.

**Comment by kekkodance** [comment]
![image](https://user-images.githubusercontent.com/53054786/197580670-7b674691-3683-4b63-84b1-1e65148933ff.png)
 it already exists???

**Comment by ActuallyTheSun** [comment]
think they mean something like the BD ChannelTabs plugin (cant find any ss anywhere and its been dead since swc)

**Comment by emir4169** [comment]
making a real mockup

**Comment by emir4169** [comment]
[THE MOCKUP IS REAL](https://i.upload.systems/RFYAkW8F)

**Comment by emir4169** [comment]
its not that finished

**Comment by emir4169** [comment]
but i did do it
(even tho i only did one part of it rn but it gives the idea)

**Comment by emir4169** [comment]
[ITS REAL INSIDE A DISCORD TAB OMG](https://i.upload.systems/L312KDD5)

**Comment by MeguminSama** [comment]
Third party CDN so re-uploading to github in case it gets deleted serverside

![image](https://user-images.githubusercontent.com/27697325/200840817-8d613d85-6f7d-4f5a-8a70-97caa884309d.png)

**Comment by emir4169** [comment]
i am going to explode

**Comment by somerandomcloud** [comment]
This can be done with CSS. Aka making it a plugin would be redundant asf. This issue should be closed as it isnt a plugin req

**Comment by Vendicated** [comment]
there are already themes doing things like this
