### ISSUE TITLE
[Bug] discord thinks it's in browser

### ISSUE THREAD

**Issue by nikorue** [Vendicated/Vencord#584]
### What happens when the bug or crash occurs?

keybinds not supported
no window control buttons
every other browser thing

### What is the expected behaviour?

normal discord windows client behaviour

### How do you recreate this bug or crash?

patch discord version 5341902 with installer 253183a
open discord

### Errors

```
VM75 renderer_init.js:93 Unable to load preload script: C:\Users\mattis\AppData\Roaming\Vencord\dist\preload.js
(anonymous) @ VM75 renderer_init.js:93
VM75 renderer_init.js:93 Error: ENOENT: no such file or directory, open 'C:\Users\mattis\AppData\Roaming\Vencord\dist\renderer.css'
    at Object.openSync (VM45 fs.js:476)
    at Object.func [as openSync] (VM70 asar_bundle.js:5)
    at readFileSync (VM45 fs.js:377)
    at e.readFileSync (VM70 asar_bundle.js:5)
    at Object.<anonymous> (preload.ts:48)
    at Object.<anonymous> (preload.ts:34)
    at Module._compile (VM43 loader.js:1078)
    at Object.Module._extensions..js (VM43 loader.js:1108)
    at Module.load (VM43 loader.js:935)
    at Module._load (VM43 loader.js:776)
(anonymous) @ VM75 renderer_init.js:93
5fb40bbd35d3eeebea90.js:103 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 5fb40bbd35d3eeebea90.js:103
    at async Promise.all (index 3)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by nikorue** [comment]
redownloaded installer
![image](https://user-images.githubusercontent.com/67581183/223739277-e40fa7e0-fd17-4073-b2fc-0badc4aeaa46.png)
same results with this

**Comment by Captain8771** [comment]
Just to make sure, did you try this?
![image](https://user-images.githubusercontent.com/81252038/223748774-9ed3f7ff-41d2-49aa-9044-9b3092ade1b0.png)

**Comment by Vendicated** [comment]
Your install is missing files. Make sure you're using the latest Installer and reinstall / redownload files
