### ISSUE TITLE
[Bug] Issues with snapping / fancy zones

### ISSUE THREAD

**Issue by KoBruh** [Vendicated/Vencord#588]
### Discord Account

OhHim!#0777

### What happens when the bug or crash occurs?

The bug in question is when vencord is enabled discord loses its ability to snap to sides of the screen or be used by fancy zones.

https://user-images.githubusercontent.com/42637159/223917723-650e2cf6-79a6-4b1d-8091-f4dcf346e270.mp4

https://user-images.githubusercontent.com/42637159/223918150-417605a6-9ad1-4487-b1fb-695b56c7b729.mp4

### What is the expected behaviour?

The expected behavior is that discord will snap to the sides of the screen or be able to be changed with fancy zones

### How do you recreate this bug or crash?

1. Have vencord enabled
2. Try to snap discord to the side of the screen
3. it doesn't work

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Works fine for me 

https://user-images.githubusercontent.com/45497981/223918944-445f79bb-70cd-4529-8bcb-be75a0d0f692.mp4

**Comment by KoBruh** [comment]
Sorry about fucking up the title, what more info could i provide for this, its a practically fresh install of the program, the only setting i have changed is the transparency setting, turned from off to on

**Comment by Vendicated** [comment]
It seems to work fine in ur video also. The first time it doesnt work but then it correctly swaps into place

**Comment by KoBruh** [comment]
i attached two videos, one where the behavior was normal ( vencord was not "injected" using the flag vanilla ) and where the behavior was weird ( vencord was injected )

**Comment by Vendicated** [comment]
At 00:05 in the first video it correctly snaps into place. What do you expect to be different there?

**Comment by KoBruh** [comment]
The window to resize like in the second window, let me attach a video super quick, Video 1 incorrect behavior. Video 2 correct behavior

https://user-images.githubusercontent.com/42637159/223923277-55eb6553-b6ae-48b4-bfe2-9854c6f30fc4.mp4

https://user-images.githubusercontent.com/42637159/223924049-2d1e1e22-28db-4fe0-8164-726ddb85e548.mp4

**Comment by KoBruh** [comment]
Video 2 was cut really short and im not 100% sure why, but fancy zones resizes the window to fit in the specified area

**Comment by Vendicated** [comment]
have you tried disabling transparency? also what plugins do you have enabled? Just run /vencord-debug in the support channel and ping me

**Comment by KoBruh** [comment]
disabling transparency has solved the issue, but does this mean its an issue with transparency, or is it working as intended ?

**Comment by Vendicated** [comment]
issue with transparency but out of our control https://github.com/electron/electron/issues/6107#issuecomment-226989722

**Comment by KoBruh** [comment]
Ahhhh good ol electron, thank you Ven you qtpie
