### ISSUE TITLE
[Bug][Plugin: NoBlockedMessages] Prevent blocked messages from triggering unread messages indicator

### ISSUE THREAD

**Issue by Pheromir** [Vendicated/Vencord#594]
### What happens when the bug or crash occurs?

Hidden blocked messages still trigger the unread messages indicator (red line/highlighted channel name), even with the "Completely ignores (recent) incoming messages from blocked users (locally)."-Setting enabled.
![grafik](https://user-images.githubusercontent.com/13359741/224510135-cf4994fd-5404-464e-b629-aef9ea6e9865.png)

### What is the expected behaviour?

Don't show the unread message indicator if the new message is blocked.
(idk if thats possible to prevent, would be cool)

### How do you recreate this bug or crash?

1. Enable NoBlockedMessages Plugin and restart Discord/Vencord
2. Block someone
3. Wait until the blocked Person writes something in another channel or while discord is not focused

### Errors

(none)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by VXsz** [comment]
Still happening, a gap also remains between the last message (when it's from me) and the textbox, once the red line disappears (so the same bug is still happening, basically).

**Comment by Fabian42** [comment]
Currently still happening, also day markers are not hidden (not sure if that's considered a separate bug):

<img width="153" height="256" alt="Image" src="https://github.com/user-attachments/assets/cb530662-6b9b-4373-9c0a-4191ad4925c1" />

**Comment by Selectively1** [comment]
Still happening. Additionally, this plugin needs to suppress replies to blocked users and reactions from blocked users to be truly useful.
