### ISSUE TITLE
[Bug] FakeNitro plugin confused about Guild ID when using Favorites experiment

### ISSUE THREAD

**Issue by Matojeje** [Vendicated/Vencord#598]
### Discord Account

Mato#2099

### What happens when the bug or crash occurs?

When sending an emoji through the experimental "Favorites server" feature, FakeNitro replaces even the text channel's regular custom emojis (that could've been normally sent) with image links.

I guess it's got to do something with the [`guildId`](https://github.com/Vendicated/Vencord/blob/471761209081f5184b4310cea5c7c4441995011d/src/plugins/fakeNitro.ts#L186) function since the URL structure is a bit different, the plugin's expecting **/channels/*guildID*/*channelID*** but is getting **/channels/@favorites/*channelID*** instead, so the function returns `@favorites` as the detected guild ID.

Checks like `emoji.guildId === guildId` might have to be edited too. The same thing might also apply to stickers

Also, I understand that this is an alpha feature, even though the experiment is over a year old, but either way feel free to disregard this issue if deemed too unstable / cutting-edge

### What is the expected behaviour?

The message should be sent as is, not replacing any guild specific emojis with image links

### How do you recreate this bug or crash?

Set up

1. Enable Experiments plugin
2. Find experiment `2021-09_favorites_server` "Enable fancy super-alpha favorites server"
3. Set bucket override to Treatment 1 "on"
4. Go to any guild that has custom non-animated emoji
5. Add a text channel from that guild to the favorites server (right-click menu)

The bug itself

6. Inside the favorites server, go to the newly added text channel shortcut
7. Send a message with a custom non-animated emoji from the text channel's guild

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by ArjixWasTaken** [comment]
> I guess it's got to do something with the [guildId](https://github.com/Vendicated/Vencord/blob/471761209081f5184b4310cea5c7c4441995011d/src/plugins/fakeNitro.ts#L186) function since the URL structure is a bit different, the plugin's expecting /channels/guildID/channelID but is getting /channels/@favorites/channelID instead, so the function returns @favorites as the detected guild ID.

Funnily enough, even if we use the official way of getting the current guild id and not my "hack", it is still `@favorites`.

![image](https://user-images.githubusercontent.com/53124886/224575839-0780a615-51e6-4432-9627-b87b7bdb32bd.png)

**Comment by ArjixWasTaken** [comment]
We can just add an edge case though, and get the `guild_id` this way

![image](https://user-images.githubusercontent.com/53124886/224575984-4457ceb9-ad23-482f-9974-acf3cd59f0ba.png)

**Comment by ArjixWasTaken** [comment]
or well, the second way of getting the `guild_id` consistently works, so we could replace the original method, but I don't know how efficient that would be

**Comment by ArjixWasTaken** [comment]
```js
function getGuildId() {
    const id = window.location.href.split("channels/")[1].split("/")[0];
    return /\d+/.test(id) ? id : Vencord.Webpack.Common.ChannelStore.getChannel(Vencord.Webpack.Common.SelectedChannelStore.getChannelId()).guild_id;
}
```

smth like this works ig, we could just check if the id is not in a list of known invalid ids, but that is not future proof, so I opted into using regex

**Comment by ArjixWasTaken** [comment]
I'm too lazy to make this into a PR, so I leave this up to anyone that wants to do this.

**Comment by Vendicated** [comment]
just use
https://github.com/Vendicated/Vencord/blob/471761209081f5184b4310cea5c7c4441995011d/src/utils/discord.ts#L26-L28

**Comment by ArjixWasTaken** [comment]
or that
