### ISSUE TITLE
[Feature Request] MessageLogger log

### ISSUE THREAD

**Issue by GeorgeV220** [Vendicated/Vencord#601]
### Discord Account

GeorgeV22#3200

### What is it that you'd like to see?

I think it would be nice if the messagelogger could keep a log of the messages that were deleted/edited and not be lost after the client is restarted. For example how messagelogger worked on betterdiscord.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
![Screenshot_20230314-170804_Bromite](https://user-images.githubusercontent.com/45497981/225067193-e50c7ec6-f2a5-4a8b-9e33-071918edf2bb.png)

Use discussions please. This has also already been suggested multiple times
