### ISSUE TITLE
[Feature Request] Improve Theme Tab

### ISSUE THREAD

**Issue by Vendicated** [Vendicated/Vencord#614]
### Discord Account

yours truly

### What is it that you'd like to see?

The current theme tab works but isn't very user friendly

It would be nicer to add a more friendly interface that allows you to
- toggle themes
- upload a local theme file so users can just download from the BD site
    - On native we could store these in the Vencord folder
    - On web we could store these with the DataStore api (indexed db)
    - Would be best to introduce the following 3 ipc methods for this:
        - Add theme
        - Remove theme
        - Get all themes
- edit themes uploaded with feature 2 (just reuse already existing Monaco editor used for QuickCss) 

### Request Agreement

- [X] This is not a plugin request

**Comment by 3kh0** [comment]
Having a simple list of some common themes to have on hand would be helpful. I could try to make a site to list themes for vencord, this would allow to browse themes, preview it with gibbu.github.io/ThemePreview and have a button to copy the css file to import it to vencord, if you are intrested, let me know and I will start work on it.

**Comment by lewisakura** [comment]
> Having a simple list of some common themes to have on hand would be helpful. I could try to make a site to list themes for vencord, this would allow to browse themes, preview it with gibbu.github.io/ThemePreview and have a button to copy the css file to import it to vencord, if you are intrested, let me know and I will start work on it.

Having a list tends to get heavily opinionated and feels like a lot of bloat when users tend to know what they're looking for already. Also, most people are importing BD themes so there's not much point in us running a list of our own.

**Comment by 3kh0** [comment]
@lewisakura I get your point, but importing themes just does feel that streamlined

**Comment by MeguminSama** [comment]
@SpirTBBX https://github.com/Vendicated/Vencord/pull/635

**Comment by SpirTBBX** [comment]
That is exactly what I and other users are looking for! Great job

**Comment by ArcWandx86** [comment]
In addition to themes in general, I think it would be a good idea have useful themes in the theme tab with toggle switches, similar to the plugins tab. There have been several requests for plugins that could be implemented by a snippet in the user's quickCSS; by having the most commonly used snippets as "themes" several such requests can be eliminated.
