### ISSUE TITLE
[Feature Request] Allow running Vencord on older macOS versions (<=11.7.4)

### ISSUE THREAD

**Issue by Vilagamer999** [Vendicated/Vencord#621]
### What is it that you'd like to see?

When oppening the latest macOS build for vencord I was prompted by the system message below, I am currently on macOS BigSur 11.6.2 (as you can see in the error) and would like to use vencord without having to update my OS.
Another user was having the same problem in issue #331 but it was never resolved, I am not asking support for super old macOS versions but atleast support for macOS 10.15.7 and 11.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/30276916/226390523-6d14224b-8a38-4a2b-ac5b-ccc52565af0e.png">

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
you can build from source and it should work, follow the instructions in the readme

**Comment by Vendicated** [comment]
Hmm, I wonder what adds that, since it's not actually in our list file. And the build workflow just zips the program

https://github.com/Vencord/Installer/blob/main/macos/Info.plist

**Comment by Vendicated** [comment]
if you could figure out what exactly adds that requirement and could contribute a fix, that would be appreciated. I don't own a Mac personally. You can find the build logic here https://github.com/Vencord/Installer/blob/main/.github/workflows/release.yml#L65-L117

**Comment by Vilagamer999** [comment]
> Hmm, I wonder what adds that, since it's not actually in our list file. And the build workflow just zips the program
> 
> [Vencord/Installer@`main`/macos/Info.plist](https://github.com/Vencord/Installer/blob/main/macos/Info.plist?rgh-link-date=2023-03-20T16%3A14%3A37Z)

I've changed the plist for now (https://github.com/Vencord/Installer/pull/26), it should set the minimum requirement to macOS Catalina as described, I'lll have a look into the build logic to see if there's anything that changes the version...

Vencord has been running on "unsupported hardware" so far without any errors.
