### ISSUE TITLE
[Feature Request] Multiple Themes

### ISSUE THREAD

**Issue by Tawnee323** [Vendicated/Vencord#625]
### Discord Account

-kiwi-#1337

### What is it that you'd like to see?

It would be very nice to be able to use multiple themes at the same time. I'm unsure if this is already being worked on, but I couldn't find any issue. This would be awesome, thanks!

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
this is already a feature, just paste multiple links

**Comment by Tawnee323** [comment]
oh I didn't know that, thanks!
