### ISSUE TITLE
[Bug] MessageClickActions uses different key than description of plugin

### ISSUE THREAD

**Issue by slinkstr** [Vendicated/Vencord#627]
### What happens when the bug or crash occurs?

Description of plugin and plugin function do not match.

### What is the expected behaviour?

Holding delete should enable quick delete or description should be changed to say backspace.

### How do you recreate this bug or crash?

1. Enable MessageClickActions
2. Hold DEL and click a message - no delete
3. Hold Backspace and click a message - deletes

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vendicated/Vencord/commit/d482d33d6f93632b1277524efc5aa392f596f095, thank you

**Comment by KaKi87** [comment]
Hello,

How about actually supporting the `Delete` key instead of or additionally to the `Backspace` key ?

Because using the latter is unusual compared to other Discord plugin systems, and it makes the user delete their draft message when they have one.

Thanks

**Comment by Vendicated** [comment]
#655

**Comment by KaKi87** [comment]
Interesting, but in this case it could be done way faster by adding an OR condition to the following lines :

https://github.com/Vendicated/Vencord/blob/7c563471f686a3b6cffb0fe13d07a5b5eaf0ebe7/src/plugins/messageClickActions.ts#L27-L28

Would you accept a PR ?
