### ISSUE TITLE
[Bug] Tag creation bugged

### ISSUE THREAD

**Issue by MeguminSama** [Vendicated/Vencord#644]
### Discord Account

me

### What happens when the bug or crash occurs?

When making a new tag e.g. `/tags create test test`, it bugs out & also says it was created by a random user.
![image](https://user-images.githubusercontent.com/27697325/226668811-96730b59-d233-40ee-b519-7a10ac60af58.png)

Also happens when doing other tag related commands

![image](https://user-images.githubusercontent.com/27697325/226669033-21049720-9a6f-40aa-8d47-a788f1bc0d28.png)

### What is the expected behaviour?

Not that:tm:

### How do you recreate this bug or crash?

^

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by roblox-codex** [comment]
When the program bugs out and says that the tag was created by a random user, it is possible that the bug is related to how the program handles user authentication and authorization. It is also possible that the bug is related to how the program stores or retrieves data related to tag creation.
