### ISSUE TITLE
[Bug] Restarting bugs out the client

### ISSUE THREAD

**Issue by Derbosik** [Vendicated/Vencord#650]
### Discord Account

Yeleha#3469

### What happens when the bug or crash occurs?

When adding a plugin and hitting 'Restart' makes it, so that when I join a VC, I can't see my microphone activity on my taskbar correctly. This is mitigated by exiting discord through the taskbar, tho it's kinda annoying.

### What is the expected behaviour?

I expect Vencord to do a better job restarting the app, like having an external program shut it down and open it back up again or some other solution.

### How do you recreate this bug or crash?

1. Install a plugin
2. Click restart
3. Join a VC
4. Click out of discord and observe the microphone activity not work while you're talking.

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Wha

**Comment by Vendicated** [comment]
This is totally unrelated to Vencord, if anything it's a Discord bug

**Comment by Derbosik** [comment]
When discord is restarted normally, by exiting it from the tray then its working fine, so it could be mitigated 🤔

**Comment by lewisakura** [comment]
Vencord already uses the methods Discord uses to restart. It's a Discord bug if it doesn't work correctly.
