### ISSUE TITLE
[Bug] client themes not working in vencord web (fakenitro)

### ISSUE THREAD

**Issue by localwhale20** [Vendicated/Vencord#651]
### Discord Account

danilwhale#6776

### What happens when the bug or crash occurs?

when i enable theme in appearance then it disables automatically after some moments to it's defualt variant

### What is the expected behaviour?

client theme must enable and not disable automatically

### How do you recreate this bug or crash?

preinstall fakenitro

1. open settings
2. open appearance
3. select client theme you want
4. after some moments it'll go back to default variant

### Errors

```
[discord_protos.discord_users.v1.PreloadedUserSettings] Updating appearance with delay 0
da729337be4af51ed6b5.js:5163 [discord_protos.discord_users.v1.PreloadedUserSettings] Scheduling save from markDirty
da729337be4af51ed6b5.js:5163 [discord_protos.discord_users.v1.PreloadedUserSettings] Persisting proto
```

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by BloodyToolzz** [comment]
It's for everyone using fakenitro plugin. I guess Discord patched this. Probably after seeing No Text to Speech's video lol.

**Comment by Nuckyz** [comment]
Don't worry, that can be fixed

**Comment by SylvKT** [comment]
This happens on the normal client aswell.

**Comment by Nuckyz** [comment]
Discord released settings sync for client themes, which broke the bypass. The latest Vencord desktop version has this issue fixed, but the web version has not been released yet, which means the issue will persist until then
