### ISSUE TITLE
[Bug] Themes not loading

### ISSUE THREAD

**Issue by artifexdevstuff** [Vendicated/Vencord#668]
### Discord Account

artifex#3650

### What happens when the bug or crash occurs?

When loading a theme via a link, It says "Valid" but the theme doesn't load.

### What is the expected behaviour?

When I Load a theme via a link, Vencord should automatically enable it.

### How do you recreate this bug or crash?

1. Get a link to an x.theme.css file
2. Load it into the theme page

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by somerandomcloud** [comment]
Are you on discord web? Using Firefox add-on or user script?
Can you send the link to the CSS file?
