### ISSUE TITLE
[Feature Request] MessageLinkEmbeds: blacklist servers

### ISSUE THREAD

**Issue by jathek** [Vendicated/Vencord#678]
### Discord Account

nearcatch#3721

### What is it that you'd like to see?

I'd like to blacklist certain servers from the MessageLinkEmbeds plugin, because these servers already have a bot that embeds previous messages. Right now those servers look like this:
![image](https://user-images.githubusercontent.com/692914/227371973-5eedcf8e-9aff-44f2-aa27-76b00828f78e.png)

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
blocked by #615
