### ISSUE TITLE
[Feature Request] Clone Stickers

### ISSUE THREAD

**Issue by screwhatescode** [Vendicated/Vencord#684]
### Discord Account

screw#2812

### What is it that you'd like to see?

Clone Stickers in the Emote Cloner plugin, would be very helpful!

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
Added! https://github.com/Vendicated/Vencord/commit/1ec28a345bad401efade1af734db59ea1cd6dc1a
