### ISSUE TITLE
[Bug] Specific Themes not allowing to remove theme on web version

### ISSUE THREAD

**Issue by 5yrex** [Vendicated/Vencord#697]
### Discord Account

khai#4150

### What happens when the bug or crash occurs?

This issue happens, as i'm in the web version, SpotiCord (BD theme) once installed, cannot be disabled from the 'Themes' textbox, as shown. Is this an issue only with this theme? I've reinstalled Vencord but still can't undo the theme.
<img width="704" alt="Screenshot 2023-03-25 at 1 27 53 pm" src="https://user-images.githubusercontent.com/115611557/227682033-48a7df16-5a9c-4df2-8d08-ea7255802bcb.png">

### What is the expected behaviour?

I expect the theme textbox to be there so I can remove this theme.

### How do you recreate this bug or crash?

1. Installed plugins
<img width="480" alt="Screenshot 2023-03-25 at 1 29 43 pm" src="https://user-images.githubusercontent.com/115611557/227682109-3f8cc70c-a86b-42bc-b566-4cabfa00b557.png">
2. Theme used: https://github.com/Slddev/SpotiCord 
3. Textbox disappears

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Complain to the theme dev, not us. You can find a fix in our FAQ https://canary.discord.com/channels/1015060230222131221/1027235873990901780/1086039623093989446

**Comment by Slddev** [comment]
Hello, the theme dev here. 

The solution/bypass to the problem has been pinned to the issue tab of the repository.
