### ISSUE TITLE
[Feature Request] CUSTOM PLUGINS

### ISSUE THREAD

**Issue by TheGlitchHunterTV** [Vendicated/Vencord#698]
### Discord Account

The Glitchologist#2398

### What is it that you'd like to see?

We should be able to add custom plugins imported from BD to make it better, i'm not asking for a specific plugin but there should be a mode where you can add custom plugins. This can maybe fix some bugs & improve Vencord so much that BD will fall.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
Already supported for third party Vencord plugins, never will be supported for BetterDiscord plugins
