### ISSUE TITLE
[Bug] TAGS CREATION GLITCH

### ISSUE THREAD

**Issue by TheGlitchHunterTV** [Vendicated/Vencord#699]
### Discord Account

The Glitchologist#2398

### What happens when the bug or crash occurs?

This bug happens whenever we type / and scroll down.. Nothing happens until we reach the tags create section but when we do then it bugs out and has infinite commands of the same time.. Keeps scrolling up and wont show us the rest of the commands even if we scroll all the way up.

### What is the expected behaviour?

I expect Vencord/Discord to let us scroll down slowly here instead of bugging it out.

### How do you recreate this bug or crash?

1. Type in "/" to open up the commands list.
 2. Keep scrolling down slowly until you see the TAGS area.
 3. Try to scroll up or down. 
 4. There we go!

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Nuckyz** [comment]
can confirm

**Comment by Vendicated** [comment]
Fixed
