### ISSUE TITLE
[Feature Request] Prevent crash gifs from crashing Discord

### ISSUE THREAD

**Issue by TomerGamerTV** [Vendicated/Vencord#708]
### Discord Account

TomerGamerTV#6645

### What is it that you'd like to see?

Currently, when a user posts a "crash gif" in Discord, it can cause the platform to freeze or crash entirely, disrupting the user experience. Therefore, I suggest the addition of a feature that detects and prevents crash gifs from causing Discord to crash.

I'm aware that i can disable autoplay but it ruins the whole experience of sending and viewing gifs.

### Request Agreement

- [x] This is not a plugin request

**Comment by ItsTeraBytes** [comment]
Try turning off "Hardware Acceleration" @ "User settings" > "Advanced"

**Comment by Vendicated** [comment]
didn't discord fix this ages ago? Anyway 
![Screenshot_20230326-185101_Bromite__01](https://user-images.githubusercontent.com/45497981/227791266-894011bc-5786-4e6f-b5b4-8db8e7ba4f4e.png)

**Comment by TomerGamerTV** [comment]
> Try turning off "Hardware Acceleration" @ "User settings" > "Advanced"

It will just make discord slower

**Comment by TomerGamerTV** [comment]
> didn't discord fix this ages ago? Anyway 
> 
> ![Screenshot_20230326-185101_Bromite__01](https://user-images.githubusercontent.com/45497981/227791266-894011bc-5786-4e6f-b5b4-8db8e7ba4f4e.png)
> 
> 

They didn't fix anything. Isn't there a way to integrate it into vencorde?

**Comment by Captain8771** [comment]
> > didn't discord fix this ages ago? Anyway 
> > 
> > ![Screenshot_20230326-185101_Bromite__01](https://user-images.githubusercontent.com/45497981/227791266-894011bc-5786-4e6f-b5b4-8db8e7ba4f4e.png)
> > 
> > 
> 
> They didn't fix anything. Isn't there a way to integrate it into vencord? 

do you have an example of a crashing gif?

**Comment by TomerGamerTV** [comment]
> > > didn't discord fix this ages ago? Anyway 
> > > 
> > > ![Screenshot_20230326-185101_Bromite__01](https://user-images.githubusercontent.com/45497981/227791266-894011bc-5786-4e6f-b5b4-8db8e7ba4f4e.png)
> > > 
> > > 
> > 
> > They didn't fix anything. Isn't there a way to integrate it into vencord? 
> 
> do you have an example of a crashing gif?

I have couple of them

**Comment by katlyn** [comment]
Typically someone asking "do you have an example" is expecting you to actually share the examples rather than just saying "yes". If you do have crash gifs, you'll have to share them otherwise devs won't know what they're trying to patch against. That said, Discord *has* patched [multiple](https://github.com/discord/electron/pull/14) [instances](https://github.com/discord/electron/pull/21) of crash "gifs" (all of which are just videos thanks to tenor and giphy).

**Comment by TomerGamerTV** [comment]
> Typically someone asking "do you have an example" is expecting you to actually share the examples rather than just saying "yes". If you do have crash gifs, you'll have to share them otherwise devs won't know what they're trying to patch against. That said, Discord _has_ patched [multiple](https://github.com/discord/electron/pull/14) [instances](https://github.com/discord/electron/pull/21) of crash "gifs" (all of which are just videos thanks to tenor and giphy), and I could find no reputable sources or examples of crash gifs that still work when searching online.

https://gfycat.com/hopefulimpossiblebuzzard
https://gfycat.com/RewardingMediumDassie
https://gfycat.com/AgonizingWellwornHornedviper
https://gfycat.com/HopefulImpossibleBuzzard

**Comment by katlyn** [comment]
After pasting all of these into my discord client and sending them, I have not crashed. I have let all of them loop several times, and even posted them in the Vencord discord server for additional feedback, and no one else has crashed. Either your Discord's electron version is a year out of date, or you have something else causing you to crash.

**Comment by TomerGamerTV** [comment]
> After pasting all of these into my discord client and sending them, I have not crashed. I have let all of them loop several times, and even posted them in the Vencord discord server for additional feedback, and no one else has crashed. Either your Discord's electron version is a year out of date, or you have something else causing you to crash.

How do i check my electron version?
