### ISSUE TITLE
[Feature Request] Experimental Custom Plugins

### ISSUE THREAD

**Issue by liquiddevelopmentnet** [Vendicated/Vencord#709]
### Discord Account

Liquid#6969

### What is it that you'd like to see?

I think it would be cool to add a feature (probably activated through the settings json file only) for developers to add their own plugin javascript files, this way people can create their own personal usage plugins and develop plugins for this repository easier.

I'm aware that this would open the possibility for users to distribute plugins to other users, but I don't see a problem with that if the setting can only be activated through a json file.

### Request Agreement

- [x] This is not a plugin request

**Comment by Vendicated** [comment]
already possible by building from source (as you've discovered :P)
