### ISSUE TITLE
[Bug - CustomRPC] Start/End time cause presence to not show

### ISSUE THREAD

**Issue by colocaust** [Vendicated/Vencord#714]
### Discord Account

colocaust#4004

### What happens when the bug or crash occurs?

The bug is in the CustomRPC plugin, whenever I set "Start Time" or "End Time" instead of value 0, the RPC disappear from my status. If I set it to 0, then it works, but there is no countdown time for "elapsed" or "remained" because the value is 0. The Preview on the plugin of the RPC is working, but not on the Profile popup.

### What is the expected behaviour?

When I set "Start Time" or "End Time" the RPC should appear and based on the set time it should show "00:01 elapsed" or "00:01 remained".

### How do you recreate this bug or crash?

Set up a CustomRPC with a "Start Time" or "End Time" and you will see the issue.

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Captain8771** [comment]
Dev of CustomRPC here! Did you try reloading? I'm not sure why, but the RPC kind of breaks if you don't reload.

**Comment by Captain8771** [comment]
Yeah i'm gonna make reloads required when changing CustomRPC settings when i stop procrastinating
