### ISSUE TITLE
[Bug] Discord Crashing

### ISSUE THREAD

**Issue by 3kh0** [Vendicated/Vencord#719]
### Discord Account

3kh0_#6969

### What happens when the bug or crash occurs?

It just goes to a white screen.

![image](https://user-images.githubusercontent.com/58097612/228247992-409d6336-b0df-40cd-bdc3-3d99be15fd37.png)

### What is the expected behaviour?

It would load up discord

### How do you recreate this bug or crash?

1. Install vencord web on firefox
2. Go to discord.com/app
3. Get flashbanged with a white screen

### Errors

![image](https://user-images.githubusercontent.com/58097612/228248918-9dcc097b-3df0-4145-ba55-cf55e7b89fec.png)
![image](https://user-images.githubusercontent.com/58097612/228249009-77feb8a8-47ee-49d6-876a-64308853a4c8.png)
![image](https://user-images.githubusercontent.com/58097612/228249080-528bbb6c-eba1-4942-83cf-f4208a8fb287.png)
![image](https://user-images.githubusercontent.com/58097612/228249198-10040316-4e63-4055-86c1-f2d383b186a4.png)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by MeguminSama** [comment]
fwiw I've run into this a few times. just ctrl+r usually fixes when it appears.

**Comment by Vendicated** [comment]
Oh this is just stock discord issue they *still* haven't fixed https://canary.discord.com/channels/1015060230222131221/1024351821873037462/1088933042590072882
