### ISSUE TITLE
[Feature Request] Plugin loader

### ISSUE THREAD

**Issue by craciu25yt** [Vendicated/Vencord#726]
### Discord Account

craciu25_YT#3332

### What is it that you'd like to see?

It would be nice to have a plugin loader that allows you to load plugins without restarting the client and allows to add third-party plugins without having to add them in the source and compile the full client

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
not possible

**Comment by craciu25yt** [comment]
and why .-.

**Comment by Vendicated** [comment]
Because we patch Discord by changing its code before it is executed. To apply new patches to the code you need to reload the module aka reload Discord
