### ISSUE TITLE
[Bug] <Access your data for https://raw.githubusercontent.com discord site only makes white (Mozilla firefox)>

### ISSUE THREAD

**Issue by MediaProductions** [Vendicated/Vencord#728]
### Discord Account

SHYSO#2384

### What happens when the bug or crash occurs?

as soon as you go to access your data for https://raw.githubusercontent.com and enable it the discord page in firefox will show up and you can't do anything but turn it off again

### What is the expected behaviour?

normal white one should use the dsicord page without it being only white can I've only seen a bug in firefox so far

### How do you recreate this bug or crash?

simply revise your addon for firefox so that something like this doesn't happen

### Errors

![safsaf](https://user-images.githubusercontent.com/65030380/228594081-20947087-53c9-49a2-865d-9c1fa07e9d20.PNG)
![dc](https://user-images.githubusercontent.com/65030380/228594084-119f26eb-951a-41d5-984b-22856c98ab2f.PNG)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
what
