### ISSUE TITLE
(Issue) Web version doesnt work on waterfox.

### ISSUE THREAD

**Issue by emir4169** [Vendicated/Vencord#73]
How to replicate
-1. have waterfox
0. have vencord all set up for both build web and normal build
1. build web
2. try to use it in waterfox
3. bug replicated

**Comment by emir4169** [comment]
Theres a flag missing thats required on manifest.json for it to work

**Comment by emir4169** [comment]
after patching the web zip file myself after building i have found that customcss will not work unless i have good knowledge of how the source code works

**Comment by Vendicated** [comment]
> Theres a flag missing thats required on manifest.json for it to work

What flag?

**Comment by emir4169** [comment]
> 

![image](https://user-images.githubusercontent.com/89991965/194764306-334d7bd6-c429-4a6b-b0f1-5ccd71f0fd0b.png)
(example of the flag thats normally missing, also i made a pr that fixes this)
