### ISSUE TITLE
[Bug] CustomRPC not working for others

### ISSUE THREAD

**Issue by AnOpenSauceDev** [Vendicated/Vencord#732]
### What happens when the bug or crash occurs?

Using Vencord with OpenAsar Discord, with the CustomRPC plugin active.
You can see your own RPC status, but nobody else can.

### What is the expected behaviour?

People should be able to see my activity just like how it is with everything else.

### How do you recreate this bug or crash?

Enable Custom RPC, fill in the application and image fields, tell someone to see your RPC, and notice how nothing shows up on their end.

### Errors

i couldn't find any errors in the log.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use our support channel please
