### ISSUE TITLE
[Bug] Typing indicator does not appear despite Silent Typing plugin being disabled

### ISSUE THREAD

**Issue by BOSS05-Games** [Vendicated/Vencord#734]
### What happens when the bug or crash occurs?

When I type, the indicator should be viewable on other accounts, as the plugin is disabled, however, it is not - people cannot see me type while I use Vencord.

### What is the expected behaviour?

The typing indicator should appear when I type, especially if the plugin is turned off or outright disabled, however this does not happen.

### How do you recreate this bug or crash?

1. Turn on the silent typing indicator plugin and use it.
2. Either disable the functionality or turn off the plugin.
3. The typing indicator is still silent for people receiving your messages.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
you're using openasar with their version of the feature enabled or similar. or if that's not the case, use our support channel
