### ISSUE TITLE
[Bug] Faulty ViewRaw

### ISSUE THREAD

**Issue by ilytouni** [Vendicated/Vencord#742]
### Discord Account

touni#7235

### What happens when the bug or crash occurs?

This happened just recently (before as well) - I am unable to use ViewRaw properly as the button doesn't show up in order to view or copy a raw message. The button is missing whenever I hover to a message, even if I right click the message - the button doesn't show up.

![image](https://user-images.githubusercontent.com/74092353/229016853-9bcf3030-de7f-4431-95d5-cade3623ad95.png)
![image](https://user-images.githubusercontent.com/74092353/229016874-0ad8cdac-08b3-4f58-9098-0ebab2ef3331.png)

As proof for enabling the plugin:

![image](https://user-images.githubusercontent.com/74092353/229017400-1e1b938e-9ab9-4a6c-a6bb-b76c35ebb73f.png)
https://user-images.githubusercontent.com/74092353/229018602-ac87a34b-ce2c-4ebe-92db-e1b65ab14b41.mp4

### What is the expected behaviour?

As usual, the ViewRaw plugin should have a button whenever you hover over a message that allows you to view and copy raw messages. However - this was not the case for me. 

### How do you recreate this bug or crash?

There is not a specific way to recreate the bug, however these are the following steps that I did / occured when the bug comes up:

1. It occured right after the Vencord Update (in which it is required to restart the client) and I am now unable to see the button and/or view and copy raw messages.
2. I have tried re-installing and restarting my Discord client but to no avail it still did not work.
3. I have also opened the Developer Console but there is no error regarding the ViewRaw plugin.

### Errors

N/A; nothing in the Developer Console says anything about an error regarding the ViewRaw plugin.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Hiya, Thanks for the report! (though usually there's no need to open an issue as we have automatic detection of broken plugins)

I just fixed this in https://github.com/Vendicated/Vencord/commit/efd99276961ffeaf9440521f2a902ee4f9b5f5ed

**Comment by Soulivan71** [comment]
Hi I mention, that ViewRaw no longer works for msg/embed msg can u look into it ?

**Comment by Vendicated** [comment]
it does. use our support channel instead of necroing years old threads.
