### ISSUE TITLE
[Bug] Ignore Activities not ignoring activities

### ISSUE THREAD

**Issue by yiyska** [Vendicated/Vencord#744]
### Discord Account

yun#7077

### What happens when the bug or crash occurs?

If I'm using an application that has an activity that changes based on my usage such as league, it will not ignore it. 
Example: I open league, the activity will be hidden as it should, then I go in a lobby and the activity is no longer hidden, same with going in champ select and going in-game.

### What is the expected behaviour?

I expected it to be hidden all the way, not just when the client is open.

### How do you recreate this bug or crash?

1. Ignore the activity in Registered Games
2. Restart Discord just in case
3. Open League client (the activity will be ignored)
3. Open practice tool lobby (the activity will no longer be ignored)
4. Start lobby (will remain unignored)
5. Start game (will remain unignored)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
That means it's using multiple different activity ids. Just ignore them all
