### ISSUE TITLE
[Bug] Could not resolve "nanoid"

### ISSUE THREAD

**Issue by nnaem** [Vendicated/Vencord#755]
### Discord Account

xv#3500

### What happens when the bug or crash occurs?

It happens since the latest 2 updates when updating.

### What is the expected behaviour?

I expect vencord to update and build properly.

### How do you recreate this bug or crash?

1. Go to user settings
2. Go to the Updater tab
3. Click the "Update Now" button
4. Observe

### Errors

```
Failed to update Object
r.<computed> @ 05cd3353f9a3e49ee3bc.js:9288
```

![image](https://user-images.githubusercontent.com/66337470/229341392-226a0302-ce4b-414b-b923-c0ab5f4cbf7c.png)

![image](https://user-images.githubusercontent.com/66337470/229341405-ff0f4774-ffd8-4b2b-9a22-b4da35dd2527.png)

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by AutumnVN** [comment]
try update by the installer

**Comment by Nuckyz** [comment]
You are using an advanced installation, run `pnpm i` inside the Vencord directory and then `pnpm build`
