### ISSUE TITLE
[Feature Request] Nightly extensions

### ISSUE THREAD

**Issue by Vendicated** [Vendicated/Vencord#757]
### Discord Account

V like Vencord

### What is it that you'd like to see?

Currently, the web extensions are only published on tag. It would be nice to offer nightly extensions that are published on each commit, likely by creating a second extension in the WebStore

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
Since google is so allergic to approving our extension updates, this would be pointless.

Self distributing is also not really viable because chromium doesn't even allow self updated extensions on not linux

UserScript & extension.zip in release exist so just use that instead

**Comment by pointydev** [comment]
> Self distributing is also not really viable because chromium doesn't even allow self updated extensions on not linux

You can tell Chromium to allow specific extension IDs for self distribution using the ExtensionInstallAllowlist policy in the Windows Registry.

See how this extension instructs users to install:
https://github.com/younesaassila/ttv-lol-pro/blob/eb34f3b3de45992f57f6705a81f44ff5f80107e9/README.md#Installation
https://github.com/younesaassila/ttv-lol-pro/releases/tag/v1.9.1
