### ISSUE TITLE
[Feature Request] MessageClickActions Implement editable key bind

### ISSUE THREAD

**Issue by exitss** [Vendicated/Vencord#758]
### What is it that you'd like to see?

At the moment, the click to delete is locked to "Backspace". I am suggesting adding a new setting into the plugin's configuration to be able to select any key. I prefer the binding to be "Ctrl + Click" to delete messages as it is more intuitive.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
#655
