### ISSUE TITLE
[Feature Request] <Remove Window Size Limit>

### ISSUE THREAD

**Issue by lewo-liowa** [Vendicated/Vencord#770]
### Discord Account

Lewo#5660

### What is it that you'd like to see?

Better discord has a little option letting you disable the window size limit in discord, coupled with the theme "Float" it is pretty essential for my multitasking workflow.
Would love to see it here.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
https://www.reddit.com/r/discordapp/comments/acog0e/remove_minimum_size_of_discord_window_windowsmac
