### ISSUE TITLE
[Bug] Discord Overlay not working since using Vencord

### ISSUE THREAD

**Issue by Danicchi** [Vendicated/Vencord#775]
### What happens when the bug or crash occurs?

Since I have installed Vencord the Discord Overlay doesn't seem to be working.
Just uninstalled Vencord, closed and launched my game and it's working just fine on native Discord.
I do not know what causes this.
using discord stable btw

### What is the expected behaviour?

I expect the Discord Overlay to work **with Vencord installed.**

### How do you recreate this bug or crash?

1. Install Vencord.
2. Launch a game and observe. That's it. Game Overlay just doesn't show up anymore lol.

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Kathund** [comment]
@Danicchi what vencord version are you using

**Comment by Danicchi** [comment]
> @Danicchi what vencord version are you using

using tthe latest version

**Comment by Danicchi** [comment]
@Kathund 

> @Danicchi what vencord version are you using

using the latest version

**Comment by Kathund** [comment]
Ight i will do some testing when i get a chance

> @Kathund
> 
> > @Danicchi what vencord version are you using
> 
> using the latest version

**Comment by fesh1471ds** [comment]
dwag wa da hell is the vencord just a error and i cant get the invite aswell bruv fix it fast

**Comment by Vendicated** [comment]
Not related to Vencord, seems to be caused by OpenAsar.

**Comment by FreshImmuc** [comment]
I just had this issue, uninstalling OpenAsar fixed this issue.
