### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by Chroansten** [Vendicated/Vencord#779]
### Discord Account

! Trish !#3049

### What happens when the bug or crash occurs?

.

### What is the expected behaviour?

I just open my Discord PTB then i saw this error, i cant even access the whole vencord, but the themes and other functions, seems to be working.

![image](https://user-images.githubusercontent.com/98820980/229787391-b121ed75-86be-4c16-8751-f2f258e0bac6.png)

### How do you recreate this bug or crash?

i didn't recreate it the bug, its just like when i update the discord PTB, its just like that

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by lyiriyah** [comment]
canary and ptb are broken, you need to use stable. if you tried using stable, you would have known that -- don't lie and tick the agreement next time

**Comment by Chroansten** [comment]
okay, gotta try that, thx for the tip
