### ISSUE TITLE
[Feature Request] Banner on fakeProfileThemes

### ISSUE THREAD

**Issue by The-MG** [Vendicated/Vencord#781]
### What is it that you'd like to see?

Adding ability to add a profile banner with profile themes would be awesome!

### Request Agreement

- [X] This is not a plugin request

**Comment by TheKodeToad** [comment]
Through URL I guess? should be limited to discord cdn though

**Comment by TheKodeToad** [comment]
Oh, can't find it! How would that even work?

**Comment by Vendicated** [comment]
Out of scope of the plugin. Use https://github.com/Discord-Custom-Covers/usrbg
