### ISSUE TITLE
[Bug] Failed to render any Components related to Vencord

### ISSUE THREAD

**Issue by xDroflLOL** [Vendicated/Vencord#784]
### What happens when the bug or crash occurs?

The bug happens when I try to access to any of the Vencord Pages.

### What is the expected behaviour?

I except Vencord/Discord to open any of the pages under the Vencord section.

### How do you recreate this bug or crash?

1. Go to settings
2. Scroll down until you find the Vencord section
3. Click on any of the pages related to Vencord
4. See `TypeError: Reflect.get called on non-object`

### Errors

```
TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at Object.ai.<computed> [as get] (proxyLazy.ts:44)
    at index.tsx:73
    at Array.map (<anonymous>)
    at dv (index.tsx:71)
    at Sa (0192aa8c9176cfd4091d.js:1744)
    at gu (0192aa8c9176cfd4091d.js:1798)
    at Ic (0192aa8c9176cfd4091d.js:1791)
    at mc (0192aa8c9176cfd4091d.js:1791)
    at hc (0192aa8c9176cfd4091d.js:1790)
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by TheKodeToad** [comment]
This is a known issue! I'd suggest closing it :P. otherwise it will be anyway

**Comment by xDroflLOL** [comment]
> This is a known issue! I'd suggest closing it :P. otherwise it will be anyway

Oh.

**Comment by NWPlayer123** [comment]
Devs, this is going to keep happening each time you close and lock other reports of this (it's very easy to see), you may as well leave it open until it's addressed

**Comment by TheKodeToad** [comment]
Maybe at least one issue should be kept open? :P
probably what most repos would do

**Comment by ItzOnlyAnimal** [comment]
Just make one issue, pin it and lock it. but that won't stop anyone since client mod users don't use their brain
