### ISSUE TITLE
[Bug] BetterFolders sidebar get stuck open

### ISSUE THREAD

**Issue by ItsTeraBytes** [Vendicated/Vencord#799]
### Discord Account

TeraBytes#5555

### What happens when the bug or crash occurs?

The better folders sidebar gets stuck open

### What is the expected behaviour?

It should just close

### How do you recreate this bug or crash?

1. Make a folder with 2 servers or more but 2 is easier
2. Open the folder in the sidebar
3. Remove all the servers by dragging all of them to the main bar without the folders
4. Done the menu stay open without any serversthem

### Errors

No errors

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
Hi! Is this still an issue?

**Comment by AutumnVN** [comment]
it only stucks like 15-20s and then it auto closes

**Comment by ItsTeraBytes** [comment]
Oh neet
