### ISSUE TITLE
[Feature Request] NoReplyMention: Inverse shift reply behaviour

### ISSUE THREAD

**Issue by Redundakitties** [Vendicated/Vencord#810]
### Discord Account

GracefulLion#9559

### What is it that you'd like to see?

I think it would be cool to see the inverse ping-on-reply behavior of normal discord. Normally, when holding shift and hitting reply the user is not pinged. With this plugin enabled it'd be nice if when holding shift and hitting reply the user IS pinged. 

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
![image](https://user-images.githubusercontent.com/45497981/230260810-979f98de-b70f-4b03-9c74-035127418a3e.png)
