### ISSUE TITLE
[Bug] a lil bug with fake stickers

### ISSUE THREAD

**Issue by LIL-JABA** [Vendicated/Vencord#819]
### Discord Account

LIL JABA#2363

### What happens when the bug or crash occurs?

if the sticker has spaces in its name, it will be sent without hiding the link

how to fix:
you can cut the "&name=cool sticker name" and it still will send the sticker. so I suggest you to remove that name part :)

![image](https://user-images.githubusercontent.com/82034934/230581073-2e03e48d-8faf-4381-b7a8-ac9683cd4ef2.png)

### What is the expected behaviour?

I expect it to send the sticker hiding the link

### How do you recreate this bug or crash?

send any sticker with spaces in its name

### Request Agreement

- [x] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by P1nkEy3** [comment]
the sticker isnt a real sticker, its a gif, so it'll show you the link of said gif
