### ISSUE TITLE
[Bug] Friend invites plugin broken

### ISSUE THREAD

**Issue by zisra** [Vendicated/Vencord#824]
### Discord Account

Isra#1000

### What happens when the bug or crash occurs?

<img width="625" alt="Screenshot 2023-04-07 at 10 29 15 AM" src="https://user-images.githubusercontent.com/100528712/230635372-a208f506-aae0-440d-baa9-67fac307cbb2.png">
<img width="641" alt="Screenshot 2023-04-07 at 10 29 48 AM" src="https://user-images.githubusercontent.com/100528712/230635458-00f45d94-7fb1-4875-aa13-0e7188ddd72c.png">
The above error is shown in the network tab after the command is initated

### What is the expected behaviour?

I expect Vencord to send me a friend invite

### How do you recreate this bug or crash?

1. Verify your phone number if you haven't yet
2. Download the friend invite plugin
3. Use the /create friend invite command
4. Observe the error in the chat and network tab of dev tools

### Errors

```js
{"code": 50035, "errors": {"_errors": [{"code": "CONTENT_TYPE_INVALID", "message": "Expected \"Content-Type\" header to be one of {'application/json'}."}]}, "message": "Invalid Form Body"}
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
it was fixed two days ago, please update
