### ISSUE TITLE
[Bug] backend api cannot be consumed as plain http

### ISSUE THREAD

**Issue by iwa** [Vendicated/Vencord#825]
### What happens when the bug or crash occurs?

i dont want to expose my vencord backend im selfhosting, as i'll be the only one using it, so i'm not exposing it to the internet and accessing to it through a vpn
but it seems that the client cannot connect to the backend unless it's https? could we allow http too? or if it's not possible at least specify it in the readme of the backend repo then?

### What is the expected behaviour?

the client should allow to use http backend

### How do you recreate this bug or crash?

- setup a vencord backend
- expose it through http only
- error in console

### Errors

![image](https://user-images.githubusercontent.com/19956672/230648989-dbb3cb54-262e-4e25-b3a8-4f9dfca5c49b.png)

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by lewisakura** [comment]
If we patch out the security check this will introduce a security hole into Discord which is not tolerable. This is just a natural consequence of trying to request a HTTP page from a HTTPS one.

**Comment by iwa** [comment]
i was afraid that would be the answer lmao
then could you add a lil note about that in the readme of the backend repo? so people don't get confuse, because the only error you visually get is this:
![image](https://user-images.githubusercontent.com/19956672/230649944-4a8ef4d4-9e54-4128-b838-b321095564d4.png)

no actually mention of the need of https :/

**Comment by lewisakura** [comment]
Backend repo now has a note saying it requires HTTPS to be used.

**Comment by Vendicated** [comment]
not possible, that error is a security feature of the browser. The only solution is to disable web security entirely but we're definitely not doing that
