### ISSUE TITLE
[Feature Request] Separate settings for all Discord installs.

### ISSUE THREAD

**Issue by bog4t** [Vendicated/Vencord#845]
### What is it that you'd like to see?

Vencord doesn't seem to have separate settings for each version of discord (stable, ptb, canary, etc.). It would be great if it did so. One particular use case I'm interested in is having separate themes for each client to better differentiate between the two of them.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
this is already possible by setting the VENCORD_DATA_DIR environment variable for each discord install

Implementing it as a native setting is not that simple, because where would you store the custom settings dir? you'd still need to store that in a common location

**Comment by bog4t** [comment]
We might be able store it in the same folder as the discord install, but we can definitely store it within `%appdata%/Vencord/settings` and have separate folders for each version of discord similar to BetterDiscord. 

We can start out with default folder names for recognized installations (stable, ptb, canary, etc.) and for custom installations we could either have a default generic folder name appended with an incrementing number and give the user an option in the settings to change it and/or have the user specify the folder in which they want the settings to be saved on installation.

**Comment by Vendicated** [comment]
The majority of people don't want separate settings for each branch, having shared settings across branches is a feature

**Comment by bog4t** [comment]
In that case, we just need to give users the option to the change the settings folder from default if they wish.

**Comment by Lunatic3k** [comment]
> this is already possible by setting the VENCORD_DATA_DIR environment variable for each discord install
> 

I'm sorry, but how do i do that? I'm not very good at this :D

**Comment by Redundakitties** [comment]
> this is already possible by setting the VENCORD_DATA_DIR environment variable for each discord install

I was testing this out as it would be nice to dev on canary with a clean slate and no plugins but still be able to use stable for everything else. 

However, even though I patched stable using the default `VENCORD_USER_DATA_DIR`, when I changed the variable to be `C:\Users\<name>\AppData\Roaming\VencordCanary\dist`, it changed my stable directory too. I'm not sure if I'm doing something wrong or if this is intended? I was formatting the path based on the installer instructions: 

![image](https://user-images.githubusercontent.com/38409600/230793204-f90e424b-8b1c-4391-9d2f-d871b9db01d4.png)

**Comment by Redundakitties** [comment]
Answer: the env has to be set per powershell launch rather than globally in the system env

Ex for windows:
```ps
$env:VENCORD_USER_DATA_DIR = /blah
Start-Process C:\Path\To\Discord\...
```

also word on the street is we should try https://github.com/Vencord/Desktop which by default it has separate settings from discord stable 👍

**Comment by Lunatic3k** [comment]
> also word on the street is we should try https://github.com/Vencord/Desktop which by default has separate settings from discord stable 👍

That worked perfectly for me. Thanks for the tip :)
