### ISSUE TITLE
[Feature Request - MoreUserTags] Setting to not apply to bots

### ISSUE THREAD

**Issue by samprdev** [Vendicated/Vencord#858]
### Discord Account

SkoopyDev#9911

### What is it that you'd like to see?

I think there should be an "opposite" function for this setting:
![image](https://user-images.githubusercontent.com/90944534/230830507-c1f21e1a-510c-4051-bc52-6f1c3729e0a5.png)

Since many bots have mod+ perms, so they show like this: "Bot - Mod". However, this setting only removes the "bot" tag, so it only displays the "mod" tag. I think it would be more useful to add a different setting that removes the "mod" tag(and the other tags, "staff" and "admin") to only leave the "bot" tag. I would like to view what members have mod+ permissions, but I don't care whether bots have them.

### Request Agreement

- [X] This is not a plugin request

**Comment by muurt** [comment]
![image](https://github.com/Vendicated/Vencord/assets/75748143/375ae770-e280-44df-a9e5-d7463e690540)
should be closed by now
