### ISSUE TITLE
[Bug] Clicking on WhoReacted avatars also adds reaction

### ISSUE THREAD

**Issue by ryanccn** [Vendicated/Vencord#868]
### Discord Account

RyanCaoDev#0428

### What happens when the bug or crash occurs?

When you click on an avatar added by the WhoReacted plugin to see the user popout, it also triggers the click and adds a reaction for yourself.

### What is the expected behaviour?

The expected behavior is probably to only add the reaction when you click in the box somewhere that isn't a user avatar.

### How do you recreate this bug or crash?

1. Use the WhoReacted plugin
2. Click an avatar in a reaction

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by KannaDev** [comment]
Made a pull request [here](https://github.com/Vendicated/Vencord/pull/977) that solves this issue.

**Comment by ryanccn** [comment]
> Made a pull request [here](https://github.com/Vendicated/Vencord/pull/977) that solves this issue.

Thanks!
