### ISSUE TITLE
[Bug] LastFMRichPresence not showing up

### ISSUE THREAD

**Issue by Taco1701** [Vendicated/Vencord#885]
### Discord Account

Taco🌮#8329

### What happens when the bug or crash occurs?

When your spotify account is linked and you enable to option to show it in your profile (when listening to music) the LastFMRichPresence does not work. 

### What is the expected behaviour?

The LastFMRichPresence should be displayed too

### How do you recreate this bug or crash?

1. Link your spotify account
2. Enable to show spotify in your status
3. Enable the LastFMRichPresence-Plugin

### Errors

None

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by AutumnVN** [comment]
is this what you mean? doesn't it work fine?
![image](https://user-images.githubusercontent.com/77253698/231911834-d52c4557-5cfa-4e12-a315-de17ab071c01.png)
![image](https://user-images.githubusercontent.com/77253698/231911843-67cb1029-a384-4d8f-9915-9ad88e67c302.png)
![image](https://user-images.githubusercontent.com/77253698/231911849-f16bf326-384a-49ff-86df-e50c90a027eb.png)

**Comment by Taco1701** [comment]
Yeah, strange it only doesn't work for me.

**Comment by Taco1701** [comment]
K

**Comment by Vendicated** [comment]
Works for me too, likely an issue on Last.fm's or your end. Nothing we can do

![image](https://github.com/Vendicated/Vencord/assets/45497981/5689abf8-f0c8-4c98-9436-c79e77a104ce)
![image](https://github.com/Vendicated/Vencord/assets/45497981/014b775a-73c2-42f9-8af9-b3a53dd15a9c)

**Comment by toiletbril** [comment]
For anyone still wondering, try checking if you have 'Activity Privacy' -> 'Share my activity' checkbox set in the settings.

**Comment by Impasse52** [comment]
Chiming in to say that this actually doesn't work for me neither years later? Status is updated client-side but nothing is appearing on the other end, just tested this by creating a different account and adding myself as a friend

**Comment by Vendicated** [comment]
use our support channel
