### ISSUE TITLE
Allow 25mb uploads for non-nitro users

### ISSUE THREAD

**Issue by billyboybob** [Vendicated/Vencord#888]
### Tell us all about it.

(I hope this is the right template for this sorta thing)

Discord recently added 25mb uploads for non-nitro users: https://twitter.com/discord/status/1645522780337885184
Would be nice to see the limit expanded in Vencord!

### Request Agreement

- [X] This is not a support or plugin request

**Comment by Vendicated** [comment]
You should already be able to use this, what does this have to do with us?

**Comment by billyboybob** [comment]
> You should already be able to use this, what does this have to do with us?

I'm probably just stupid, but I can't do it after installing Vencord, uninstalling works just fine though

**Comment by billyboybob** [comment]
Okay, yeah this is just a me issue then. Just tried it on a VM and it worked just fine. Gonna close this and see what else is causing this.
Sorry!
