### ISSUE TITLE
[Feature Request] Transparent Client

### ISSUE THREAD

**Issue by EchoLWS999** [Vendicated/Vencord#890]
### Discord Account

EchoLWS#0001

### What is it that you'd like to see?

The transparent window option that BetterDiscord has would be really nice here as using Discord with Wallpaper Engine is really nice. I don't know how hard it would be to implement, but it'd be great 

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
already feature but currently hidden from the ui as it causes issues for some people. You can enable it via the console (then fully restart):
```js
Vencord.Settings.transparentUNSAFE_USE_AT_OWN_RISK = true;
```

**Comment by EchoLWS999** [comment]
Oh, thank you so much!

**Comment by Vendicated** [comment]
added via https://github.com/Vendicated/Vencord/commit/988435714e8b1de6e7e95885cbb5222113fb039c
