### ISSUE TITLE
[Feature Request] FakeNitro enhancement: Allow usage of a server's emotes which get locked after the server level drops.

### ISSUE THREAD

**Issue by pewpasta** [Vendicated/Vencord#897]
### Discord Account

ZooterZ#6362

### What is it that you'd like to see?

I'm in a server which was at level 1 and had a hundred emotes. But after the server lost level 1, 50 of it's emotes were locked again. Would be pretty cool if the plugin allowed me to use to those emotes again. The [EmoteReplacer](https://github.com/Yentis/betterdiscord-emotereplacer) plugin for Betterdiscord already has this feature.

for example, the greyed out emotes here have been locked after the server lost level 1 ![image](https://user-images.githubusercontent.com/67459484/232055988-d6a8dc17-fa3c-42a7-8688-69e26c3b8630.png)

### Request Agreement

- [X] This is not a plugin request

**Comment by antiops** [comment]
+1 for this

It's possible (at least in the `v1.2.0` chrome extension) to send them by clicking any inside the emote picker, but they do not show up when trying to type them in the message input.

**Comment by Vendicated** [comment]
Implemented in #1184, will arrive in your Vencord soon!
