### ISSUE TITLE
Updating gives error `Command 'node' not found. Please install it and try again.`

### ISSUE THREAD

**Issue by LewsTherinTelescope** [Vendicated/Vencord#91]
I _do_ have Node.js installed, which was the first thing I thought to double-check, and running `node` in the terminal does in fact work fine. Devtools console has this object logged but nothing else:

```javascript
{
	cmd: "node build.mjs",
	code: "ENOENT",
	errno: -2,
	path: "node",
	spawnargs: [ "build.mjs" ],
	stderr: "",
	stdout: "",
	syscall: "spawn node",
}
```

Update seems to otherwise go smoothly, as if I open the directory up in the terminal, rerun `pnpm build`, and restart Discord, it goes to the new version.

**Comment by katlyn** [comment]
Depending how you've installed node, node may not be in your path at the time Discord is started. This can happen if you're using fnm or other tools, or even if your path is just configured incorrectly.

**Comment by LewsTherinTelescope** [comment]
Is there a way I can check what `PATH` the app is using?

**Comment by Vendicated** [comment]
Open Devtools (CTRL + Shift + i), click the dropdown in the second bar on the top where it says "top". Now switch to Electron isolated context and run `process.env.PATH`

**Comment by LewsTherinTelescope** [comment]
Ah, thanks! Yep, you're right, it's just using a very limited path. 

For anyone else who stumbles across this with the same issue on Mac after installing Node with `brew`, just add the Homebrew folder to the path at the start of `index.js`:

```js
process.env['PATH'] = process.env['PATH'] + ':/usr/local/bin';
```
