### ISSUE TITLE
[Feature Request] PinDMs: Pin Categories

### ISSUE THREAD

**Issue by iblowmymind** [Vendicated/Vencord#912]
### What is it that you'd like to see?

Renamable, collapsable categories for pinned DMs would be a really nice feature to have, as I would be able to organise my DMs better that way (e.g. different categories for my mutuals, friends, closer friends and bots). It could be similar to how https://github.com/Bricklou/powercord-pindms did it.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
I personally don't think this is very useful so I (as the plugin author) have no interest in working on this, but pull requests are very welcome

**Comment by iblowmymind** [comment]
Completely understandable, thanks anyway!
If anyone's willing to do it, that would be really helpful.
Cheers!

**Comment by Faf4a** [comment]
I'm sure this isn't what you looked for (maybe it is) but there's an alternative using the experimental favourites tab which allows you to pin guild channels, group DMs and regular DMs. You are able to add categories, rename them and more. The "feature" is rather unstable tho and won't work for all users unfortunately.

It's rather a private server where you can find all pinned channels, dms and whatever you want to pin.

![image](https://user-images.githubusercontent.com/87046111/232288377-f7ffd884-a407-4ff6-838a-ddcd754f36e6.png)
![image](https://user-images.githubusercontent.com/87046111/232288372-a2d5d2b0-d979-46af-8625-fd385a2a32e9.png)

(Note: Once used you can't disable it anymore, meaning it will stay forever)

There are two ways of accessing this: 
- Use the experiment plugin to enable this.
- Visit https://discord.com/channels/@favorites

**Comment by iblowmymind** [comment]
Thanks for your suggestion! However, not very keen to enable experiments as it would probably be risky. Would wait for it to eventually roll out to me, though!

**Comment by Violet-Scarelli** [comment]
This particular feature would be extremely useful for me, to be honest- I recently switched from BD to Vencord, and the PinDMs plugin I was using on BD had folders, which was nice. I could group the people I talked to by relationship (artist, friends, etc)

**Comment by bron99** [comment]
This feature was the main reason as to why i was using BD, if someone were to pick up this idea it would be highly appreciated. I believe this would be beneficial to many users, since the way discord handles DMs is awful :(

**Comment by iblowmymind** [comment]
Closing, as this was implemented. Thanks everyone!
