### ISSUE TITLE
[Bug] ShowMeYourName displays wrong username in a slash command reply.

### ISSUE THREAD

**Issue by Poki-Pancake** [Vendicated/Vencord#928]
### Discord Account

Pōki#7777

### What happens when the bug or crash occurs?

A bot's slash command reply preview will have the bot's name rather than the username of the user who called the slash command. The same behavior happens whether or not the user has a nickname.

Both plugin settings doesn't change the behavior. (It will always show `nickname (Bot name)`)

I do not know if that was intended

Example:
![2023-04-16_23-11_1](https://user-images.githubusercontent.com/115858316/232369625-aec16c4f-c304-47ca-80f6-f2c8d3440ce8.png)
![2023-04-16_23-11](https://user-images.githubusercontent.com/115858316/232369627-0ce00839-1bc1-4b2d-8d03-3346dad51d3a.png)

### What is the expected behaviour?

The username of the user calling the slash command should be displayed instead

or none depending plugin settings or if the user doesn't have nickname.

### How do you recreate this bug or crash?

1. Enable ShowMeYourName plugin
2. Have/make a bot that replies to slash command calls.
3. Use the slash command

### Errors

No log available

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
i think should be fixed. if no, feel free to reopen
