### ISSUE TITLE
[Bug] Issues with Relationship Notifier

### ISSUE THREAD

**Issue by craciu25yt** [Vendicated/Vencord#929]
### Discord Account

craciu25_YT#3332

### What happens when the bug or crash occurs?

When you use the discord account manager and you switch to another account the plugin relationship notifier just spams that everything changed because it is an another account with other dms ...

### What is the expected behaviour?

to do not notify

### How do you recreate this bug or crash?

1. Enable RelatioshipNotifier
2. Switch to another account

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
should be fixed

**Comment by craciu25yt** [comment]
Yep, it is. Thanks
