### ISSUE TITLE
`SyntaxError: Unexpected reserved word`

### ISSUE THREAD

**Issue by NotFubukIl** [Vendicated/Vencord#93]
Hi, i'm sharing you an error that I got while I tried to build, do you know how to fix it ?

![Capture d’écran 2022-10-12 145957](https://user-images.githubusercontent.com/75570490/195349167-d9ad6ea7-a379-4edd-99f4-142d20f5e900.png)

**Comment by Vendicated** [comment]
you're probably using an ancient nodejs version, use the support channel please
