### ISSUE TITLE
[Bug] WhoReacted causing scrolling issues

### ISSUE THREAD

**Issue by ThaUnknown** [Vendicated/Vencord#952]
### What happens when the bug or crash occurs?

Whenever you scroll in a channel with reactions, every time WhoReacted loads a new icon the scroll position jumps, making it very hard to continue scrolling.

### What is the expected behaviour?

Scrolling should be smooth as when WhoReacted isn't enabled.

### How do you recreate this bug or crash?

1. Enable WhoReacted
2. Open a channel with a frequent reactions
3. Scroll up
4. Notice scroll jitter

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Kapppa** [comment]
This also causes issues when jumping to an old message. It will not scroll all way to the message.

**Comment by Vendicated** [comment]
should be fixed
