### ISSUE TITLE
BUG: FXTwitter plugin patching `/username/somepath` which redirects to fxtwitter github

### ISSUE THREAD

**Issue by MeguminSama** [Vendicated/Vencord#97]
e.g., if you post `https://twitter.com/MeguminSama/with_replies`, it becomes `https://fxtwitter.com/MeguminSama/with_replies`, which just redirects to `https://github.com/FixTweet/FixTweet`

**Comment by somerandomcloud** [comment]
I actually made my regex fix that, but it got changed out last minute. Ill update the regex again to fix this now
