### ISSUE TITLE
[Bug] OperaGX autofills Discord email into Plugins search

### ISSUE THREAD

**Issue by JustinsKittens** [Vendicated/Vencord#972]
### What happens when the bug or crash occurs?

When I try to open the plugins menu on Vencord Web on Opera GX, it thinks the search box is for Discord accounts, so it autofills my email into the searchbox. When I try to remove it, it autofills again.

### What is the expected behaviour?

I expect it to NOT force my email into the Plugins search box on Vencord Web

### How do you recreate this bug or crash?

1. Open up Opera GX
2. Open Discord from the sidebar
3. Go to the plugins setting section
4. It will force your Discord email if you have saved passwords enabled on Opera GX

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
use a better browser or contact Opera gx support. I don't know how you expect us to fix this

**Comment by ArjixWasTaken** [comment]
Just don't save passwords on the browser, ez.

Keepass for the win
