### ISSUE TITLE
[Bug] Cant launch installer

### ISSUE THREAD

**Issue by nolan2014hvi** [Vendicated/Vencord#973]
### Discord Account

whatup#6537

### What happens when the bug or crash occurs?

All time that i try to launch the vencord installer its not launching when i go to task manager there nothing who appear

### What is the expected behaviour?

dont know

### How do you recreate this bug or crash?

1. You get Vencord installer
2. you launch it.

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by Vendicated** [comment]
please read
![image](https://user-images.githubusercontent.com/45497981/233811060-e9248043-beec-412c-ad4e-811b8f893b01.png)
