### ISSUE TITLE
Layout problem with plugin

### ISSUE THREAD

**Issue by nathanparra** [Vendicated/Vencord#978]
### Tell us all about it.

See the problem!
https://youtu.be/WXb-LzqiFBE

### Request Agreement

- [ ] This is not a support or plugin request

**Comment by Vendicated** [comment]
that's an issue with your theme, not Vencord.

**Comment by nathanparra** [comment]
> that's an issue with your theme, not Vencord.
and vencord supports betterdiscord themes, so if it works correctly in bc, it should in vencord too

**Comment by nathanparra** [comment]
> that's an issue with your theme, not Vencord.

and vencord supports betterdiscord themes, so if it works correctly in bc, it should in vencord too

**Comment by Vendicated** [comment]
your theme is boldly assuming there will always only be 3 elements. Adding the game activity toggle adds a fourth so your theme breaks. This is simply your theme at fault, complain to the author, fix it yourself, or use a different theme.

**Comment by nathanparra** [comment]
> 



> your theme is boldly assuming there will always only be 3 elements. Adding the game activity toggle adds a fourth so your theme breaks. This is simply your theme at fault. Complain to the author, fix it yourself, use a different theme or don't use the plugin.

Logically, if I knew how to fix it, I wouldn't be here asking for support for both.
https://github.com/ClearVision/ClearVision-v6/issues/131

**Comment by nathanparra** [comment]
> your theme is boldly assuming there will always only be 3 elements. Adding the game activity toggle adds a fourth so your theme breaks. This is simply your theme at fault. Complain to the author, fix it yourself, use a different theme or don't use the plugin.

and the problem only exist in Vencord, i no think that autor of theme can help..
