### ISSUE TITLE
[Feature Request] An Improvement to the MessageClickActions Plugin

### ISSUE THREAD

**Issue by HappySama** [Vendicated/Vencord#985]
### Discord Account

The Prodigy#0001

### What is it that you'd like to see?

The MessageClickActions Plugin works similarly like the "Double Click To Edit" BetterDiscord Plugin .(https://betterdiscord.app/plugin/Double%20Click%20To%20Edit), But it lacks one amazing addition to it, Which is the ability to double click to reply as well, it is mentioned in the link I provided above and already added there, so it would be awesome if it gets added here on Vencord too!

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
Added
